# Введение

# imports

In [1]:
import itertools
import json

import numpy as np
import pandas as pd
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", None)

import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, clear_output
import ast
import random
from matplotlib.lines import Line2D


RANDOM_STATE = 42

# Данные/EDA

In [2]:
raw_features = pd.read_csv("train_features.csv")
raw_features.head()

,match_id_hash,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed
0,a400b8f29dece5f4d266f49f1ae2e98a,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.0,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.00,0,0,0,0
1,b9c57c450ce74a2af79c9ce96fac144d,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.5,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.00,0,0,0,0
2,6db558535151ea18ca70a6892197db41,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.0,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.00,0,0,0,0
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.0,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.00,0,0,2,0
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.5,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.25,0,0,0,0

In [3]:
test_features = pd.read_csv("test_features (1).csv")

In [4]:
raw_features['lobby_type'].value_counts()

lobby_type
7    27049
0    12626
Name: count, dtype: int64

In [5]:
raw_targets = pd.read_csv("train_targets.csv")
raw_targets.head()

,match_id_hash,game_time,radiant_win,duration,time_remaining,next_roshan_team
0,a400b8f29dece5f4d266f49f1ae2e98a,155,False,992,837,NaN
1,b9c57c450ce74a2af79c9ce96fac144d,658,True,1154,496,NaN
2,6db558535151ea18ca70a6892197db41,21,True,1503,1482,Radiant
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,True,1952,1376,NaN
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,False,2001,1548,NaN

In [6]:
def create_features(df):
    # какие характеристики суммируем для каждой команды
    metrics = ["gold", "kills", "deaths", "level"]

    for m in metrics:
        # radiant
        r_cols = [f"r{i}_{m}" for i in range(1, 6)]
        df[f"radiant_total_{m}"] = df[r_cols].sum(axis=1)

        # dire
        d_cols = [f"d{i}_{m}" for i in range(1, 6)]
        df[f"dire_total_{m}"] = df[d_cols].sum(axis=1)

        # разница
        df[f"radiant_{m}_advantage"] = df[f"radiant_total_{m}"] - df[f"dire_total_{m}"]

    # итоговая метрика убийств и смертей
    df["total_kills_deaths"] = (
        df["radiant_total_kills"] +
        df["dire_total_kills"] +
        df["radiant_total_deaths"] +
        df["dire_total_deaths"]
    )
    
    return df

In [7]:
df_feats = create_features(raw_features)

In [8]:
df_feats

,match_id_hash,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed,radiant_total_gold,dire_total_gold,radiant_gold_advantage,radiant_total_kills,dire_total_kills,radiant_kills_advantage,radiant_total_deaths,dire_total_deaths,radiant_deaths_advantage,radiant_total_level,dire_total_level,radiant_level_advantage,total_kills_deaths
0,a400b8f29dece5f4d266f49f1ae2e98a,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00000,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00000,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00000,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.000,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.0000,0,0,0,0,2037,3948,-1911,0,1,-1,1,0,1,9,13,-4,2
1,b9c57c450ce74a2af79c9ce96fac144d,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25000,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25000,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50000,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.500,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.0000,0,0,0,0,18172,13144,5028,16,3,13,4,16,-12,37,30,7,39
2,6db558535151ea18ca70a6892197db41,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00000,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00000,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00000,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.000,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.0000,0,0,0,0,880,480,400,0,0,0,0,0,0,5,5,0,0
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00000,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50000,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50000,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.000,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.0000,0,0,2,0,13348,11301,2047,6,1,5,2,7,-5,32,28,4,16
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25000,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25000,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25000,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.500,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.2500,0,0,0,0,8079,9177,-1098,2,4,-2,4,2,2,25,26,-1,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39670,defd0caeed6ea83d7d5fbdec013fe7d1,1783,22,0,8,23,3,1,9,9,0,6283,13,7847,0,1380,710.93820,13,144,100,90.944490,0,0,8,0,0.500000,0,0,10,19,49,2,7,8,7,8838,83,10815,1760,1760,530.93800,15,74,76,41.750020,0,0,2,0,0.500000,0,0,1,0,7,4,7,8,4,8530,66,9270,0,1580,1162.93860,14,140,98,71.732760,0,0,6,0,0.600000,0,0,0,0,74,8,3,2,27,14815,161,19257,0,1875,1581.93900,21,144,100,24.060377,0,0,4,0,0.500000,2,0,2,4,63,4,6,5,14,9864,91,10367,1000,1000,554.93805,15,140,138,0.000000,0,0,14,1,0.450000,1,0,0,0,14,6,7,11,6,9371,67,11911,0,2515,1275.93870,16,134,98,39.090730,0,0,6,0,0.53125,0,0,1,2,36,8,1,11,2,13071,143,16893,1560,1560,1356.93880,19,124,78,4.432127,0,0,7,0,0.59375,1,0,0,0,32,7,4,10,7,7937,25,10579,1120,1120,494.93796,15,124,164,0.000000,0,0,9,0,0.53125,0,0,3,2,8,10,5,6,21,15226,183,16164,1667,1680,602.93805,19,126,76,0.799805,0,0,9,0,0.500,2,0,0,0,5,1,4,17,0,6033,20,9742,1040,1040,830.93830,14,130,76,26.493834,6,2,3,0,0.5625,0,0,7,2,48330,51638,-3308,19,32,-13,32,21,11,78,83,-5,104
39671,bc7a87ed5f9c2bca55f9f7a93da0b0c5,377,22,7,1,0,14,0,2,1,1,809,2,1102,0,900,290.93777,4,84,156,1.266357,0,0,0,0,0.500000,0,0,0,0,80,1,1,0,6,1692,21,1323,627,680,278.93777,4,174,100,0.000000,0,0,0,0,0.500000,0,0,0,0,12,0,0,1,3,1671,22,2345,509,920,506.93800,6,112,114,0.000000,0,0,0,0,0.500000,0,0,0,0,3,1,0,1,2,1443,2,1150,761,840,458.93793,4,176,94,0.000000,3,1,6,1,1.000000,0,0,1,1,63,0,0,0,0,1173,9,1505,523,660,350.93784,4,86,156,0.000000,0,0,2,0,0.000000,0,0,0,1,88,0,1,1,2,1039,7,1097,700,700,374.93787,4,174,110,10.097570,0,0,1,0,0.50000,0,0,0,0,47,1,0,0,0,967,3,1154,573,800,350.93784,4,178,108,0.000000,0,0,0,0,0.50000,0,0,0,0,11,1,1,0,8,2184,29,2964,820,820,470.93796,7,120,122,0.000000,0,0,2,0,0.50000,0,0,0,0,27,0,0,0,6,1000,2,838,509,740,422.93790,3,84,156,6.298479,3,1,4,0,0.000,0,0,1,1,73,0,0,0,10,3203,41,2510,95,920,494.93796,6,90,158,0.000000,0,0,1,0,0.0000,0,0,0,0,6788,8393,-1605,2,2,0,3,2,1,22,24,-2,9
39672,e2ca68ac1a6847f4a37f6c9c8ee8695b,643,22,7,1,23,63,1,4,0,2,1747,4,2677,369,780,422.93790,6,80,138,0.000000,0,0,4,0,0.250000,0,0,0,0,27,0,3,2,2,1331,2,1737,780,780,470.93796,5,164,96,26.693481,0,0,3,0,0.500000,0,0,3,0,110,0,10,1,0,1055,0,379,345,680,326.93780,2,106,110,0.000000,0,0,0,0,0.250000,0,0,0,0,10,3,2,0,15,4191,44,3760,440,640,374.93787,8,176,84,0.000000,0,0,3,0,0.750000,0,0,0,0,49,0,1,0,7,3028,44,3661,0,1360,410.93790,8,88,144,5.065430,0,0,0,0,0.000000,0,0,1,1,120,3,0,1,3,3148,27,2941,679,820,398.93787,7,174,90,-0.983398,0,0,2,0,0.20000,0,0,0,0,40,0,3,4,0,2208,10,1847,798,820,530.93800,5,174,90,0.000000,0,0,5,0,0.20000,0,0,0,0,30,3,1,2,4,2266,3,2620,465,760,554.93805,6,80,154,11.063930,3,1,6,0,0.25000,0,0,3,3,44,3,0,3,21,4453,48,4659,968,980,410.93790,9,82,154,0.000000,0,0,2,0,0.300,0,0,0,0,11,9,0,1,14,5431,51,5420,773,1000,686.93820,10,120,124,2.532715,0,0,3,1,0.5000,0,0,1,0,11352,17506,-6154,4,18,-14,20,4,16,29,37,-8,46
39673,47ad6454ede66c1c78fdaa9391dfc556,2405,22,7,12,4,22,3,8,14,7,14375,168,19847,0,1995,1843.93920,21,134,154,8.850186,0,0,15,0,0.404762,1,0,1,0,32,9,12,10,2,12448,42,18449,1343,1500,794.93823,21,130,150,0.000000,0,0,18,0,0.428571,0,0,1,1,81,8,3,9,7,21451,305,27114,5200,5200,854.93830,25,122,124,23.931118,0,0,8,0,0.404762,2,0,0,0,91,1,14,13,6,8134,11,13382,1280,1280,698.93820,17,94,132,0.000000,0,0,11,0,0.333333,0,0,14,2,23,21,3,7,15,32403,413,26950,1550,2760,902.93835,25,116,134,35.064312,0,0,10,0,0.666667,3,1,0,0,26,9,11,15,1,11499,20,18654,0,1820,1484.93900,21,120,138,132.343580,0,0,5,1,0.60000,0,0,13,4,53,6,12,17,1,19420,276,20634,0,1960,1574.93900,22,76,146,0.000000,0,0,1,0,0.57500,1,0,0,2,10,10,6,2,22,17934,236,22866,813,1500,722.93820,23,126,158,5.569586,0,0,10,0,0.30000,0,0,2,0,42,5,6,18,1,14477,136,19556,1657,2260,794.93823,21,118,164,40.033060,1,1,9,0,0.575,1,0,0,1,11,9,7,16,26,18231,181,25354,1840,2525,1548.93900,24,98,158,17.583984,3,1,4,0,0.6250,0,0,0,0,88811,81561,7250,42,39,3,40,42,-2,109,111,-2,163
39674,9928dfde50efcbdb2055da23dcdbc101,1775,22,0,10,13,32,3,4,15,0,8847,20,11151,0,1100,602.93805,15,118,120,0.000000,0,0,16,0,0.600000,0,0,5,6,69,5,7,11,5,11458,102,10823,2267,2280,698.93820,15,174,112,32.059246,0,0,7,0,0.533333,1,0,0,0,76,10,0,5,29,16708,201,19598,2750,2750,1756.93920,21,178,110,46.655327,0,0,3,0,0.500000,2,0,0,0,10,2,5,7,2,13150,194,16362,1061,1200,614.93810,19,106,114,2.399467,1,1,6,0,0.300000,1,0,0,0,68,10,4,10,0,9666,48,13504,1440,1440,1380.93880,17,180,108,14.772326,2,1,2,0,0.666667,0,0,8,4,49,1,7,4,6,10347,105,11612,2180,2180,578.93805,16,178,166,22.585493,0,0,8,0,0.25000,2,0,0,0,110,4,10,5,4,9140,49,9222,0,1560,758.93823,14,122,126,4.432282,2,1,13,0,0.45000,0,0,9,8,62,4,4,10,3,8229,10,10008,528,1120,888.93835,14,140,134,0.928828,0,0,4,0,0.70000,0,0,1,0,106,8,3,6,15,14982,183,15506,1832,1840,1226.93870,19,78,166,36.424126,2,1,12,1,0.700,1,0,1,0,95,3,6,8,19,14096,225,15424,2031,2060,470.93796,19,104,162,8.331238,0,0,1,0,0.5500,1,0,0,0,59829,56794,3035,30,20,10,20,30,-10,87,82,5,100

In [9]:

train_jsonl_path = "DOTA 2/train_matches.jsonl"
test_jsonl_path = "DOTA 2/test_matches.jsonl"

df_train_matches = pd.read_json(train_jsonl_path, lines=True)
df_test_matches  = pd.read_json(test_jsonl_path, lines=True)

df_json_matches = pd.concat([df_train_matches, df_test_matches], ignore_index=True)

print(df_train_matches.columns)

Index(['game_time', 'match_id_hash', 'teamfights', 'objectives', 'chat',
       'game_mode', 'lobby_type', 'players', 'targets'],
      dtype='object')

In [10]:
df_train_matches.sample(10)

,game_time,match_id_hash,teamfights,objectives,chat,game_mode,lobby_type,players,targets
32876,711,b38d866f28ba17abab6b66ede83b19ea,"[{'start': 607.781, 'end': 666.571, 'last_deat...","[{'time': 119.038, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 128, 'time': -73.663, 'text':...",22,0,"[{'player_slot': 0, 'hero_id': 14, 'hero_name'...","{'game_time': 711, 'duration': 2564, 'time_rem..."
25694,608,4d6d76a649a8cb73c197830f5abc8741,"[{'start': 182.122, 'end': 224.882, 'last_deat...","[{'time': 142.302, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 131, 'time': 32.907, 'text': ...",23,0,"[{'player_slot': 0, 'hero_id': 35, 'hero_name'...","{'game_time': 608, 'duration': 1387, 'time_rem..."
27047,3165,b7f1ef7f484918ea3bc63efee49d806c,"[{'start': 571.457, 'end': 617.316, 'last_deat...","[{'time': 225.345, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 1, 'time': -77.248, 'text': '...",22,7,"[{'player_slot': 0, 'hero_id': 62, 'hero_name'...","{'game_time': 3165, 'duration': 3750, 'time_re..."
26470,1577,cad70aedb43aaee1abb5a6a845bb6680,"[{'start': 604.443, 'end': 661.899, 'last_deat...","[{'time': 120.498, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 132, 'time': -45.576, 'text':...",4,0,"[{'player_slot': 0, 'hero_id': 20, 'hero_name'...","{'game_time': 1577, 'duration': 3561, 'time_re..."
8057,891,ddb3e0b5588d8d14721a96dd2c01e475,[],"[{'time': 102.408, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 128, 'time': -286.841, 'text'...",22,0,"[{'player_slot': 0, 'hero_id': 14, 'hero_name'...","{'game_time': 891, 'duration': 2845, 'time_rem..."
10527,2258,d92ab87451657006fc74b92c3e619f8f,"[{'start': 146.86, 'end': 178.723, 'last_death...","[{'time': 53.82, 'type': 'CHAT_MESSAGE_FIRSTBL...","[{'player_slot': 1, 'time': 1031.581, 'text': ...",22,0,"[{'player_slot': 0, 'hero_id': 44, 'hero_name'...","{'game_time': 2258, 'duration': 2592, 'time_re..."
15756,1575,f75d446cb5809157d9a92811f669043d,"[{'start': 352.31, 'end': 399.602, 'last_death...","[{'time': 6.498, 'type': 'CHAT_MESSAGE_FIRSTBL...","[{'player_slot': 130, 'time': 527.505, 'text':...",22,7,"[{'player_slot': 0, 'hero_id': 104, 'hero_name...","{'game_time': 1575, 'duration': 2517, 'time_re..."
12910,593,5e1de18ec3769cef3b9e5d7a1d15b7ce,[],"[{'time': 180.756, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 2, 'time': 504.01, 'text': '*...",22,7,"[{'player_slot': 0, 'hero_id': 77, 'hero_name'...","{'game_time': 593, 'duration': 1802, 'time_rem..."
23730,1334,f372eb0bc903c6e3e9ed8cf39da7d295,"[{'start': 294.291, 'end': 329.586, 'last_deat...","[{'time': 264.269, 'type': 'CHAT_MESSAGE_FIRST...",[],22,7,"[{'player_slot': 0, 'hero_id': 87, 'hero_name'...","{'game_time': 1334, 'duration': 2763, 'time_re..."
25777,1382,90902bfba9ea319f7010ce8741c3d8e2,[],"[{'time': 69.55, 'type': 'CHAT_MESSAGE_FIRSTBL...",[],22,7,"[{'player_slot': 0, 'hero_id': 42, 'hero_name'...","{'game_time': 1382, 'duration': 2031, 'time_re..."

In [11]:
longest_match_id = df_train_matches['game_time'].idxmax()

In [13]:
df_train_matches['players'][longest_match_id]

[{'player_slot': 0,
  'hero_id': 35,
  'hero_name': 'npc_dota_hero_sniper',
  'account_id_hash': 'a9c02a54303436304abdc0adcc8e8201',
  'ability_upgrades': [{'ability': 5155, 'time': 464, 'level': 1},
   {'ability': 5154, 'time': 512, 'level': 2},
   {'ability': 5154, 'time': 544, 'level': 3},
   {'ability': 5156, 'time': 593, 'level': 4},
   {'ability': 5154, 'time': 726, 'level': 5},
   {'ability': 5157, 'time': 825, 'level': 6},
   {'ability': 5154, 'time': 908, 'level': 7},
   {'ability': 5156, 'time': 1012, 'level': 8},
   {'ability': 5156, 'time': 1172, 'level': 9},
   {'ability': 5960, 'time': 1264, 'level': 10},
   {'ability': 5156, 'time': 1339, 'level': 11},
   {'ability': 5157, 'time': 1379, 'level': 12},
   {'ability': 5155, 'time': 1454, 'level': 13},
   {'ability': 5155, 'time': 1472, 'level': 14},
   {'ability': 6210, 'time': 1688, 'level': 15},
   {'ability': 5155, 'time': 1772, 'level': 16},
   {'ability': 5157, 'time': 1983, 'level': 17},
   {'ability': 6896, 'time': 2274, 'level': 18},
   {'ability': 5944, 'time': 3168, 'level': 19}],
  'obs_placed': 0,
  'sen_placed': 0,
  'creeps_stacked': 0,
  'camps_stacked': 0,
  'rune_pickups': 5,
  'firstblood_claimed': 0,
  'teamfight_participation': 0.739,
  'towers_killed': 1,
  'roshans_killed': 0,
  'observers_placed': 0,
  'stuns': 0.167,
  'max_hero_hit': {'type': 'max_hero_hit',
   'time': 4481.192,
   'max': True,
   'inflictor': None,
   'unit': 'npc_dota_hero_sniper',
   'key': 'npc_dota_hero_batrider',
   'value': 477,
   'slot': 0,
   'player_slot': 0},
  'times': [0,
   60,
   120,
   180,
   240,
   300,
   360,
   420,
   480,
   540,
   600,
   660,
   720,
   780,
   840,
   900,
   960,
   1020,
   1080,
   1140,
   1200,
   1260,
   1320,
   1380,
   1440,
   1500,
   1560,
   1620,
   1680,
   1740,
   1800,
   1860,
   1920,
   1980,
   2040,
   2100,
   2160,
   2220,
   2280,
   2340,
   2400,
   2460,
   2520,
   2580,
   2640,
   2700,
   2760,
   2820,
   2880,
   2940,
   3000,
   3060,
   3120,
   3180,
   3240,
   3300,
   3360,
   3420,
   3480,
   3540,
   3600,
   3660,
   3720,
   3780,
   3840,
   3900,
   3960,
   4020,
   4080,
   4140,
   4200,
   4260,
   4320,
   4380,
   4440,
   4500,
   4560,
   4620,
   4680,
   4740],
  'gold_t': [41,
   293,
   744,
   1089,
   1681,
   2084,
   2311,
   2952,
   3908,
   4337,
   4730,
   4958,
   5541,
   5987,
   6889,
   7643,
   8187,
   8855,
   9582,
   10235,
   10457,
   10897,
   11730,
   12594,
   13243,
   14158,
   14581,
   15495,
   15949,
   16724,
   16815,
   17355,
   18180,
   18932,
   19672,
   19763,
   20123,
   20896,
   21791,
   22848,
   23372,
   24451,
   25034,
   25689,
   26118,
   26378,
   26803,
   29318,
   30138,
   30789,
   31252,
   31576,
   32590,
   33062,
   33544,
   34110,
   37444,
   38094,
   38477,
   39030,
   39549,
   39640,
   39838,
   40386,
   41031,
   41521,
   41762,
   42400,
   42719,
   43388,
   43956,
   44245,
   45119,
   45710,
   46549,
   47660,
   49692,
   51353,
   52110,
   53102],
  'lh_t': [0,
   2,
   10,
   15,
   20,
   27,
   30,
   38,
   42,
   49,
   56,
   59,
   65,
   73,
   82,
   89,
   92,
   112,
   120,
   128,
   131,
   143,
   157,
   172,
   185,
   201,
   212,
   233,
   242,
   264,
   264,
   280,
   293,
   310,
   324,
   324,
   331,
   348,
   356,
   373,
   381,
   386,
   389,
   404,
   411,
   417,
   424,
   442,
   461,
   475,
   485,
   492,
   515,
   526,
   538,
   552,
   577,
   591,
   599,
   611,
   623,
   623,
   626,
   639,
   652,
   663,
   667,
   680,
   686,
   701,
   714,
   719,
   738,
   751,
   773,
   786,
   800,
   823,
   834,
   846],
  'dn_t': [0,
   1,
   5,
   6,
   7,
   11,
   12,
   14,
   15,
   20,
   23,
   25,
   25,
   26,
   28,
   31,
   31,
   32,
   33,
   33,
   33,
   33,
   33,
   36,
   37,
   37,
   39,
   39,
   39,
   41,
   41,
   41,
   41,
   41,
   41,
   41,
   41,
   42,
   44,
   47,
   47,
   47,
   47,
   50,
   51,
   51,
   51,
   51,
   51,
   52,
   53,
   53,
   54,
   54,
   54,
   55,
   56,
   57,
   57,
   58,
   58,
   58,
   58,
   58,
   58,
   58,
   58,
   62,
   62,
   62,
   62,
   62,
   62,
   63,
   63,
   63,
   63,
   63,
   63,
   63],
  'xp_t': [0,
   91,
   427,
   741,
   1147,
   1513,
   1708,
   2114,
   2697,
   3016,
   3398,
   3647,
   4066,
   4268,
   4793,
   5366,
   5935,
   7290,
   8801,
   9164,
   9308,
   9750,
   10338,
   11304,
   11856,
   12866,
   13341,
   14166,
   14445,
   15661,
   15661,
   16468,
   17335,
   18193,
   18981,
   18981,
   19208,
   19698,
   21202,
   22292,
   22654,
   24812,
   25013,
   25505,
   25743,
   25930,
   26239,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997,
   26997],
  'obs_log': [],
  'sen_log': [],
  'obs_left_log': [],
  'sen_left_log': [],
  'purchase_log': [{'time': -89.778, 'key': 'tango'},
   {'time': -89.778, 'key': 'branches'},
   {'time': -89.778, 'key': 'branches'},
   {'time': -89.778, 'key': 'tpscroll'},
   {'time': -89.778, 'key': 'slippers'},
   {'time': -89.778, 'key': 'enchanted_mango'},
   {'time': 4.199, 'key': 'circlet'},
   {'time': 49.055, 'key': 'magic_stick'},
   {'time': 88.145, 'key': 'wraith_band'},
   {'time': 92.611, 'key': 'magic_wand'},
   {'time': 92.611, 'key': 'magic_stick'},
   {'time': 163.793, 'key': 'sobi_mask'},
   {'time': 175.657, 'key': 'ring_of_protection'},
   {'time': 225.412, 'key': 'ring_of_basilius'},
   {'time': 225.412, 'key': 'ring_of_aquila'},
   {'time': 226.378, 'key': 'blades_of_attack'},
   {'time': 341.417, 'key': 'boots'},
   {'time': 355.78, 'key': 'tpscroll'},
   {'time': 443.258, 'key': 'lifesteal'},
   {'time': 461.621, 'key': 'phase_boots'},
   {'time': 461.621, 'key': 'blades_of_attack'},
   {'time': 488.314, 'key': 'tango'},
   {'time': 556.764, 'key': 'quarterstaff'},
   {'time': 626.114, 'key': 'mask_of_madness'},
   {'time': 637.044, 'key': 'slippers'},
   {'time': 836.862, 'key': 'staff_of_wizardry'},
   {'time': 837.029, 'key': 'ring_of_health'},
   {'time': 837.162, 'key': 'force_staff'},
   {'time': 888.45, 'key': 'boots_of_elves'},
   {'time': 923.908, 'key': 'tpscroll'},
   {'time': 932.472, 'key': 'boots_of_elves'},
   {'time': 1018.785, 'key': 'ogre_axe'},
   {'time': 1018.918, 'key': 'boots_of_elves'},
   {'time': 1036.78, 'key': 'dragon_lance'},
   {'time': 1036.78, 'key': 'hurricane_pike'},
   {'time': 1116.061, 'key': 'gloves'},
   {'time': 1194.108, 'key': 'tpscroll'},
   {'time': 1313.446, 'key': 'mithril_hammer'},
   {'time': 1358.302, 'key': 'tpscroll'},
   {'time': 1364.733, 'key': 'maelstrom'},
   {'time': 1481.538, 'key': 'shadow_amulet'},
   {'time': 1521.062, 'key': 'claymore'},
   {'time': 1521.262, 'key': 'tpscroll'},
   {'time': 1531.793, 'key': 'invis_sword'},
   {'time': 1802.126, 'key': 'tpscroll'},
   {'time': 2108.938, 'key': 'tpscroll'},
   {'time': 2489.467, 'key': 'ultimate_orb'},
   {'time': 2489.635, 'key': 'ultimate_orb'},
   {'time': 2489.768, 'key': 'skadi'},
   {'time': 2489.768, 'key': 'point_booster'},
   {'time': 2591.716, 'key': 'hyperstone'},
   {'time': 2657.473, 'key': 'mjollnir'},
   {'time': 3421.743, 'key': 'tpscroll'},
   {'time': 3440.741, 'key': 'eagle'},
   {'time': 3440.774, 'key': 'butterfly'},
   {'time': 3440.774, 'key': 'talisman_of_evasion'},
   {'time': 3633.564, 'key': 'hyperstone'},
   {'time': 3633.698, 'key': 'moon_shard'},
   {'time': 3633.698, 'key': 'hyperstone'},
   {'time': 3872.778, 'key': 'ultimate_orb'},
   {'time': 3953.661, 'key': 'silver_edge'},
   {'time': 4176.155, 'key': 'ogre_axe'},
   {'time': 4249.268, 'key': 'ogre_axe'},
   {'time': 4250.563, 'key': 'mithril_hammer'},
   {'time': 4258.266, 'key': 'staff_of_wizardry'},
   {'time': 4258.299, 'key': 'circlet'},
   {'time': 4258.332, 'key': 'mantle'},
   {'time': 4258.366, 'key': 'null_talisman'},
   {'time': 4258.432, 'key': 'dagon'},
   {'time': 4297.844, 'key': 'ogre_axe'},
   {'time': 4298.043, 'key': 'mithril_hammer'},
   {'time': 4298.973, 'key': 'black_king_bar'},
   {'time': 4495.801, 'key': 'boots'},
   {'time': 4495.967, 'key': 'travel_boots'}],
  'kills_log': [{'time': 209.915, 'key': 'npc_dota_hero_batrider'},
   {'time': 392.937, 'key': 'npc_dota_hero_crystal_maiden'},
   {'time': 454.656, 'key': 'npc_dota_hero_batrider'},
   {'time': 458.855, 'key': 'npc_dota_hero_sand_king'},
   {'time': 672.702, 'key': 'npc_dota_hero_crystal_maiden'},
   {'time': 788.807, 'key': 'npc_dota_hero_sand_king'},
   {'time': 833.63, 'key': 'npc_dota_hero_crystal_maiden'},
   {'time': 859.723, 'key': 'npc_dota_hero_sand_king'},
   {'time': 913.31, 'key': 'npc_dota_hero_crystal_maiden'},
   {'time': 1093.6, 'key': 'npc_dota_hero_sand_king'},
   {'time': 2224.632, 'key': 'npc_dota_hero_nevermore'},
   {'time': 2240.519, 'key': 'npc_dota_hero_batrider'},
   {'time': 2450.602, 'key': 'npc_dota_hero_razor'},
   {'time': 2768.585, 'key': 'npc_dota_hero_sand_king'},
   {'time': 2803.704, 'key': 'npc_dota_hero_nevermore'},
   {'time': 3313.24, 'key': 'npc_dota_hero_nevermore'},
   {'time': 3320.766, 'key': 'npc_dota_hero_crystal_maiden'},
   {'time': 3324.813, 'key': 'npc_dota_hero_razor'},
   {'time': 4474.352, 'key': 'npc_dota_hero_batrider'},
   {'time': 4477.141, 'key': 'npc_dota_hero_crystal_maiden'},
   {'time': 4522.098, 'key': 'npc_dota_hero_nevermore'},
   {'time': 4571.936, 'key': 'npc_dota_hero_sand_king'},
   {'time': 4735.129, 'key': 'npc_dota_hero_sand_king'}],
  'buyback_log': [{'time': 2405.749,
    'slot': 0,
    'type': 'buyback_log',
    'player_slot': 0},
   {'time': 4535.612, 'slot': 0, 'type': 'buyback_log', 'player_slot': 0}],
  'runes_log': [{'time': 2.966, 'key': 5},
   {'time': 1340.773, 'key': 5},
   {'time': 1480.405, 'key': 5},
   {'time': 1648.764, 'key': 5},
   {'time': 2300.724, 'key': 5}],
  'obs': {},
  'sen': {},
  'actions': {'1': 10185,
   '2': 267,
   '3': 539,
   '4': 1661,
   '5': 85,
   '6': 42,
   '7': 7,
   '8': 305,
   '9': 2,
   '10': 215,
   '11': 15,
   '12': 3,
   '13': 2,
   '14': 6,
   '15': 23,
   '16': 67,
   '17': 11,
   '18': 2,
   '19': 38,
   '23': 2,
   '27': 3,
   '32': 3},
  'pings': {'0': 173},
  'purchase': {'tango': 2,
   'branches': 2,
   'tpscroll': 9,
   'slippers': 2,
   'enchanted_mango': 1,
   'circlet': 2,
   'magic_stick': 2,
   'recipe_wraith_band': 1,
   'wraith_band': 1,
   'magic_wand': 1,
   'sobi_mask': 1,
   'ring_of_protection': 1,
   'ring_of_basilius': 1,
   'ring_of_aquila': 1,
   'blades_of_attack': 2,
   'boots': 2,
   'lifesteal': 1,
   'phase_boots': 1,
   'quarterstaff': 1,
   'mask_of_madness': 1,
   'staff_of_wizardry': 2,
   'ring_of_health': 1,
   'force_staff': 1,
   'recipe_force_staff': 1,
   'boots_of_elves': 3,
   'ogre_axe': 4,
   'dragon_lance': 1,
   'hurricane_pike': 1,
   'gloves': 1,
   'mithril_hammer': 3,
   'recipe_maelstrom': 1,
   'maelstrom': 1,
   'shadow_amulet': 1,
   'claymore': 1,
   'invis_sword': 1,
   'ultimate_orb': 3,
   'skadi': 1,
   'point_booster': 1,
   'hyperstone': 3,
   'recipe_mjollnir': 1,
   'mjollnir': 1,
   'eagle': 1,
   'butterfly': 1,
   'talisman_of_evasion': 1,
   'moon_shard': 1,
   'recipe_silver_edge': 3,
   'silver_edge': 1,
   'mantle': 1,
   'null_talisman': 1,
   'recipe_null_talisman': 1,
   'dagon': 1,
   'recipe_dagon': 1,
   'black_king_bar': 1,
   'recipe_black_king_bar': 1,
   'travel_boots': 1,
   'recipe_travel_boots': 1},
  'gold_reasons': {'0': 1409,
   '1': -3296,
   '2': -4663,
   '6': 9620,
   '11': 764,
   '12': 10434,
   '13': 33913},
  'xp_reasons': {'0': 1, '1': 6280, '2': 20717},
  'killed': {'npc_dota_creep_badguys_melee': 41213,
   'npc_dota_creep_goodguys_melee': 9094,
   'npc_dota_creep_badguys_ranged': 15057,
   'npc_dota_creep_goodguys_ranged': 1666,
   'npc_dota_hero_batrider': 545,
   'npc_dota_hero_crystal_maiden': 805,
   'npc_dota_badguys_siege': 952,
   'npc_dota_hero_sand_king': 1216,
   'npc_dota_neutral_dark_troll': 3164,
   'npc_dota_dark_troll_warlord_skeleton_warrior': 1198,
   'npc_dota_neutral_dark_troll_warlord': 1465,
   'npc_dota_neutral_alpha_wolf': 981,
   'npc_dota_neutral_giant_wolf': 2430,
   'npc_dota_neutral_satyr_trickster': 1243,
   'npc_dota_neutral_centaur_outrunner': 1371,
   'npc_dota_neutral_centaur_khan': 695,
   'npc_dota_neutral_satyr_soulstealer': 1525,
   'npc_dota_neutral_prowler_shaman': 285,
   'npc_dota_neutral_prowler_acolyte': 676,
   'npc_dota_neutral_ogre_magi': 1443,
   'npc_dota_neutral_ogre_mauler': 2819,
   'npc_dota_neutral_polar_furbolg_ursa_warrior': 708,
   'npc_dota_neutral_polar_furbolg_champion': 682,
   'npc_dota_neutral_enraged_wildkin': 636,
   'npc_dota_neutral_wildkin': 1651,
   'npc_dota_neutral_mud_golem': 3560,
   'npc_dota_neutral_mud_golem_split': 6733,
   'npc_dota_neutral_big_thunder_lizard': 608,
   'npc_dota_neutral_small_thunder_lizard': 1407,
   'npc_dota_neutral_rock_golem': 1520,
   'npc_dota_neutral_forest_troll_berserker': 162,
   'npc_dota_neutral_kobold_taskmaster': 222,
   'npc_dota_neutral_black_dragon': 152,
   'npc_dota_neutral_black_drake': 500,
   'npc_dota_neutral_satyr_hellcaller': 324,
   'npc_dota_neutral_granite_golem': 556,
   'npc_dota_neutral_harpy_storm': 277,
   'npc_dota_neutral_harpy_scout': 492,
   'npc_dota_creep_badguys_melee_upgraded': 68490,
   'npc_dota_creep_badguys_ranged_upgraded': 29015,
   'npc_dota_badguys_siege_upgraded': 2253,
   'npc_dota_hero_nevermore': 684,
   'npc_dota_hero_razor': 192,
   'npc_dota_badguys_tower2_mid': 56,
   'npc_dota_goodguys_siege': 203,
   'npc_dota_beastmaster_boar_4': 357},
  'item_uses': {'tango': 6,
   'magic_wand': 7,
   'tpscroll': 9,
   'ring_of_aquila': 2,
   'phase_boots': 161,
   'tango_single': 1,
   'mask_of_madness': 60,
   'force_staff': 2,
   'hurricane_pike': 20,
   'invis_sword': 8,
   'mjollnir': 8,
   'butterfly': 10,
   'moon_shard': 1,
   'black_king_bar': 1,
   'silver_edge': 2,
   'travel_boots': 1},
  'ability_uses': {'sniper_shrapnel': 43, 'sniper_assassinate': 7},
  'hero_hits': {'null': 254,
   'sniper_shrapnel': 181,
   'sniper_assassinate': 7,
   'maelstrom': 12,
   'mjollnir': 73},
  'damage': {'npc_dota_hero_batrider': 13210,
   'npc_dota_creep_badguys_melee': 104695,
   'npc_dota_creep_goodguys_melee': 13020,
   'npc_dota_creep_badguys_ranged': 33062,
   'npc_dota_creep_goodguys_ranged': 1952,
   'npc_dota_hero_crystal_maiden': 8818,
   'npc_dota_badguys_siege': 5898,
   'npc_dota_hero_sand_king': 7365,
   'npc_dota_hero_razor': 12093,
   'npc_dota_badguys_tower1_bot': 540,
   'npc_dota_neutral_dark_troll': 8116,
   'npc_dota_neutral_dark_troll_warlord': 7357,
   'npc_dota_dark_troll_warlord_skeleton_warrior': 2129,
   'npc_dota_neutral_alpha_wolf': 4144,
   'npc_dota_neutral_giant_wolf': 7393,
   'npc_dota_neutral_satyr_soulstealer': 5174,
   'npc_dota_neutral_centaur_outrunner': 3038,
   'npc_dota_neutral_centaur_khan': 4845,
   'npc_dota_neutral_satyr_trickster': 2349,
   'npc_dota_hero_nevermore': 11631,
   'npc_dota_neutral_prowler_acolyte': 3006,
   'npc_dota_neutral_prowler_shaman': 2806,
   'npc_dota_neutral_ogre_magi': 4308,
   'npc_dota_neutral_ogre_mauler': 11810,
   'npc_dota_neutral_polar_furbolg_ursa_warrior': 3842,
   'npc_dota_neutral_polar_furbolg_champion': 2479,
   'npc_dota_neutral_enraged_wildkin': 3995,
   'npc_dota_neutral_wildkin': 3327,
   'npc_dota_neutral_mud_golem': 13394,
   'npc_dota_neutral_mud_golem_split': 9426,
   'npc_dota_neutral_big_thunder_lizard': 4571,
   'npc_dota_neutral_small_thunder_lizard': 6686,
   'npc_dota_neutral_rock_golem': 6411,
   'npc_dota_neutral_granite_golem': 6605,
   'npc_dota_neutral_forest_troll_berserker': 546,
   'npc_dota_neutral_kobold_taskmaster': 442,
   'npc_dota_neutral_black_dragon': 2043,
   'npc_dota_neutral_black_drake': 2082,
   'npc_dota_neutral_satyr_hellcaller': 2399,
   'npc_dota_neutral_harpy_storm': 719,
   'npc_dota_neutral_harpy_scout': 1069,
   'npc_dota_creep_badguys_melee_upgraded': 214490,
   'npc_dota_creep_badguys_ranged_upgraded': 76331,
   'npc_dota_badguys_siege_upgraded': 13310,
   'illusion_npc_dota_hero_batrider': 2026,
   'npc_dota_badguys_tower2_mid': 56,
   'npc_dota_badguys_tower3_mid': 160,
   'npc_dota_goodguys_siege': 203,
   'npc_dota_beastmaster_boar_4': 357},
  'damage_taken': {'npc_dota_hero_batrider': 4205,
   'npc_dota_creep_badguys_ranged': 328,
   'npc_dota_creep_badguys_melee': 933,
   'npc_dota_badguys_siege': 57,
   'npc_dota_hero_sand_king': 625,
   'npc_dota_hero_crystal_maiden': 1395,
   'npc_dota_hero_razor': 4179,
   'npc_dota_neutral_dark_troll': 60,
   'npc_dota_neutral_dark_troll_warlord': 348,
   'npc_dota_dark_troll_warlord_skeleton_warrior': 88,
   'npc_dota_neutral_giant_wolf': 127,
   'npc_dota_neutral_satyr_soulstealer': 74,
   'npc_dota_neutral_centaur_khan': 212,
   'npc_dota_neutral_satyr_trickster': 20,
   'npc_dota_neutral_centaur_outrunner': 64,
   'npc_dota_hero_nevermore': 12871,
   'npc_dota_neutral_ogre_magi': 32,
   'npc_dota_neutral_ogre_mauler': 43,
   'npc_dota_neutral_polar_furbolg_champion': 29,
   'npc_dota_neutral_wildkin': 52,
   'npc_dota_neutral_small_thunder_lizard': 227,
   'npc_dota_neutral_forest_troll_berserker': 35,
   'npc_dota_neutral_kobold_taskmaster': 6,
   'npc_dota_neutral_black_drake': 59,
   'npc_dota_neutral_black_dragon': 52,
   'npc_dota_neutral_satyr_hellcaller': 28,
   'npc_dota_neutral_mud_golem': 58,
   'npc_dota_neutral_granite_golem': 95,
   'npc_dota_neutral_rock_golem': 75,
   'npc_dota_neutral_enraged_wildkin': 31,
   'npc_dota_neutral_mud_golem_split': 7,
   'npc_dota_neutral_alpha_wolf': 37,
   'npc_dota_creep_badguys_ranged_upgraded': 460,
   'npc_dota_creep_badguys_melee_upgraded': 250,
   'npc_dota_badguys_siege_upgraded': 57},
  'damage_inflictor': {'null': 32486,
   'sniper_shrapnel': 8878,
   'sniper_assassinate': 2145,
   'maelstrom': 949,
   'mjollnir': 8659},
  'runes': {'5': 5},
  'killed_by': {'npc_dota_hero_batrider': 2,
   'npc_dota_hero_crystal_maiden': 1,
   'npc_dota_hero_nevermore': 4},
  'kill_streaks': {'3': 3, '4': 2, '5': 2, '6': 2, '7': 1, '8': 1},
  'multi_kills': {'2': 2, '3': 1},
  'life_state': {'0': 8955, '1': 46, '2': 483},
  'healing': {'npc_dota_hero_sniper': 6112},
  'damage_inflictor_received': {'null': 3500,
   'batrider_sticky_napalm': 1472,
   'batrider_firefly': 2150,
   'sandking_burrowstrike': 291,
   'crystal_maiden_frostbite': 494,
   'sandking_caustic_finale': 15,
   'crystal_maiden_crystal_nova': 577,
   'razor_plasma_field': 2050,
   'sandking_sand_storm': 38,
   'cyclone': 381,
   'nevermore_requiem': 7399,
   'batrider_flamebreak': 76,
   'razor_unstable_current': 222,
   'razor_eye_of_the_storm': 100,
   'nevermore_shadowraze3': 874,
   'nevermore_shadowraze1': 1817,
   'nevermore_shadowraze2': 1819},
  'randomed': False,
  'pred_vict': True,
  'gold': 53105,
  'lh': 846,
  'xp': 26997,
  'x': 152,
  'y': 126,
  'hero_inventory': [{'id': 'item_black_king_bar', 'cooldown': 0},
   {'id': 'item_skadi', 'cooldown': 0},
   {'id': 'item_silver_edge', 'cooldown': 0},
   {'id': 'item_butterfly', 'cooldown': 0},
   {'id': 'item_hurricane_pike', 'cooldown': 0},
   {'id': 'item_mjollnir', 'cooldown': 34.41}],
  'hero_stash': [],
  'health': 2523,
  'max_health': 2845,
  'max_mana': 1884.939,
  'level': 25,
  'kills': 21,
  'deaths': 7,
  'assists': 13,
  'denies': 63,
  'nearby_creep_death_count': 1161},
 {'player_slot': 1,
  'hero_id': 20,
  'hero_name': 'npc_dota_hero_vengefulspirit',
  'account_id_hash': 'bd58d4404a9bb16211ba4f014ed7cebe',
  'ability_upgrades': [{'ability': 5122, 'time': 366, 'level': 1},
   {'ability': 5123, 'time': 463, 'level': 2},
   {'ability': 5122, 'time': 655, 'level': 3},
   {'ability': 5124, 'time': 777, 'level': 4},
   {'ability': 5122, 'time': 930, 'level': 5},
   {'ability': 5125, 'time': 1105, 'level': 6},

In [14]:
def attach_player_feature(raw_features, df_matches, feature: str, overwrite=False):
    """
    Добавляет к raw_features фичу по игрокам из df_matches["players"].
    Колонки будут вида r1_<feature>, ..., r5_<feature>, d1_<feature>, ..., d5_<feature>.
    Джойн по match_id_hash.
    
    overwrite=False не трогает уже существующие колонки этого feature.
    """

    def extract_for_match(players):
        row = {}
        for p in players:
            slot = p.get("player_slot")
            if slot is None:
                continue

            if slot < 128:
                prefix = "r"
                idx = slot + 1
            else:
                prefix = "d"
                idx = slot - 128 + 1

            col_name = f"{prefix}{idx}_{feature}"
            row[col_name] = p.get(feature)

        return pd.Series(row)

    tmp = df_matches[["match_id_hash", "players"]].copy()
    features_df = tmp["players"].apply(extract_for_match)
    tmp = pd.concat([tmp[["match_id_hash"]], features_df], axis=1)

 
    left = raw_features.set_index("match_id_hash")
    right = tmp.set_index("match_id_hash")

    if not overwrite:
        new_cols = [c for c in right.columns if c not in left.columns]
        right = right[new_cols]

    result = left.join(right, how="left").reset_index()
    return result

In [15]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="pred_vict"
)

In [16]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="hero_name"
)

In [17]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="damage"
)

In [19]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="gold_t"
)

In [20]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="xp_t"
)

In [21]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="lh_t"
)

In [22]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="dn_t"
)

In [23]:
raw_features.head()

,match_id_hash,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed,radiant_total_gold,dire_total_gold,radiant_gold_advantage,radiant_total_kills,dire_total_kills,radiant_kills_advantage,radiant_total_deaths,dire_total_deaths,radiant_deaths_advantage,radiant_total_level,dire_total_level,radiant_level_advantage,total_kills_deaths,r1_pred_vict,r2_pred_vict,r3_pred_vict,r4_pred_vict,r5_pred_vict,d1_pred_vict,d2_pred_vict,d3_pred_vict,d4_pred_vict,d5_pred_vict,r1_hero_name,r2_hero_name,r3_hero_name,r4_hero_name,r5_hero_name,d1_hero_name,d2_hero_name,d3_hero_name,d4_hero_name,d5_hero_name,r1_damage,r2_damage,r3_damage,r4_damage,r5_damage,d1_damage,d2_damage,d3_damage,d4_damage,d5_damage,r1_gold_t,r2_gold_t,r3_gold_t,r4_gold_t,r5_gold_t,d1_gold_t,d2_gold_t,d3_gold_t,d4_gold_t,d5_gold_t,r1_xp_t,r2_xp_t,r3_xp_t,r4_xp_t,r5_xp_t,d1_xp_t,d2_xp_t,d3_xp_t,d4_xp_t,d5_xp_t,r1_lh_t,r2_lh_t,r3_lh_t,r4_lh_t,r5_lh_t,d1_lh_t,d2_lh_t,d3_lh_t,d4_lh_t,d5_lh_t,r1_dn_t,r2_dn_t,r3_dn_t,r4_dn_t,r5_dn_t,d1_dn_t,d2_dn_t,d3_dn_t,d4_dn_t,d5_dn_t
0,a400b8f29dece5f4d266f49f1ae2e98a,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.0,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.00,0,0,0,0,2037,3948,-1911,0,1,-1,1,0,1,9,13,-4,2,False,False,False,False,False,True,True,False,False,False,npc_dota_hero_nevermore,npc_dota_hero_brewmaster,npc_dota_hero_pudge,npc_dota_hero_huskar,npc_dota_hero_lycan,npc_dota_hero_phantom_lancer,npc_dota_hero_windrunner,npc_dota_hero_night_stalker,npc_dota_hero_ogre_magi,npc_dota_hero_tinker,"{'npc_dota_creep_goodguys_melee': 92, 'npc_dot...","{'npc_dota_creep_goodguys_ranged': 113, 'npc_d...","{'npc_dota_hero_ogre_magi': 16, 'npc_dota_hero...","{'npc_dota_creep_badguys_melee': 497, 'npc_dot...","{'npc_dota_neutral_satyr_soulstealer': 1286, '...","{'npc_dota_creep_badguys_melee': 695, 'npc_dot...","{'npc_dota_hero_huskar': 402, 'npc_dota_creep_...","{'npc_dota_hero_huskar': 635, 'npc_dota_creep_...",{'npc_dota_hero_pudge': 868},"{'npc_dota_hero_nevermore': 704, 'npc_dota_cre...","[1, 91, 356]","[1, 91, 262]","[1, 91, 182]","[1, 169, 260]","[1, 91, 281]","[1, 331, 738]","[1, 251, 561]","[1, 251, 342]","[1, 251, 342]","[1, 425, 680]","[0, 107, 387]","[0, 38, 318]","[0, 0, 73]","[0, 202, 301]","[0, 38, 238]","[0, 85, 431]","[0, 58, 445]","[0, 41, 229]","[0, 85, 329]","[0, 240, 616]","[0, 0, 4]","[0, 0, 2]","[0, 0, 0]","[0, 2, 2]","[0, 0, 5]","[0, 2, 9]","[0, 0, 5]","[0, 0, 0]","[0, 0, 0]","[0, 4, 8]","[0, 0, 0]","[0, 0, 2]","[0, 0, 0]","[0, 1, 1]","[0, 0, 0]","[0, 4, 12]","[0, 1, 4]","[0, 0, 1]","[0, 0, 0]","[0, 0, 0]"
1,b9c57c450ce74a2af79c9ce96fac144d,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.5,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.00,0,0,0,0,18172,13144,5028,16,3,13,4,16,-12,37,30,7,39,False,False,False,False,False,False,False,False,False,False,npc_dota_hero_razor,npc_dota_hero_centaur,npc_dota_hero_shadow_shaman,npc_dota_hero_weaver,npc_dota_hero_naga_siren,npc_dota_hero_enchantress,npc_dota_hero_pudge,npc_dota_hero_antimage,npc_dota_hero_clinkz,npc_dota_hero_visage,"{'npc_dota_hero_pudge': 2298, 'npc_dota_hero_c...","{'npc_dota_creep_goodguys_ranged': 194, 'npc_d...","{'npc_dota_hero_clinkz': 122, 'npc_dota_hero_p...","{'npc_dota_creep_goodguys_ranged': 622, 'npc_d...","{'npc_dota_hero_clinkz': 1021, 'npc_dota_hero_...","{'npc_dota_hero_centaur': 2252, 'npc_dota_neut...","{'npc_dota_hero_shadow_shaman': 890, 'npc_dota...","{'npc_dota_hero_centaur': 1617, 'npc_dota_cree...","{'npc_dota_hero_shadow_shaman': 258, 'npc_dota...","{'npc_dota_creep_goodguys_melee': 903, 'npc_do...","[41, 819, 1196, 1467, 1839, 2356, 2812, 3444, ...","[41, 211, 340, 589, 762, 1209, 1579, 1803, 240...","[41, 211, 302, 393, 530, 621, 712, 877, 968, 1...","[41, 292, 750, 922, 1644, 1875, 2042, 2623, 28...","[41, 541, 632, 723, 814, 1100, 1406, 1769, 186...","[1, 131, 295, 458, 592, 814, 1002, 1194, 1460,...","[1, 426, 617, 735, 908, 1095, 1383, 1473, 1564...","[1, 225, 396, 742, 1223, 1707, 1798, 2077, 231...","[1, 182, 315, 543, 766, 1135, 1226, 1500, 1632...","[1, 131, 379, 647, 738, 881, 972, 1062, 1153, ...","[0, 166, 395, 702, 1038, 1497, 1759, 2387, 282...","[0, 57, 452, 1022, 1103, 1641, 1991, 2388, 306...","[0, 19, 122, 184, 311, 467, 827, 1065, 1121, 1...","[0, 188, 968, 1291, 2209, 2480, 2695, 3298, 34...","[0, 166, 395, 631, 687, 1023, 1582, 1855, 2009...","[0, 0, 183, 384, 528, 1025, 1025, 1391, 1973, ...","[0, 30, 254, 444, 615, 843, 1209, 1329, 1500, ...","[0, 197, 532, 698, 1368, 1719, 1902, 2000, 224...","[0, 87, 458, 631, 997, 1189, 1317, 1656, 1884,...","[0, 188, 510, 945, 1136, 1136, 1136, 1136, 113...","[0, 2, 8, 12, 18, 22, 25, 33, 39, 45, 52]","[0, 0, 1, 5, 8, 9, 10, 13, 15, 17, 19]","[0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]","[0, 2, 4, 6, 9, 12, 14, 21, 25, 28, 33]","[0, 0, 0, 0, 0, 5, 8, 8, 8, 8, 13]","[0, 0, 4, 8, 11, 11, 12, 14, 18, 22, 22]","[0, 0, 2, 4, 6, 8, 12, 12, 12, 12, 12]","[0, 2, 4, 7, 15, 15, 15, 18, 25, 27, 27]","[0, 0, 1, 1, 4, 6, 6, 9, 10, 11, 16]","[0, 0, 4, 8, 8, 8, 8, 8, 8, 8, 8]","[0, 0, 1, 5, 5, 7, 7, 7, 7, 7, 7]","[0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3]","[0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2]","[0, 1, 2, 2, 4, 6, 7, 8, 9, 11, 12]","[0, 0, 0, 1, 1, 2, 3, 3, 3, 3, 4]","[0, 0, 0, 0, 0, 1, 1, 1, 2, 3, 3]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 1, 3, 7, 7, 7, 7, 7, 7, 7]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3]","[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]"
2,6db558535151ea18ca70a6892197db41,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.0,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.00,0,0,0,0,880,480,400,0,0,0,0,0,0,5,5,0,0,False,False,False,False,False,False,False,False,False,False,npc_dota_hero_skywrath_mage,npc_dota_hero_rattletrap,npc_dota_hero_phantom_assassin,npc_dota_hero_dragon_knight,npc_dota_hero_furion,npc_dota_hero_sven,npc_dota_hero_spectre,npc_dota_hero_viper,npc_dota_hero_venomancer,npc_dota_hero_storm_spirit,{},{},{'npc_dota_hero_spectre': 70},{},{},{},{'npc_dota_hero_phantom_assassin': 68},{},{},{},[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0]
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.0,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.00,0,0,2,0,13348,11301,2047,6,1,5,2,7,-5,32,28,4,16,False,False,False,False,False,False,False,False,True,False,npc_dota_hero_pudge,npc_dota_hero_bristleback,npc_dota_hero_skywrath_mage,npc_dota_hero_lion,npc_dota_hero_faceless_void,npc_dota_hero_sven,npc_dota_hero_shredder,npc_dota_hero_juggernaut,npc_dota_hero_doom_bringer,npc_dota_hero_rubick,"{'npc_dota_hero_pudge': 918, 'npc_dota_hero_do...","{'npc_dota_creep_badguys_melee': 6665, 'npc_do...","{'npc_dota_hero_shredder': 4304, 'npc_dota_cre...","{'npc_dota_hero_doom_bringer': 710, 'npc_dota_...","{'npc_dota_creep_badguys_melee': 4949, 'npc_do...","{'npc_dota_neutral_satyr_trickster': 2710, 'np...","{'npc_dota_creep_goodguys_melee': 5060, 'npc_d...","{'npc_dota_creep_goodguys_melee': 6142, 'npc_d...","{'npc_dota_creep_goodguys_melee': 960, 'npc_do...","{'npc_dota_hero_bristleback': 1577, 'npc_dota_...","[81, 171, 262, 524, 615, 820, 911, 1105, 1196,...","[81, 171, 499, 658, 924, 1285, 1416, 1968, 213...","[81, 274, 540, 1239, 1455, 2132, 2398, 2706, 3...","[81, 171, 262, 464, 555, 885, 976, 1092, 1272,...","[81, 288, 681, 992, 1374, 1620, 2029, 2418, 26...","[104, 194, 424, 658, 828, 1258, 1491, 1917, 22...","[104, 315, 579, 710, 1014, 1148, 1379, 1865, 2...","[104, 272, 547, 892, 1321, 1602, 1989, 2331, 2...","[104, 262, 427, 625, 821, 1031, 1180, 1539, 17...","[104, 194, 285, 376, 561, 728, 819, 910, 1001,...","[0, 77, 206, 352, 422, 611, 701, 970, 1177, 1311]","[0, 114, 720, 1153, 1539, 2050, 2121, 2548, 28...","[0, 240, 776, 1231, 1616, 2282, 2750, 3318, 36...","[0, 42, 233, 372, 504, 698, 768, 984, 1095, 1194]","[0, 77, 410, 849, 1209, 1460, 1805, 2204, 2817...","[0, 0, 336, 506, 634, 1056, 1283, 1533, 1960, ...","[0, 240, 719, 1028, 1596, 1933, 2275, 2772, 32...","[0, 118, 354, 708, 1096, 1377, 1699, 2010, 219...","[0, 57, 172, 266, 499, 822, 908, 1250, 1504, 1...","[0, 118, 354, 463, 761, 990, 1312, 1494, 1676,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 5, 7, 10, 16, 17, 24, 26, 30]","[0, 2, 6, 11, 14, 20, 24, 27, 33, 37]","[0, 0, 0, 2, 2, 2, 2, 2, 2, 2]","[0, 3, 10, 15, 22, 25, 32, 39, 42, 51]","[0, 0, 7, 10, 12, 24, 29, 36, 47, 56]","[0, 3, 7, 8, 13, 14, 17, 20, 23, 23]","[0, 2, 6, 12, 19, 23, 30, 34, 39, 40]","[0, 1, 3, 4, 6, 8, 9, 12, 15, 15]","[0, 0, 0, 0, 2, 2, 2, 2, 2, 2]","[0, 0, 1, 1, 1, 1, 1, 1, 1, 1]","[0, 0, 0, 0, 1, 2, 2, 2, 2, 2]","[0, 0, 2, 2, 2, 4, 7, 7, 8, 8]","[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]","[0, 2, 9, 12, 14, 15, 17, 21, 23, 28]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 2, 2, 4, 4, 4, 4, 5, 5]","[0, 0, 0, 0, 0, 1, 2, 3, 4, 4]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 1, 1, 1, 1]"
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.5,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.25,0,0,0,0,8079,9177,-1098,2,4,-2,4,2,2,25,26,-1,12,False,False,False,False,False,False,False,False,False,False,npc_dota_hero_skeleton_king,npc_dota_hero_doom_bringer,npc_dota_hero_shadow_shaman,npc_dota_hero_legion_commander,npc_dota_hero_batrider,npc_dota_hero_kunkka,npc_dota_hero_zuus,npc_dota_hero_sniper,npc_dota_hero_gyrocopter,npc_dota_hero_antimage,"{'npc_dota_hero_antimage': 418, 'npc_dota_cree...","{'npc_dota_hero_antimage': 766, 'npc_dota_cree...","{'npc_dota_hero_gyrocopter': 168, 'npc_dota_cr...","{'npc_dota_hero_antimage': 248, 'npc_dota_cree...","{'npc_dota_creep_badguys_melee': 4301, 'npc_do...","{'npc_dota_hero_legion_commander': 134, 'npc_d...","{'npc_dota_creep_goodguys_melee': 4583, 'npc_d...","{'npc_dota_hero_shadow_shaman': 1521, 'npc_dot...","{'npc_dota_hero_shadow_shaman': 447, 'npc_dota...","{'npc_dota_hero_doom_bringer': 672, 'npc_dota_...","[21, 191, 282, 481, 610, 820, 988, 1355]","[283, 555, 782, 1030, 1186, 1372, 1488, 1645]","[1, 211, 345, 573, 664, 854, 1024, 1115]","[27, 238, 504, 595, 781, 1149, 1374, 1675]","[1, 171, 356, 515, 700, 944, 1174, 1438]","[1, 210, 339, 468, 823, 1030, 1202, 1293]","[1, 214, 456, 667, 758, 890, 1180, 1326]","[86, 431, 686, 957, 1183, 1457, 1670, 2173]","[165, 389, 556, 981, 1115, 1248, 1431, 1648]","[1, 312, 542, 905, 1217, 1442, 1756, 2077]","[20, 66, 247, 365, 519, 789, 887, 1295]","[20, 80, 278, 524, 678, 1062, 1229, 1511]","[0, 297, 777, 1214, 1694, 2048, 2856, 2856]","[20, 148, 384, 384, 684, 1042, 1343, 1823]","[0, 147, 383, 623, 797, 915, 1090, 1090]","[0, 133, 384, 749, 1053, 1205, 1499, 1624]","[0, 118, 305, 636, 844, 1195, 1439, 1617]","[30, 327, 807, 1301, 1838, 2387, 2684, 3304]","[30, 148, 266, 569, 777, 957, 1236, 1623]","[0, 133, 384, 608, 912, 1235, 1529, 1753]","[0, 0, 0, 1, 2, 3, 5, 9]","[0, 2, 5, 8, 9, 11, 11, 12]","[0, 1, 2, 5, 5, 7, 9, 9]","[0, 1, 5, 5, 7, 13, 16, 21]","[0, 0, 2, 2, 4, 4, 7, 7]","[0, 1, 2, 3, 5, 6, 8, 8]","[0, 1, 4, 7, 7, 8, 9, 10]","[0, 4, 8, 12, 15, 19, 22, 31]","[0, 1, 3, 4, 5, 6, 9, 12]","[0, 3, 6, 12, 16, 19, 23, 28]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 1, 1, 1, 1]","[0, 0, 0, 1, 1, 1, 1, 2]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 2, 4, 5, 6, 6, 8, 8]"

In [ ]:
def match_timeseries_widget_random(df, idx=0, time_step=60):
    metrics = {
        "gold_t": "Gold networth",
        "xp_t": "XP",
        "lh_t": "Last hits",
        "dn_t": "Denies",
    }

    players = [f"r{i}" for i in range(1, 6)] + [f"d{i}" for i in range(1, 6)]

    out = widgets.Output()

    dropdown = widgets.Dropdown(
        options=[(label, key) for key, label in metrics.items()],
        value="gold_t",
        description="Metric",
        layout=widgets.Layout(width="260px")
    )

    btn_random = widgets.Button(
        description="Random match",
        button_style="",
        icon="random",
        layout=widgets.Layout(width="150px")
    )

    idx_label = widgets.HTML()

    state = {"idx": idx}

    def coerce_list(val):
        if val is None:
            return []
        if isinstance(val, (list, tuple)):
            return list(val)
        if isinstance(val, str):
            s = val.strip()
            if s.startswith("[") and s.endswith("]"):
                try:
                    parsed = ast.literal_eval(s)
                    if isinstance(parsed, list):
                        return parsed
                except Exception:
                    return []
        return []

    def get_series(row, p, metric):
        col = f"{p}_{metric}"
        if col not in row.index:
            return []
        return coerce_list(row[col])

    def update_label(row_idx):
        text = f"<b>idx:</b> {row_idx}"
        idx_label.value = text

    def plot():
        row_idx = state["idx"]
        metric = dropdown.value
        row = df.iloc[row_idx]

        with out:
            clear_output(wait=True)

            plt.figure(figsize=(10, 6))

            plotted_any = False
            max_len = 0

            for p in players:
                values = get_series(row, p, metric)
                if not values:
                    continue

                max_len = max(max_len, len(values))
                times = [i * time_step for i in range(len(values))]
                color = "green" if p.startswith("r") else "red"

                plt.plot(times, values, color=color, alpha=0.9)
                plotted_any = True

            if not plotted_any:
                print(
                    f"Для строки idx={row_idx} нет данных {metric}. "
                    f"Проверь, что колонки r1_{metric} ... d5_{metric} прикреплены "
                    f"и что в этой строке они не пустые"
                )
                return

            plt.xlabel("Time, sec")
            plt.ylabel(metrics[metric])
            plt.title(f"{metrics[metric]} for all players, idx = {row_idx}")

            if max_len > 1:
                plt.xlim(0, (max_len - 1) * time_step)

            legend_handles = [
                Line2D([0], [0], color="green", lw=2, label="Radiant"),
                Line2D([0], [0], color="red", lw=2, label="Dire"),
            ]
            plt.legend(handles=legend_handles, loc="upper left")

            plt.tight_layout()
            plt.show()

    def on_metric_change(change):
        if change.get("name") == "value":
            update_label(state["idx"])
            plot()

    def on_random_click(_):
        state["idx"] = random.randrange(0, len(df))
        update_label(state["idx"])
        plot()

    dropdown.observe(on_metric_change)
    btn_random.on_click(on_random_click)

    controls = widgets.HBox([dropdown, btn_random, idx_label])

    display(controls)
    display(out)

    update_label(state["idx"])
    plot()

In [25]:
match_timeseries_widget_random(raw_features, idx=longest_match_id)

HBox(children=(Dropdown(description='Metric', layout=Layout(width='260px'), options=(('Gold networth', 'gold_t…

Output()

In [26]:
raw_features.iloc[0]

match_id_hash     a400b8f29dece5f4d266f49f1ae2e98a
game_time                                      155
game_mode                                       22
lobby_type                                       7
objectives_len                                   1
                                ...
d1_dn_t                                 [0, 4, 12]
d2_dn_t                                  [0, 1, 4]
d3_dn_t                                  [0, 0, 1]
d4_dn_t                                  [0, 0, 0]
d5_dn_t                                  [0, 0, 0]
Name: 0, Length: 329, dtype: object

In [27]:
X = df_feats.drop('match_id_hash', axis=1)
y = raw_targets["radiant_win"]

In [28]:
X

,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed,radiant_total_gold,dire_total_gold,radiant_gold_advantage,radiant_total_kills,dire_total_kills,radiant_kills_advantage,radiant_total_deaths,dire_total_deaths,radiant_deaths_advantage,radiant_total_level,dire_total_level,radiant_level_advantage,total_kills_deaths
0,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00000,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00000,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00000,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.000,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.0000,0,0,0,0,2037,3948,-1911,0,1,-1,1,0,1,9,13,-4,2
1,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25000,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25000,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50000,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.500,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.0000,0,0,0,0,18172,13144,5028,16,3,13,4,16,-12,37,30,7,39
2,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00000,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00000,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00000,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.000,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.0000,0,0,0,0,880,480,400,0,0,0,0,0,0,5,5,0,0
3,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00000,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50000,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50000,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.000,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.0000,0,0,2,0,13348,11301,2047,6,1,5,2,7,-5,32,28,4,16
4,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25000,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25000,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25000,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.500,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.2500,0,0,0,0,8079,9177,-1098,2,4,-2,4,2,2,25,26,-1,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39670,1783,22,0,8,23,3,1,9,9,0,6283,13,7847,0,1380,710.93820,13,144,100,90.944490,0,0,8,0,0.500000,0,0,10,19,49,2,7,8,7,8838,83,10815,1760,1760,530.93800,15,74,76,41.750020,0,0,2,0,0.500000,0,0,1,0,7,4,7,8,4,8530,66,9270,0,1580,1162.93860,14,140,98,71.732760,0,0,6,0,0.600000,0,0,0,0,74,8,3,2,27,14815,161,19257,0,1875,1581.93900,21,144,100,24.060377,0,0,4,0,0.500000,2,0,2,4,63,4,6,5,14,9864,91,10367,1000,1000,554.93805,15,140,138,0.000000,0,0,14,1,0.450000,1,0,0,0,14,6,7,11,6,9371,67,11911,0,2515,1275.93870,16,134,98,39.090730,0,0,6,0,0.53125,0,0,1,2,36,8,1,11,2,13071,143,16893,1560,1560,1356.93880,19,124,78,4.432127,0,0,7,0,0.59375,1,0,0,0,32,7,4,10,7,7937,25,10579,1120,1120,494.93796,15,124,164,0.000000,0,0,9,0,0.53125,0,0,3,2,8,10,5,6,21,15226,183,16164,1667,1680,602.93805,19,126,76,0.799805,0,0,9,0,0.500,2,0,0,0,5,1,4,17,0,6033,20,9742,1040,1040,830.93830,14,130,76,26.493834,6,2,3,0,0.5625,0,0,7,2,48330,51638,-3308,19,32,-13,32,21,11,78,83,-5,104
39671,377,22,7,1,0,14,0,2,1,1,809,2,1102,0,900,290.93777,4,84,156,1.266357,0,0,0,0,0.500000,0,0,0,0,80,1,1,0,6,1692,21,1323,627,680,278.93777,4,174,100,0.000000,0,0,0,0,0.500000,0,0,0,0,12,0,0,1,3,1671,22,2345,509,920,506.93800,6,112,114,0.000000,0,0,0,0,0.500000,0,0,0,0,3,1,0,1,2,1443,2,1150,761,840,458.93793,4,176,94,0.000000,3,1,6,1,1.000000,0,0,1,1,63,0,0,0,0,1173,9,1505,523,660,350.93784,4,86,156,0.000000,0,0,2,0,0.000000,0,0,0,1,88,0,1,1,2,1039,7,1097,700,700,374.93787,4,174,110,10.097570,0,0,1,0,0.50000,0,0,0,0,47,1,0,0,0,967,3,1154,573,800,350.93784,4,178,108,0.000000,0,0,0,0,0.50000,0,0,0,0,11,1,1,0,8,2184,29,2964,820,820,470.93796,7,120,122,0.000000,0,0,2,0,0.50000,0,0,0,0,27,0,0,0,6,1000,2,838,509,740,422.93790,3,84,156,6.298479,3,1,4,0,0.000,0,0,1,1,73,0,0,0,10,3203,41,2510,95,920,494.93796,6,90,158,0.000000,0,0,1,0,0.0000,0,0,0,0,6788,8393,-1605,2,2,0,3,2,1,22,24,-2,9
39672,643,22,7,1,23,63,1,4,0,2,1747,4,2677,369,780,422.93790,6,80,138,0.000000,0,0,4,0,0.250000,0,0,0,0,27,0,3,2,2,1331,2,1737,780,780,470.93796,5,164,96,26.693481,0,0,3,0,0.500000,0,0,3,0,110,0,10,1,0,1055,0,379,345,680,326.93780,2,106,110,0.000000,0,0,0,0,0.250000,0,0,0,0,10,3,2,0,15,4191,44,3760,440,640,374.93787,8,176,84,0.000000,0,0,3,0,0.750000,0,0,0,0,49,0,1,0,7,3028,44,3661,0,1360,410.93790,8,88,144,5.065430,0,0,0,0,0.000000,0,0,1,1,120,3,0,1,3,3148,27,2941,679,820,398.93787,7,174,90,-0.983398,0,0,2,0,0.20000,0,0,0,0,40,0,3,4,0,2208,10,1847,798,820,530.93800,5,174,90,0.000000,0,0,5,0,0.20000,0,0,0,0,30,3,1,2,4,2266,3,2620,465,760,554.93805,6,80,154,11.063930,3,1,6,0,0.25000,0,0,3,3,44,3,0,3,21,4453,48,4659,968,980,410.93790,9,82,154,0.000000,0,0,2,0,0.300,0,0,0,0,11,9,0,1,14,5431,51,5420,773,1000,686.93820,10,120,124,2.532715,0,0,3,1,0.5000,0,0,1,0,11352,17506,-6154,4,18,-14,20,4,16,29,37,-8,46
39673,2405,22,7,12,4,22,3,8,14,7,14375,168,19847,0,1995,1843.93920,21,134,154,8.850186,0,0,15,0,0.404762,1,0,1,0,32,9,12,10,2,12448,42,18449,1343,1500,794.93823,21,130,150,0.000000,0,0,18,0,0.428571,0,0,1,1,81,8,3,9,7,21451,305,27114,5200,5200,854.93830,25,122,124,23.931118,0,0,8,0,0.404762,2,0,0,0,91,1,14,13,6,8134,11,13382,1280,1280,698.93820,17,94,132,0.000000,0,0,11,0,0.333333,0,0,14,2,23,21,3,7,15,32403,413,26950,1550,2760,902.93835,25,116,134,35.064312,0,0,10,0,0.666667,3,1,0,0,26,9,11,15,1,11499,20,18654,0,1820,1484.93900,21,120,138,132.343580,0,0,5,1,0.60000,0,0,13,4,53,6,12,17,1,19420,276,20634,0,1960,1574.93900,22,76,146,0.000000,0,0,1,0,0.57500,1,0,0,2,10,10,6,2,22,17934,236,22866,813,1500,722.93820,23,126,158,5.569586,0,0,10,0,0.30000,0,0,2,0,42,5,6,18,1,14477,136,19556,1657,2260,794.93823,21,118,164,40.033060,1,1,9,0,0.575,1,0,0,1,11,9,7,16,26,18231,181,25354,1840,2525,1548.93900,24,98,158,17.583984,3,1,4,0,0.6250,0,0,0,0,88811,81561,7250,42,39,3,40,42,-2,109,111,-2,163
39674,1775,22,0,10,13,32,3,4,15,0,8847,20,11151,0,1100,602.93805,15,118,120,0.000000,0,0,16,0,0.600000,0,0,5,6,69,5,7,11,5,11458,102,10823,2267,2280,698.93820,15,174,112,32.059246,0,0,7,0,0.533333,1,0,0,0,76,10,0,5,29,16708,201,19598,2750,2750,1756.93920,21,178,110,46.655327,0,0,3,0,0.500000,2,0,0,0,10,2,5,7,2,13150,194,16362,1061,1200,614.93810,19,106,114,2.399467,1,1,6,0,0.300000,1,0,0,0,68,10,4,10,0,9666,48,13504,1440,1440,1380.93880,17,180,108,14.772326,2,1,2,0,0.666667,0,0,8,4,49,1,7,4,6,10347,105,11612,2180,2180,578.93805,16,178,166,22.585493,0,0,8,0,0.25000,2,0,0,0,110,4,10,5,4,9140,49,9222,0,1560,758.93823,14,122,126,4.432282,2,1,13,0,0.45000,0,0,9,8,62,4,4,10,3,8229,10,10008,528,1120,888.93835,14,140,134,0.928828,0,0,4,0,0.70000,0,0,1,0,106,8,3,6,15,14982,183,15506,1832,1840,1226.93870,19,78,166,36.424126,2,1,12,1,0.700,1,0,1,0,95,3,6,8,19,14096,225,15424,2031,2060,470.93796,19,104,162,8.331238,0,0,1,0,0.5500,1,0,0,0,59829,56794,3035,30,20,10,20,30,-10,87,82,5,100

In [29]:
y.head()

0    False
1     True
2     True
3     True
4    False
Name: radiant_win, dtype: bool

In [30]:
path = "DOTA 2//train_matches.jsonl"

with open(path, "r", encoding="utf-8") as f:
    for line in itertools.islice(f, 5):  # первые 5 строк
        print(line.strip())

{"game_time": 155, "match_id_hash": "a400b8f29dece5f4d266f49f1ae2e98a", "teamfights": [], "objectives": [{"time": 124.203, "type": "CHAT_MESSAGE_FIRSTBLOOD", "slot": 8, "key": 2, "player_slot": 131}], "chat": [{"player_slot": 0, "time": -13.63, "text": "???"}, {"player_slot": 0, "time": -10.964, "text": "? ???? ??????"}, {"player_slot": 0, "time": -7.965, "text": "???????? ????("}, {"player_slot": 4, "time": 43.756, "text": "???"}, {"player_slot": 2, "time": 44.422, "text": "??? ??????"}, {"player_slot": 4, "time": 45.289, "text": "*[*[*["}, {"player_slot": 2, "time": 46.622, "text": "????"}, {"player_slot": 4, "time": 47.355, "text": "??? ??????"}, {"player_slot": 4, "time": 48.688, "text": "????"}, {"player_slot": 2, "time": 52.021, "text": "???????? ??? ??????"}, {"player_slot": 4, "time": 73.349, "text": "????? ??? ?????"}], "game_mode": 22, "lobby_type": 7, "players": [{"player_slot": 0, "hero_id": 11, "hero_name": "npc_dota_hero_nevermore", "account_id_hash": "86bf86c5488742478688149155258ea8", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 1, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 94.977, "max": true, "inflictor": "nevermore_shadowraze2", "unit": "npc_dota_hero_nevermore", "key": "npc_dota_hero_tinker", "value": 136, "slot": 0, "player_slot": 0}, "times": [0, 60, 120], "gold_t": [1, 91, 356], "lh_t": [0, 0, 4], "dn_t": [0, 0, 0], "xp_t": [0, 107, 387], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "wraith_band"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": -84.215, "key": "tango"}, {"time": 99.409, "key": "flask"}, {"time": 100.909, "key": "clarity"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 134.067, "key": 0}], "obs": {}, "sen": {}, "actions": {"1": 551, "2": 8, "4": 43, "6": 1, "7": 2, "8": 6, "10": 1, "11": 2, "15": 2, "16": 8, "17": 2, "19": 6, "21": 30, "33": 30}, "pings": {"0": 6}, "purchase": {"wraith_band": 1, "enchanted_mango": 1, "tpscroll": 1, "tango": 1, "flask": 1, "clarity": 1}, "gold_reasons": {"0": 600, "13": 308}, "xp_reasons": {"2": 533}, "killed": {"npc_dota_creep_badguys_melee": 250, "npc_dota_creep_badguys_ranged": 203}, "item_uses": {"tango": 1, "flask": 1}, "ability_uses": {"nevermore_shadowraze3": 1, "nevermore_shadowraze1": 1, "nevermore_shadowraze2": 1}, "hero_hits": {"null": 3, "nevermore_shadowraze3": 1, "nevermore_shadowraze1": 1, "nevermore_shadowraze2": 1}, "damage": {"npc_dota_creep_goodguys_melee": 92, "npc_dota_creep_badguys_melee": 478, "npc_dota_hero_tinker": 459, "npc_dota_creep_badguys_ranged": 203, "npc_dota_creep_goodguys_ranged": 55}, "damage_taken": {"npc_dota_hero_tinker": 704, "npc_dota_creep_badguys_melee": 231, "npc_dota_creep_badguys_ranged": 38}, "damage_inflictor": {"null": 159, "nevermore_shadowraze3": 64, "nevermore_shadowraze1": 100, "nevermore_shadowraze2": 136}, "runes": {"0": 1}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {"tinker_laser": 410, "null": 294}, "randomed": false, "pred_vict": false, "gold": 543, "lh": 7, "xp": 533, "x": 116, "y": 122, "hero_inventory": [{"id": "item_tango", "num_charges": 2, "cooldown": 0}, {"id": "item_wraith_band", "cooldown": 0}, {"id": "item_enchanted_mango", "cooldown": 0}, {"id": "item_clarity", "num_charges": 1, "cooldown": 0}, {"id": "item_tpscroll", "num_charges": 1, "cooldown": 0}], "hero_stash": [], "health": 358, "max_health": 600, "max_mana": 350.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 0, "nearby_creep_death_count": 19}, {"player_slot": 1, "hero_id": 78, "hero_name": "npc_dota_hero_brewmaster", "account_id_hash": "67d6d5d0a77e585a11319af7bdd5caed", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 0, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"value": 0}, "times": [0, 60, 120], "gold_t": [1, 91, 262], "lh_t": [0, 0, 2], "dn_t": [0, 0, 2], "xp_t": [0, 38, 318], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tpscroll"}, {"time": -66.817, "key": "stout_shield"}, {"time": -66.417, "key": "enchanted_mango"}, {"time": -65.851, "key": "tango"}, {"time": -65.184, "key": "tango"}, {"time": -64.951, "key": "flask"}], "kills_log": [], "buyback_log": [], "runes_log": [], "obs": {}, "sen": {}, "actions": {"1": 713, "4": 196, "5": 1, "6": 3, "7": 18, "8": 2, "10": 52, "11": 2, "12": 1, "16": 5, "19": 1, "33": 52}, "pings": {}, "purchase": {"tpscroll": 1, "stout_shield": 1, "enchanted_mango": 1, "tango": 2, "flask": 1}, "gold_reasons": {"0": 600, "13": 164}, "xp_reasons": {"2": 478}, "killed": {"npc_dota_creep_goodguys_ranged": 113, "npc_dota_creep_badguys_melee": 281, "npc_dota_creep_goodguys_melee": 53}, "item_uses": {"tpscroll": 1, "enchanted_mango": 1, "flask": 1, "tango": 6}, "ability_uses": {"brewmaster_drunken_haze": 2}, "hero_hits": {}, "damage": {"npc_dota_creep_goodguys_ranged": 113, "npc_dota_creep_badguys_melee": 1002, "npc_dota_creep_goodguys_melee": 212}, "damage_taken": {"npc_dota_creep_badguys_melee": 148, "npc_dota_hero_tinker": 116}, "damage_inflictor": {}, "runes": {}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {"npc_dota_hero_brewmaster": 1}, "damage_inflictor_received": {"null": 116}, "randomed": false, "pred_vict": false, "gold": 399, "lh": 4, "xp": 478, "x": 124, "y": 126, "hero_inventory": [], "hero_stash": [], "health": 636, "max_health": 720, "max_mana": 254.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 3, "nearby_creep_death_count": 19}, {"player_slot": 2, "hero_id": 14, "hero_name": "npc_dota_hero_pudge", "account_id_hash": "d0cb6c812472517b999025ea19d17b5c", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 1, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 123.437, "max": true, "inflictor": "pudge_rot", "unit": "npc_dota_hero_pudge", "key": "npc_dota_hero_ogre_magi", "value": 4, "slot": 2, "player_slot": 2}, "times": [0, 60, 120], "gold_t": [1, 91, 182], "lh_t": [0, 0, 0], "dn_t": [0, 0, 0], "xp_t": [0, 0, 73], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tpscroll"}, {"time": -70.849, "key": "courier"}, {"time": -69.116, "key": "tango"}, {"time": -65.117, "key": "magic_stick"}, {"time": -19.662, "key": "wind_lace"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 139.333, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 145, "5": 1, "7": 3, "8": 1, "9": 1, "10": 10, "11": 1, "15": 1, "16": 4, "19": 3, "33": 10}, "pings": {"0": 1}, "purchase": {"tpscroll": 1, "courier": 1, "tango": 1, "magic_stick": 1, "wind_lace": 1}, "gold_reasons": {"0": 669, "1": -67}, "xp_reasons": {"2": 130}, "killed": {}, "item_uses": {"courier": 1, "tango": 3, "tpscroll": 1}, "ability_uses": {"pudge_rot": 1}, "hero_hits": {"pudge_rot": 8}, "damage": {"npc_dota_hero_ogre_magi": 16, "npc_dota_hero_pudge": 16}, "damage_taken": {"npc_dota_hero_ogre_magi": 868, "npc_dota_hero_phantom_lancer": 224, "npc_dota_hero_pudge": 16}, "damage_inflictor": {"pudge_rot": 16}, "runes": {"5": 1}, "killed_by": {"npc_dota_hero_ogre_magi": 1}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 300, "1": 3, "2": 7}, "healing": {}, "damage_inflictor_received": {"null": 731, "orb_of_venom": 54, "ogre_magi_ignite": 190, "phantom_lancer_spirit_lance": 76, "ogre_magi_fireblast": 41}, "randomed": false, "pred_vict": false, "gold": 304, "lh": 0, "xp": 130, "x": 70, "y": 156, "hero_inventory": [{"id": "item_magic_stick", "num_charges": 4, "cooldown": 0}, {"id": "item_wind_lace", "cooldown": 0}], "hero_stash": [], "health": 700, "max_health": 700, "max_mana": 242.938, "level": 1, "kills": 0, "deaths": 1, "assists": 0, "denies": 0, "nearby_creep_death_count": 6}, {"player_slot": 3, "hero_id": 59, "hero_name": "npc_dota_hero_huskar", "account_id_hash": "83975f1afb5f5e97dc7266402f997dc3", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 0, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 83.48, "max": true, "inflictor": null, "unit": "npc_dota_hero_huskar", "key": "npc_dota_hero_night_stalker", "value": 42, "slot": 3, "player_slot": 3}, "times": [0, 60, 120], "gold_t": [1, 169, 260], "lh_t": [0, 2, 2], "dn_t": [0, 1, 1], "xp_t": [0, 202, 301], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tango"}, {"time": -89.783, "key": "wind_lace"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "tpscroll"}, {"time": 52.221, "key": "magic_wand"}, {"time": 52.221, "key": "magic_stick"}, {"time": 117.438, "key": "flask"}], "kills_log": [], "buyback_log": [], "runes_log": [], "obs": {}, "sen": {}, "actions": {"1": 1053, "2": 8, "3": 3, "4": 84, "6": 3, "7": 3, "8": 1, "10": 41, "11": 2, "16": 7, "19": 1, "20": 2, "33": 41}, "pings": {}, "purchase": {"tango": 1, "wind_lace": 1, "enchanted_mango": 1, "branches": 2, "tpscroll": 1, "magic_wand": 1, "magic_stick": 1, "flask": 1}, "gold_reasons": {"0": 600, "13": 154}, "xp_reasons": {"2": 506}, "killed": {"npc_dota_creep_badguys_melee": 185, "npc_dota_creep_goodguys_melee": 46}, "item_uses": {"tango": 3}, "ability_uses": {}, "hero_hits": {"huskar_burning_spear": 25, "null": 6}, "damage": {"npc_dota_creep_badguys_melee": 497, "npc_dota_hero_huskar": 90, "npc_dota_hero_windrunner": 64, "npc_dota_creep_goodguys_melee": 46, "npc_dota_hero_night_stalker": 303}, "damage_taken": {"npc_dota_hero_windrunner": 402, "npc_dota_hero_night_stalker": 635, "npc_dota_hero_huskar": 90, "npc_dota_creep_badguys_melee": 65}, "damage_inflictor": {"null": 194, "huskar_burning_spear": 173}, "runes": {}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {"null": 760, "orb_of_venom": 87, "night_stalker_void": 190}, "randomed": false, "pred_vict": false, "gold": 389, "lh": 4, "xp": 506, "x": 170, "y": 86, "hero_inventory": [{"id": "item_wind_lace", "cooldown": 0}, {"id": "item_magic_wand", "num_charges": 2, "cooldown": 0}, {"id": "item_tpscroll", "num_charges": 1, "cooldown": 0}], "hero_stash": [], "health": 399, "max_health": 700, "max_mana": 326.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 1, "nearby_creep_death_count": 14}, {"player_slot": 4, "hero_id": 77, "hero_name": "npc_dota_hero_lycan", "account_id_hash": "7713505172bca930266a2da3524ae04e", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 0, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"value": 0}, "times": [0, 60, 120], "gold_t": [1, 91, 281], "lh_t": [0, 0, 5], "dn_t": [0, 0, 0], "xp_t": [0, 38, 238], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "stout_shield"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "faerie_fire"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": -9.198, "key": "quelling_blade"}], "kills_log": [], "buyback_log": [], "runes_log": [], "obs": {}, "sen": {}, "actions": {"1": 671, "2": 5, "3": 1, "4": 130, "7": 1, "8": 1, "10": 1, "11": 2, "16": 4, "19": 2}, "pings": {}, "purchase": {"stout_shield": 1, "branches": 2, "faerie_fire": 1, "enchanted_mango": 1, "tpscroll": 1, "quelling_blade": 1}, "gold_reasons": {"0": 600, "13": 167}, "xp_reasons": {"2": 344}, "killed": {"npc_dota_neutral_satyr_soulstealer": 174, "npc_dota_neutral_satyr_trickster": 194, "npc_dota_neutral_mud_golem": 209, "npc_dota_neutral_mud_golem_split": 399}, "item_uses": {"quelling_blade": 1}, "ability_uses": {"lycan_howl": 1}, "hero_hits": {}, "damage": {"npc_dota_neutral_satyr_soulstealer": 1286, "npc_dota_neutral_satyr_trickster": 780, "npc_dota_neutral_mud_golem": 1721, "npc_dota_neutral_mud_golem_split": 1206, "npc_dota_neutral_giant_wolf": 97}, "damage_taken": {"npc_dota_neutral_satyr_soulstealer": 227, "npc_dota_neutral_satyr_trickster": 56, "npc_dota_neutral_mud_golem": 343, "npc_dota_neutral_mud_golem_split": 44, "npc_dota_neutral_giant_wolf": 35}, "damage_inflictor": {}, "runes": {}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {}, "randomed": true, "pred_vict": false, "gold": 402, "lh": 10, "xp": 344, "x": 120, "y": 100, "hero_inventory": [{"id": "item_stout_shield", "cooldown": 0}, {"id": "item_quelling_blade", "cooldown": 0}, {"id": "item_branches", "cooldown": 0}, {"id": "item_faerie_fire", "num_charges": 1, "cooldown": 0}, {"id": "item_enchanted_mango", "cooldown": 0}, {"id": "item_branches", "cooldown": 0}], "hero_stash": [], "health": 422, "max_health": 800, "max_mana": 314.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 0, "nearby_creep_death_count": 12}, {"player_slot": 128, "hero_id": 12, "hero_name": "npc_dota_hero_phantom_lancer", "account_id_hash": "c5e8f264da8fbb8b352f5298039c9be8", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 1, "firstblood_claimed": 0, "teamfight_participation": 1, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 118.771, "max": true, "inflictor": "phantom_lancer_spirit_lance", "unit": "npc_dota_hero_phantom_lancer", "key": "npc_dota_hero_pudge", "value": 76, "slot": 5, "player_slot": 128}, "times": [0, 60, 120], "gold_t": [1, 331, 738], "lh_t": [0, 2, 9], "dn_t": [0, 4, 12], "xp_t": [0, 85, 431], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tango"}, {"time": -89.783, "key": "flask"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "stout_shield"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": 23.428, "key": "quelling_blade"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 4.232, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 443, "2": 12, "3": 1, "4": 80, "6": 1, "7": 4, "10": 19, "11": 2, "15": 2, "16": 7, "17": 1, "19": 5, "33": 19}, "pings": {}, "purchase": {"tango": 1, "flask": 1, "branches": 1, "stout_shield": 1, "enchanted_mango": 1, "tpscroll": 1, "quelling_blade": 1}, "gold_reasons": {"0": 760, "12": 34, "13": 553}, "xp_reasons": {"1": 30, "2": 750}, "killed": {"npc_dota_creep_badguys_melee": 507, "npc_dota_creep_goodguys_melee": 648, "npc_dota_creep_badguys_ranged": 239, "npc_dota_creep_goodguys_ranged": 364}, "item_uses": {"tango": 1, "quelling_blade": 3}, "ability_uses": {"phantom_lancer_spirit_lance": 1}, "hero_hits": {"phantom_lancer_spirit_lance": 1, "null": 4}, "damage": {"npc_dota_creep_badguys_melee": 695, "npc_dota_creep_goodguys_melee": 1436, "npc_dota_creep_badguys_ranged": 239, "npc_dota_creep_goodguys_ranged": 927, "npc_dota_hero_pudge": 224}, "damage_taken": {"npc_dota_creep_goodguys_ranged": 220, "npc_dota_creep_goodguys_melee": 127}, "damage_inflictor": {"phantom_lancer_spirit_lance": 76, "null": 148}, "runes": {"5": 1}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {}, "randomed": false, "pred_vict": true, "gold": 982, "lh": 12, "xp": 780, "x": 82, "y": 170, "hero_inventory": [{"id": "item_tango", "num_charges": 2, "cooldown": 0}, {"id": "item_flask", "num_charges": 1, "cooldown": 0}, {"id": "item_enchanted_mango", "cooldown": 0}, {"id": "item_stout_shield", "cooldown": 0}, {"id": "item_quelling_blade", "cooldown": 0}, {"id": "item_branches", "cooldown": 0}], "hero_stash": [], "health": 650, "max_health": 720, "max_mana": 386.938, "level": 3, "kills": 0, "deaths": 0, "assists": 1, "denies": 13, "nearby_creep_death_count": 30}, {"player_slot": 129, "hero_id": 21, "hero_name": "npc_dota_hero_windrunner", "account_id_hash": "0472e177a478eb381f3534446f80cd2a", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 2, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": -5.465, "max": true, "inflictor": null, "unit": "npc_dota_hero_windrunner", "key": "npc_dota_hero_huskar", "value": 50, "slot": 6, "player_slot": 129}, "times": [0, 60, 120], "gold_t": [1, 251, 561], "lh_t": [0, 0, 5], "dn_t": [0, 1, 4], "xp_t": [0, 58, 445], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "orb_of_venom"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "tango"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": 23.428, "key": "magic_wand"}, {"time": 23.428, "key": "magic_stick"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 1.7, "key": 5}, {"time": 8.565, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 575, "2": 4, "4": 77, "11": 3, "15": 10, "16": 6, "19": 3}, "pings": {}, "purchase": {"orb_of_venom": 1, "branches": 2, "tango": 1, "enchanted_mango": 1, "tpscroll": 1, "magic_wand": 1, "magic_stick": 1}, "gold_reasons": {"0": 760, "13": 393}, "xp_reasons": {"2": 706}, "killed": {"npc_dota_creep_badguys_ranged": 159, "npc_dota_creep_goodguys_melee": 350, "npc_dota_creep_badguys_melee": 148, "npc_dota_creep_goodguys_ranged": 110}, "item_uses": {}, "ability_uses": {}, "hero_hits": {"null": 8, "orb_of_venom": 14}, "damage": {"npc_dota_hero_huskar": 402, "npc_dota_creep_goodguys_melee": 460, "npc_dota_creep_badguys_ranged": 265, "npc_dota_creep_badguys_melee": 740, "npc_dota_creep_goodguys_ranged": 110}, "damage_taken": {"npc_dota_hero_huskar": 64, "npc_dota_creep_goodguys_melee": 95, "npc_dota_creep_goodguys_ranged": 31}, "damage_inflictor": {"null": 360, "orb_of_venom": 42}, "runes": {"5": 2}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {"null": 40, "huskar_burning_spear": 24}, "randomed": false, "pred_vict": true, "gold": 788, "lh": 9, "xp": 706, "x": 174, "y": 90, "hero_inventory": [{"id": "item_orb_of_venom", "cooldown": 0}, {"id": "item_tango", "num_charges": 3, "cooldown": 0}, {"id": "item_flask", "num_charges": 1, "cooldown": 0}, {"id": "item_magic_wand", "cooldown": 0}, {"id": "item_tpscroll", "num_charges": 1, "cooldown": 0}], "hero_stash": [], "health": 640, "max_health": 640, "max_mana": 422.938, "level": 3, "kills": 0, "deaths": 0, "assists": 0, "denies": 6, "nearby_creep_death_count": 23}, {"player_slot": 130, "hero_id": 60, "hero_name": "npc_dota_hero_night_stalker", "account_id_hash": "fc1271b29e684b9e7f39817b94db73dd", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 2, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0

In [31]:
path = "DOTA 2//train_matches.jsonl"
count = 0

with open(path, "rb") as f:
    for block in iter(lambda: f.read(1024 * 1024), b""):  # читаем по 1 МБ
        count += block.count(b"\n")

print("Строк в файле:", count)

Строк в файле: 33723

In [32]:
path = "DOTA 2//test_matches.jsonl"
with open(path, "r", encoding="utf-8") as f:
    for line in itertools.islice(f, 5):  # первые 5 строк
        print(line.strip())

{"game_time": 1249, "match_id_hash": "4b6e4e511d399180776d0f23984466b2", "teamfights": [{"start": 335.581, "end": 369.61, "last_death": 354.114, "deaths": 3, "players": [{"deaths_pos": {}, "ability_uses": {"sandking_sand_storm": 1}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 157, "xp_delta": 166}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 84, "xp_delta": 111}, {"deaths_pos": {}, "ability_uses": {"furion_teleportation": 1}, "item_uses": {"magic_wand": 1, "phase_boots": 1}, "killed": {"npc_dota_hero_earthshaker": 71}, "deaths": 0, "buybacks": 0, "damage": 522, "healing": 0, "gold_delta": 170, "xp_delta": 23}, {"deaths_pos": {}, "ability_uses": {"chaos_knight_reality_rift": 1, "chaos_knight_chaos_bolt": 1}, "item_uses": {"power_treads": 3, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 307, "healing": 120, "gold_delta": -117, "xp_delta": 80}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 108, "healing": 0, "gold_delta": 93, "xp_delta": 228}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 178, "xp_delta": 285}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {"quelling_blade": 2}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 291, "xp_delta": 335}, {"deaths_pos": {}, "ability_uses": {"earthshaker_enchant_totem": 2, "earthshaker_fissure": 1}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 463, "healing": 0, "gold_delta": 130, "xp_delta": 298}, {"deaths_pos": {}, "ability_uses": {"venomancer_plague_ward": 4, "venomancer_venomous_gale": 1}, "item_uses": {}, "killed": {"npc_dota_hero_furion": 8}, "deaths": 0, "buybacks": 0, "damage": 94, "healing": 0, "gold_delta": 474, "xp_delta": 493}, {"deaths_pos": {}, "ability_uses": {"oracle_purifying_flames": 2, "oracle_fortunes_end": 1}, "item_uses": {"tpscroll": 1}, "killed": {"npc_dota_hero_chaos_knight": 41}, "deaths": 0, "buybacks": 0, "damage": 459, "healing": 0, "gold_delta": 426, "xp_delta": 460}]}, {"start": 742.049, "end": 793.573, "last_death": 778.443, "deaths": 4, "players": [{"deaths_pos": {}, "ability_uses": {"sandking_sand_storm": 1}, "item_uses": {"blink": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 499, "xp_delta": 178}, {"deaths_pos": {}, "ability_uses": {"riki_smoke_screen": 1, "riki_blink_strike": 1}, "item_uses": {"phase_boots": 4, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 68, "healing": 15, "gold_delta": 311, "xp_delta": 384}, {"deaths_pos": {}, "ability_uses": {"furion_sprout": 1, "furion_wrath_of_nature": 1}, "item_uses": {"ancient_janggo": 1, "phase_boots": 2, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 145, "healing": 135, "gold_delta": 919, "xp_delta": 0}, {"deaths_pos": {}, "ability_uses": {"chaos_knight_phantasm": 1, "chaos_knight_reality_rift": 2, "chaos_knight_chaos_bolt": 1}, "item_uses": {"armlet": 3, "magic_wand": 1}, "killed": {"npc_dota_hero_oracle": 118}, "deaths": 0, "buybacks": 0, "damage": 2372, "healing": 321, "gold_delta": 290, "xp_delta": 57}, {"deaths_pos": {}, "ability_uses": {"tinker_march_of_the_machines": 5, "tinker_rearm": 6, "tinker_heat_seeking_missile": 2, "tinker_laser": 1}, "item_uses": {"bottle": 15, "soul_ring": 4, "travel_boots": 4, "magic_stick": 1}, "killed": {"npc_dota_hero_venomancer": 271}, "deaths": 0, "buybacks": 0, "damage": 1846, "healing": 581, "gold_delta": 646, "xp_delta": 663}, {"deaths_pos": {}, "ability_uses": {"nyx_assassin_vendetta": 1, "nyx_assassin_impale": 1, "nyx_assassin_mana_burn": 2, "nyx_assassin_spiked_carapace": 1}, "item_uses": {"clarity": 1, "power_treads": 6, "quelling_blade": 1, "magic_wand": 1}, "killed": {"npc_dota_hero_furion": 74}, "deaths": 0, "buybacks": 0, "damage": 1422, "healing": 75, "gold_delta": 377, "xp_delta": 702}, {"deaths_pos": {}, "ability_uses": {"terrorblade_conjure_image": 2}, "item_uses": {"power_treads": 3, "quelling_blade": 2}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 205, "healing": 0, "gold_delta": 378, "xp_delta": 605}, {"deaths_pos": {}, "ability_uses": {"earthshaker_echo_slam": 1, "earthshaker_enchant_totem": 4}, "item_uses": {"arcane_boots": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 454, "healing": 0, "gold_delta": 540, "xp_delta": 932}, {"deaths_pos": {}, "ability_uses": {"venomancer_plague_ward": 4, "venomancer_venomous_gale": 1}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 425, "healing": 0, "gold_delta": 284, "xp_delta": 567}, {"deaths_pos": {}, "ability_uses": {"oracle_false_promise": 1, "oracle_fortunes_end": 1, "oracle_purifying_flames": 1}, "item_uses": {"magic_wand": 1, "flask": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 382, "healing": 713, "gold_delta": 142, "xp_delta": 421}]}, {"start": 956.929, "end": 1009.12, "last_death": 993.957, "deaths": 4, "players": [{"deaths_pos": {}, "ability_uses": {}, "item_uses": {"blink": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 0, "xp_delta": 0}, {"deaths_pos": {}, "ability_uses": {"riki_smoke_screen": 1, "riki_blink_strike": 2, "riki_tricks_of_the_trade": 1}, "item_uses": {"tpscroll": 1, "phase_boots": 5, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 812, "healing": 210, "gold_delta": 394, "xp_delta": 1326}, {"deaths_pos": {}, "ability_uses": {"furion_sprout": 2, "furion_force_of_nature": 1, "furion_teleportation": 1, "furion_wrath_of_nature": 1}, "item_uses": {"magic_wand": 2, "phase_boots": 3, "ancient_janggo": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 684, "healing": 135, "gold_delta": 254, "xp_delta": 700}, {"deaths_pos": {}, "ability_uses": {"chaos_knight_phantasm": 1, "chaos_knight_reality_rift": 4, "chaos_knight_chaos_bolt": 1}, "item_uses": {"magic_wand": 3, "armlet": 3, "power_treads": 1, "tpscroll": 1}, "killed": {"npc_dota_hero_terrorblade": 117, "npc_dota_hero_venomancer": 71, "npc_dota_hero_oracle": 115, "npc_dota_hero_nyx_assassin": 107}, "deaths": 0, "buybacks": 0, "damage": 4169, "healing": 238, "gold_delta": 1263, "xp_delta": 1385}, {"deaths_pos": {}, "ability_uses": {"tinker_rearm": 5, "tinker_heat_seeking_missile": 4, "tinker_march_of_the_machines": 2, "tinker_laser": 1}, "item_uses": {"soul_ring": 5, "bottle": 13, "blink": 4, "magic_stick": 1, "travel_boots": 4}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 2369, "healing": 771, "gold_delta": 347, "xp_delta": 928}, {"deaths_pos": {}, "ability_uses": {"nyx_assassin_mana_burn": 1, "nyx_assassin_impale": 2, "nyx_assassin_spiked_carapace": 1}, "item_uses": {"magic_wand": 2, "meteor_hammer": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 2300, "healing": 90, "gold_delta": -107, "xp_delta": 188}, {"deaths_pos": {}, "ability_uses": {"terrorblade_reflection": 1, "terrorblade_metamorphosis": 1}, "item_uses": {"quelling_blade": 1, "tpscroll": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 205, "healing": 0, "gold_delta": -180, "xp_delta": 136}, {"deaths_pos": {}, "ability_uses": {"earthshaker_echo_slam": 1, "earthshaker_enchant_totem": 3, "earthshaker_fissure": 2}, "item_uses": {"blink": 2, "magic_stick": 1, "tpscroll": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 1359, "healing": 30, "gold_delta": 380, "xp_delta": 478}, {"deaths_pos": {}, "ability_uses": {"venomancer_plague_ward": 2}, "item_uses": {"tpscroll": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 538, "healing": 0, "gold_delta": -70, "xp_delta": 84}, {"deaths_pos": {}, "ability_uses": {"oracle_fates_edict": 2, "oracle_purifying_flames": 3, "oracle_false_promise": 1, "oracle_fortunes_end": 1}, "item_uses": {"arcane_boots": 1, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 93, "healing": 1078, "gold_delta": -114, "xp_delta": 78}]}, {"start": 1088.797, "end": 1136.089, "last_death": 1120.993, "deaths": 4, "players": [{"deaths_pos": {}, "ability_uses": {"sandking_epicenter": 1, "sandking_burrowstrike": 1, "sandking_sand_storm": 1}, "item_uses": {"tpscroll": 1, "blink": 1, "soul_ring": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 1596, "healing": 0, "gold_delta": -156, "xp_delta": 156}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {"phase_boots": 4}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 171, "xp_delta": 802}, {"deaths_pos": {}, "ability_uses": {"furion_teleportation": 1, "furion_force_of_nature": 1, "furion_sprout": 1}, "item_uses": {"phase_boots": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": -131, "xp_delta": 176}, {"deaths_pos": {}, "ability_uses": {"chaos_knight_reality_rift": 1, "chaos_knight_chaos_bolt": 1, "chaos_knight_phantasm": 1}, "item_uses": {"armlet": 5, "power_treads": 2, "tpscroll": 1, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 1678, "healing": 573, "gold_delta": -94, "xp_delta": 297}, {"deaths_pos": {}, "ability_uses": {"tinker_rearm": 6, "tinker_laser": 1, "tinker_heat_seeking_missile": 5, "tinker_march_of_the_machines": 1}, "item_uses": {"bottle": 14, "soul_ring": 5, "travel_boots": 3, "blink": 2, "magic_stick": 1}, "killed": {"npc_dota_hero_venomancer": 272}, "deaths": 0, "buybacks": 0, "damage": 1897, "healing": 552, "gold_delta": 350, "xp_delta": 502}, {"deaths_pos": {}, "ability_uses": {"nyx_assassin_mana_burn": 2, "nyx_assassin_spiked_carapace": 1, "nyx_assassin_impale": 1, "nyx_assassin_vendetta": 1}, "item_uses": {"meteor_hammer": 1, "magic_wand": 1}, "killed": {"npc_dota_hero_furion": 108}, "deaths": 0, "buybacks": 0, "damage": 1218, "healing": 165, "gold_delta": 672, "xp_delta": 934}, {"deaths_pos": {}, "ability_uses": {"terrorblade_conjure_image": 3, "terrorblade_reflection": 1}, "item_uses": {"force_staff": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 463, "healing": 0, "gold_delta": 459, "xp_delta": 619}, {"deaths_pos": {}, "ability_uses": {"earthshaker_fissure": 2, "earthshaker_enchant_totem": 2, "earthshaker_echo_slam": 1}, "item_uses": {"blink": 3, "force_staff": 1, "magic_stick": 1, "arcane_boots": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 1533, "healing": 120, "gold_delta": 443, "xp_delta": 948}, {"deaths_pos": {}, "ability_uses": {"venomancer_plague_ward": 5, "venomancer_venomous_gale": 1, "venomancer_poison_nova": 1}, "item_uses": {"magic_wand": 1, "power_treads": 1}, "killed": {"npc_dota_hero_sand_king": 82}, "deaths": 0, "buybacks": 0, "damage": 1666, "healing": 8, "gold_delta": 736, "xp_delta": 896}, {"deaths_pos": {}, "ability_uses": {"oracle_purifying_flames": 3, "oracle_fortunes_end": 1, "oracle_false_promise": 1}, "item_uses": {"arcane_boots": 1}, "killed": {"npc_dota_hero_chaos_knight": 280}, "deaths": 0, "buybacks": 0, "damage": 512, "healing": 0, "gold_delta": 951, "xp_delta": 856}]}, {"start": 1143.45, "end": 1178.612, "last_death": 1163.483, "deaths": 3, "players": [{"deaths_pos": {}, "ability_uses": {}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 0, "xp_delta": 0}, {"deaths_pos": {}, "ability_uses": {"riki_blink_strike": 2, "riki_smoke_screen": 2, "riki_tricks_of_the_trade": 1}, "item_uses": {"ward_dispenser": 1, "phase_boots": 4, "ring_of_aquila": 1, "magic_wand": 1}, "killed": {"npc_dota_hero_oracle": 110}, "deaths": 0, "buybacks": 0, "damage": 911, "healing": 135, "gold_delta": 324, "xp_delta": 1329}, {"deaths_pos": {}, "ability_uses": {"furion_wrath_of_nature": 1, "furion_teleportation": 1, "furion_force_of_nature": 1, "furion_sprout": 1}, "item_uses": {"phase_boots": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 509, "healing": 0, "gold_delta": 23, "xp_delta": 19}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 0, "xp_delta": 0}, {"deaths_pos": {}, "ability_uses": {"tinker_rearm": 3, "tinker_march_of_the_machines": 1, "tinker_heat_seeking_missile": 2, "tinker_laser": 1}, "item_uses": {"bottle": 4, "blink": 2, "soul_ring": 2, "magic_stick": 1}, "killed": {"npc_dota_hero_nyx_assassin": 332}, "deaths": 0, "buybacks": 0, "damage": 2539, "healing": 175, "gold_delta": 463, "xp_delta": 1331}, {"deaths_pos": {}, "ability_uses": {"nyx_assassin_impale": 1, "nyx_assassin_spiked_carapace": 1}, "item_uses": {"magic_wand": 1, "quelling_blade": 2}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 27, "healing": 75, "gold_delta": -223, "xp_delta": 38}, {"deaths_pos": {}, "ability_uses": {"terrorblade_conjure_image": 2, "terrorblade_reflection": 1, "terrorblade_sunder": 1, "terrorblade_metamorphosis": 1}, "item_uses": {"force_staff": 1, "power_treads": 3, "quelling_blade": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 1386, "healing": 830, "gold_delta": 232, "xp_delta": 682}, {"deaths_pos": {}, "ability_uses": {"earthshaker_fissure": 1}, "item_uses": {"blink": 2, "force_staff": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 201, "healing": 0, "gold_delta": 0, "xp_delta": 45}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {"tpscroll": 1, "hand_of_midas": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 200, "xp_delta": 184}, {"deaths_pos": {}, "ability_uses": {"oracle_fates_edict": 1, "oracle_purifying_flames": 2, "oracle_fortunes_end": 1}, "item_uses": {"magic_wand": 1, "dust": 1}, "killed": {"npc_dota_hero_furion": 102}, "deaths": 0, "buybacks": 0, "damage": 348, "healing": 1014, "gold_delta": 392, "xp_delta": 752}]}], "objectives": [{"time": 614.883, "type": "CHAT_MESSAGE_TOWER_DENY", "team": 60, "slot": 8, "player_slot": 131}, {"time": 719.124, "type": "CHAT_MESSAGE_TOWER_KILL", "team": 2, "slot": -1}, {"time": 764.113, "type": "CHAT_MESSAGE_TOWER_KILL", "team": 2, "slot": 2, "player_slot": 2}, {"time": 1059.041, "type": "CHAT_MESSAGE_TOWER_KILL", "team": 2, "slot": 3, "player_slot": 3}, {"time": 1120.56, "type": "CHAT_MESSAGE_TOWER_KILL", "team": 3, "slot": 8, "player_slot": 131}], "chat": [{"player_slot": 4, "time": 512.375, "text": "*****"}, {"player_slot": 4, "time": 514.441, "text": "******"}, {"player_slot": 4, "time": 516.974, "text": "** **** ***"}, {"player_slot": 1, "time": 655.54, "text": "))"}], "game_mode": 22, "lobby_type": 7, "players": [{"player_slot": 0, "hero_id": 16, "hero_name": "npc_dota_hero_sand_king", "account_id_hash": "5f8e7c02c758eb0a517002e7484a7918", "ability_upgrades": [{"ability": 5102, "time": 308, "level": 1}, {"ability": 5103, "time": 502, "level": 2}, {"ability": 5103, "time": 639, "level": 3}, {"ability": 5102, "time": 792, "level": 4}, {"ability": 5102, "time": 911, "level": 5}, {"ability": 5103, "time": 995, "level": 6}, {"ability": 5103, "time": 1037, "level": 7}], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 6, "camps_stacked": 3, "rune_pickups": 11, "firstblood_claimed": 0, "teamfight_participation": 0.238, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 50.655, "max_hero_hit": {"type": "max_hero_hit", "time": 948.502, "max": true, "inflictor": "sandking_burrowstrike", "unit": "npc_dota_hero_sand_king", "key": "npc_dota_hero_terrorblade", "value": 214, "slot": 0, "player_slot": 0}, "times": [0, 60, 120, 180, 240, 300, 360, 420, 480, 540, 600, 660, 720, 780, 840, 900, 960, 1020, 1080, 1140, 1200], "gold_t": [1, 211, 328, 419, 718, 909, 1073, 1248, 1469, 1707, 1829, 2182, 2777, 3480, 3690, 3781, 4420, 4511, 5095, 5472, 5700], "lh_t": [0, 0, 0, 0, 2, 2, 6, 6, 10, 12, 13, 17, 25, 30, 32, 32, 38, 38, 43, 43, 46], "dn_t": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 4], "xp_t": [0, 49, 125, 202, 427, 579, 786, 849, 1166, 1620, 1710, 2123, 2827, 3141, 3271, 3278, 3764, 3821, 4478, 4634, 4799], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.861, "key": "tango"}, {"time": -89.861, "key": "orb_of_venom"}, {"time": -89.861, "key": "tpscroll"}, {"time": -83.326, "key": "clarity"}, {"time": -82.393, "key": "tango"}, {"time": 223.046, "key": "boots"}, {"time": 264.935, "key": "wind_lace"}, {"time": 265.335, "key": "tpscroll"}, {"time": 427.229, "key": "tranquil_boots"}, {"time": 427.229, "key": "ring_of_regen"}, {"time": 435.594, "key": "tpscroll"}, {"time": 789.574, "key": "blink"}, {"time": 989.792, "key": "tpscroll"}, {"time": 1058.875, "key": "ring_of_regen"}, {"time": 1059.008, "key": "gauntlets"}, {"time": 1059.141, "key": "gauntlets"}, {"time": 1059.308, "key": "soul_ring"}, {"time": 1151.819, "key": "tpscroll"}, {"time": 1152.152, "key": "tpscroll"}, {"time": 1218.536, "key": "tome_of_knowledge"}, {"time": 1246.729, "key": "tpscroll"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 1.766, "key": 5}, {"time": 185.255, "key": 5}, {"time": 360.279, "key": 5}, {"time": 748.517, "key": 5}, {"time": 755.182, "key": 5}, {"time": 916.276, "key": 5}, {"time": 920.409, "key": 5}, {"time": 1016.252, "key": 3}, {"time": 1046.978, "key": 5}, {"time": 1081.836, "key": 5}, {"time": 1088.301, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 3929, "2": 2, "4": 395, "5": 18, "6": 20, "7": 4, "8": 24, "10": 35, "11": 10, "14": 2, "15": 35, "16": 21, "19": 3, "27": 1, "33": 35}, "pings": {"0": 1}, "purchase": {"tango": 2, "orb_of_venom": 1, "tpscroll": 7, "clarity": 1, "boots": 1, "wind_lace": 1, "tranquil_boots": 1, "ring_of_regen": 2, "blink": 1, "gauntlets": 2, "soul_ring": 1, "recipe_soul_ring": 1, "tome_of_knowledge": 1}, "gold_reasons": {"0": 1763, "1": -645, "11": 500, "12": 264, "13": 2061}, "xp_reasons": {"0": 1, "1": 437, "2": 4734}, "killed": {"npc_dota_creep_badguys_melee": 1803, "npc_dota_neutral_satyr_trickster": 119, "npc_dota_neutral_satyr_soulstealer": 105, "npc_dota_neutral_dark_troll": 114, "npc_dota_neutral_dark_troll_warlord": 30, "npc_dota_neutral_satyr_hellcaller": 24, "npc_dota_neutral_polar_furbolg_ursa_warrior": 30, "npc_dota_neutral_polar_furbolg_champion": 24, "npc_dota_creep_goodguys_melee": 200, "npc_dota_creep_badguys_ranged": 698, "npc_dota_creep_goodguys_ranged": 77, "npc_dota_neutral_centaur_outrunner": 40, "npc_dota_neutral_centaur_khan": 50}, "item_uses": {"tango": 6, "tpscroll": 5, "clarity": 1, "blink": 10, "soul_ring": 2}, "ability_uses": {"sandking_burrowstrike": 18, "sandking_sand_storm": 19, "sandking_epicenter": 1}, "hero_hits": {"null": 34, "orb_of_venom": 51, "sandking_burrowstrike": 18, "sandking_sand_storm": 35, "sandking_epicenter": 10}, "damage": {"npc_dota_hero_venomancer": 1807, "npc_dota_hero_earthshaker": 957, "npc_dota_hero_terrorblade": 1337, "illusion_npc_dota_hero_terrorblade": 6083, "npc_dota_creep_badguys_melee": 12000, "npc_dota_hero_oracle": 879, "npc_dota_creep_badguys_ranged": 2743, "npc_dota_neutral_centaur_outrunner": 758, "npc_dota_neutral_satyr_soulstealer": 1745, "npc_dota_neutral_satyr_trickster": 719, "npc_dota_neutral_enraged_wildkin": 117, "npc_dota_neutral_wildkin": 120, "npc_dota_neutral_dark_troll": 2040, "npc_dota_neutral_dark_troll_warlord": 1620, "npc_dota_neutral_polar_furbolg_ursa_warrior": 1878, "npc_dota_neutral_polar_furbolg_champion": 1248, "npc_dota_hero_nyx_assassin": 996, "npc_dota_neutral_satyr_hellcaller": 1003, "npc_dota_creep_goodguys_melee": 381, "npc_dota_badguys_siege": 216, "npc_dota_creep_goodguys_ranged": 141, "npc_dota_neutral_centaur_khan": 920}, "damage_taken": {"npc_dota_hero_venomancer": 2019, "npc_dota_hero_earthshaker": 1277, "npc_dota_creep_badguys_ranged": 330, "npc_dota_creep_badguys_melee": 584, "npc_dota_hero_oracle": 2148, "npc_dota_hero_terrorblade": 644, "npc_dota_neutral_centaur_outrunner": 12, "npc_dota_neutral_wildkin": 26, "npc_dota_neutral_enraged_wildkin": 43, "npc_dota_neutral_satyr_trickster": 4, "npc_dota_neutral_satyr_soulstealer": 16, "npc_dota_neu

In [33]:
path = "DOTA 2//test_matches.jsonl"
count = 0

with open(path, "rb") as f:
    for block in iter(lambda: f.read(1024 * 1024), b""):  # читаем по 1 МБ
        count += block.count(b"\n")

print("Строк в файле:", count)

Строк в файле: 5952

In [34]:
src = "DOTA 2//train_matches.jsonl"
dst = "train_matches_sample.jsonl"

step = 1  # каждую сотую строку берём в семпл

with open(src, "r", encoding="utf-8") as fin, open(dst, "w", encoding="utf-8") as fout:
    for i, line in enumerate(fin, start=1):
        if not line.strip():
            continue
        if i % step == 0:
            fout.write(line)

print("Готово, семпл сохранён в", dst)

Готово, семпл сохранён в train_matches_sample.jsonl

# Предобработка

In [35]:
# import json

# jsonl_path = "DOTA 2/train_matches.jsonl"

# # set со всеми match_id_hash из файла
# jsonl_ids = set()

# with open(jsonl_path, "r", encoding="utf8") as f:
#     for line in f:
#         obj = json.loads(line)
#         jsonl_ids.add(obj["match_id_hash"])

# print("ID в JSONL:", len(jsonl_ids))

In [36]:
# feature_ids = set(raw_features["match_id_hash"])

# print("ID в таблице:", len(feature_ids))

# missing = jsonl_ids - feature_ids
# print("Отсутствуют:", len(missing))

# if missing:
#     print("Примеры отсутствующих:", list(missing)[:10])
# else:
#     print("Все match_id_hash присутствуют")

In [37]:
# import json

# train_path = "DOTA 2/train_matches.jsonl"
# test_path = "DOTA 2/test_matches.jsonl"

# def load_ids(path):
#     ids = set()
#     with open(path, "r", encoding="utf8") as f:
#         for line in f:
#             obj = json.loads(line)
#             ids.add(obj["match_id_hash"])
#     return ids

# # Загружаем id из обоих файлов
# train_ids = load_ids(train_path)
# test_ids = load_ids(test_path)

# # Объединяем множества
# jsonl_ids = train_ids.union(test_ids)

# print("ID в train:", len(train_ids))
# print("ID в test:", len(test_ids))
# print("Всего уникальных ID:", len(jsonl_ids))

# # ID из твоей таблицы признаков
# feature_ids = set(raw_features["match_id_hash"])

# print("ID в таблице:", len(feature_ids))

# # Проверка отсутствующих
# missing = jsonl_ids - feature_ids
# print("Отсутствуют:", len(missing))

# if missing:
#     print("Примеры отсутствующих:", list(missing)[:10])
# else:
#     print("Все match_id_hash присутствуют в таблице признаков")

In [38]:
# import json

# train_path = "DOTA 2/train_matches.jsonl"
# test_path = "DOTA 2/test_matches.jsonl"

# def load_ids(path):
#     ids = set()
#     with open(path, "r", encoding="utf8") as f:
#         for line in f:
#             obj = json.loads(line)
#             ids.add(obj["match_id_hash"])
#     return ids

# # Загружаем id из обоих файлов
# train_ids = load_ids(train_path)
# test_ids = load_ids(test_path)

# # Объединяем множества
# jsonl_ids = train_ids.union(test_ids)

# print("ID в train:", len(train_ids))
# print("ID в test:", len(test_ids))
# print("Всего уникальных ID:", len(jsonl_ids))

# # ID из твоей таблицы признаков
# feature_ids = set(test_features["match_id_hash"])

# print("ID в таблице:", len(feature_ids))

# # Проверка отсутствующих
# missing = jsonl_ids - feature_ids
# print("Отсутствуют:", len(missing))

# if missing:
#     print("Примеры отсутствующих:", list(missing)[:10])
# else:
#     print("Все match_id_hash присутствуют в таблице признаков")

In [39]:
# df = pd.read_json("train_matches_sample.jsonl", lines=True)
# df.head()

In [40]:
# df['players'][1]

# Моделирование

## Catboost

In [41]:
model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.1,
    depth=7,
    loss_function='Logloss',
    eval_metric='AUC',
    random_state=RANDOM_STATE,
    verbose=100)


X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,      
    random_state=RANDOM_STATE,    
    stratify=y,
    shuffle=True         
)

model.fit(X_train, y_train)#, eval_set=(X_test, y_test), verbose=100)

0:	total: 182ms	remaining: 3m 1s
100:	total: 1.33s	remaining: 11.9s
200:	total: 2.48s	remaining: 9.86s
300:	total: 3.66s	remaining: 8.5s
400:	total: 4.83s	remaining: 7.21s
500:	total: 5.98s	remaining: 5.96s
600:	total: 7.12s	remaining: 4.73s
700:	total: 8.28s	remaining: 3.53s
800:	total: 9.42s	remaining: 2.34s
900:	total: 10.6s	remaining: 1.16s
999:	total: 11.7s	remaining: 0us

# Оценка

In [42]:
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)[:, 1]

accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_proba)

print(f"Accuracy: {accuracy:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

Accuracy: 0.7269
ROC AUC: 0.8163

In [43]:
y_pred

array([ True,  True, False, ..., False,  True,  True])

In [44]:
# model = CatBoostClassifier(
#     iterations=1000,
#     learning_rate=0.1,
#     depth=7,
#     loss_function='Logloss',
#     eval_metric='AUC',
#     random_state=RANDOM_STATE,
#     verbose=100)


# X_train, X_test, y_train, y_test = train_test_split(
#     X, y,
#     test_size=0.25,      
#     random_state=RANDOM_STATE,    
#     stratify=y,
#     shuffle=True         
# )

# model.fit(X_train, y_train)#, eval_set=(X_test, y_test), verbose=100)

# y_pred = model.predict(X_test)
# accuracy = accuracy_score(y_test, y_pred)
# roc_auc = roc_auc_score(y_test, y_pred)

# print(f"Accuracy: {accuracy:.4f}")
# print(f"ROC AUC: {roc_auc:.4f}")

# Выводы