# Введение

# imports

In [1]:
import ast
import itertools
import json
import random

import ipywidgets as widgets
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier
from IPython.display import clear_output, display
from matplotlib.lines import Line2D
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", None)





RANDOM_STATE = 42

# Данные/EDA

In [2]:
raw_features = pd.read_csv("train_features.csv")
raw_features.head()

,match_id_hash,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed
0,a400b8f29dece5f4d266f49f1ae2e98a,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.0,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.00,0,0,0,0
1,b9c57c450ce74a2af79c9ce96fac144d,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.5,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.00,0,0,0,0
2,6db558535151ea18ca70a6892197db41,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.0,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.00,0,0,0,0
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.0,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.00,0,0,2,0
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.5,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.25,0,0,0,0

In [3]:
test_features = pd.read_csv("test_features (1).csv")

In [4]:
raw_features['lobby_type'].value_counts()

lobby_type
7    27049
0    12626
Name: count, dtype: int64

In [5]:
raw_targets = pd.read_csv("train_targets.csv")
raw_targets.head()

,match_id_hash,game_time,radiant_win,duration,time_remaining,next_roshan_team
0,a400b8f29dece5f4d266f49f1ae2e98a,155,False,992,837,NaN
1,b9c57c450ce74a2af79c9ce96fac144d,658,True,1154,496,NaN
2,6db558535151ea18ca70a6892197db41,21,True,1503,1482,Radiant
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,True,1952,1376,NaN
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,False,2001,1548,NaN

In [6]:
# df_feats = create_features(raw_features)

In [7]:
# df_feats

In [8]:

train_jsonl_path = "DOTA 2/train_matches.jsonl"
test_jsonl_path = "DOTA 2/test_matches.jsonl"

df_train_matches = pd.read_json(train_jsonl_path, lines=True)
df_test_matches  = pd.read_json(test_jsonl_path, lines=True)

df_json_matches = pd.concat([df_train_matches, df_test_matches], ignore_index=True)

print(df_train_matches.columns)

Index(['game_time', 'match_id_hash', 'teamfights', 'objectives', 'chat',
       'game_mode', 'lobby_type', 'players', 'targets'],
      dtype='object')

In [9]:
df_train_matches.sample(10)

,game_time,match_id_hash,teamfights,objectives,chat,game_mode,lobby_type,players,targets
3196,365,590df5abf9483b43ff8bad4d561700d2,"[{'start': 288.226, 'end': 333.452, 'last_deat...","[{'time': 60.319, 'type': 'CHAT_MESSAGE_FIRSTB...","[{'player_slot': 131, 'time': 230.744, 'text':...",22,0,"[{'player_slot': 0, 'hero_id': 5, 'hero_name':...","{'game_time': 365, 'duration': 2095, 'time_rem..."
8699,400,a10f2f8b2bd1709fd47d4cb748fde8fc,"[{'start': 147.76, 'end': 208.649, 'last_death...","[{'time': -7.098, 'type': 'CHAT_MESSAGE_FIRSTB...",[],22,7,"[{'player_slot': 0, 'hero_id': 82, 'hero_name'...","{'game_time': 400, 'duration': 1330, 'time_rem..."
5369,2118,2167e6c835729443e22d1bd9d3d76d48,"[{'start': 659.102, 'end': 702.095, 'last_deat...","[{'time': 76.248, 'type': 'CHAT_MESSAGE_FIRSTB...","[{'player_slot': 1, 'time': 907.245, 'text': '...",22,7,"[{'player_slot': 0, 'hero_id': 119, 'hero_name...","{'game_time': 2118, 'duration': 2855, 'time_re..."
23679,1454,d60673e9d4ee919702c73bad85c8951d,"[{'start': 519.536, 'end': 562.829, 'last_deat...","[{'time': 7.032, 'type': 'CHAT_MESSAGE_FIRSTBL...","[{'player_slot': 3, 'time': 59.219, 'text': '?...",22,7,"[{'player_slot': 0, 'hero_id': 99, 'hero_name'...","{'game_time': 1454, 'duration': 1698, 'time_re..."
28203,2763,69b767f73cbde54b387c915f0380bdaa,"[{'start': 1603.938, 'end': 1640.033, 'last_de...","[{'time': 182.922, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 0, 'time': 1278.188, 'text': ...",22,0,"[{'player_slot': 0, 'hero_id': 8, 'hero_name':...","{'game_time': 2763, 'duration': 3144, 'time_re..."
11703,580,cffd82de05b21dd031e22794cc468f2b,"[{'start': 508.972, 'end': 570.127, 'last_deat...","[{'time': 249.706, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 0, 'time': -201.48, 'text': '...",22,7,"[{'player_slot': 0, 'hero_id': 19, 'hero_name'...","{'game_time': 580, 'duration': 2783, 'time_rem..."
6383,65,d31ac8b2ff677ce624c180b1cced3c2c,[],[],[],22,7,"[{'player_slot': 0, 'hero_id': 104, 'hero_name...","{'game_time': 65, 'duration': 2036, 'time_rema..."
29619,2851,489f5950e3f39259464a4e308ce2bdf5,"[{'start': 356.409, 'end': 401.069, 'last_deat...","[{'time': 13.163, 'type': 'CHAT_MESSAGE_FIRSTB...","[{'player_slot': 130, 'time': 1593.211, 'text'...",22,0,"[{'player_slot': 0, 'hero_id': 50, 'hero_name'...","{'game_time': 2851, 'duration': 3117, 'time_re..."
21232,1163,1ebbecf19587ccc08b812b7e15f76c2d,"[{'start': 853.755, 'end': 900.08, 'last_death...","[{'time': 167.259, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 131, 'time': -200.251, 'text'...",22,0,"[{'player_slot': 0, 'hero_id': 100, 'hero_name...","{'game_time': 1163, 'duration': 1872, 'time_re..."
13133,1335,6f56c6f5d59191ee3d9103bfd3ca7ef3,"[{'start': 486.811, 'end': 532.803, 'last_deat...","[{'time': 128.302, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 1, 'time': 150.297, 'text': '...",22,0,"[{'player_slot': 0, 'hero_id': 72, 'hero_name'...","{'game_time': 1335, 'duration': 3075, 'time_re..."

In [10]:
longest_match_id = df_train_matches['game_time'].idxmax()

In [11]:
df_train_matches['players'][1]

[{'player_slot': 0,
  'hero_id': 15,
  'hero_name': 'npc_dota_hero_razor',
  'account_id_hash': '390104597f914d032c19bfa4afb2859b',
  'ability_upgrades': [{'ability': 5083, 'time': 191, 'level': 1},
   {'ability': 5084, 'time': 286, 'level': 2},
   {'ability': 5083, 'time': 367, 'level': 3},
   {'ability': 5084, 'time': 450, 'level': 4},
   {'ability': 5083, 'time': 552, 'level': 5},
   {'ability': 5085, 'time': 611, 'level': 6}],
  'obs_placed': 0,
  'sen_placed': 0,
  'creeps_stacked': 0,
  'camps_stacked': 0,
  'rune_pickups': 0,
  'firstblood_claimed': 0,
  'teamfight_participation': 0.438,
  'towers_killed': 0,
  'roshans_killed': 0,
  'observers_placed': 0,
  'stuns': 0,
  'max_hero_hit': {'type': 'max_hero_hit',
   'time': 538.262,
   'max': True,
   'inflictor': None,
   'unit': 'npc_dota_hero_razor',
   'key': 'npc_dota_hero_pudge',
   'value': 216,
   'slot': 0,
   'player_slot': 0},
  'times': [0, 60, 120, 180, 240, 300, 360, 420, 480, 540, 600],
  'gold_t': [41, 819, 1196, 1467, 1839, 2356, 2812, 3444, 3824, 4438, 4969],
  'lh_t': [0, 2, 8, 12, 18, 22, 25, 33, 39, 45, 52],
  'dn_t': [0, 0, 1, 5, 5, 7, 7, 7, 7, 7, 7],
  'xp_t': [0, 166, 395, 702, 1038, 1497, 1759, 2387, 2821, 3425, 3937],
  'obs_log': [],
  'sen_log': [],
  'obs_left_log': [],
  'sen_left_log': [],
  'purchase_log': [{'time': -89.781, 'key': 'tpscroll'},
   {'time': -70.815, 'key': 'wind_lace'},
   {'time': -69.748, 'key': 'tango'},
   {'time': -69.015, 'key': 'branches'},
   {'time': -68.848, 'key': 'branches'},
   {'time': -54.912, 'key': 'slippers'},
   {'time': -48.31, 'key': 'enchanted_mango'},
   {'time': -45.676, 'key': 'branches'},
   {'time': 30.94, 'key': 'magic_wand'},
   {'time': 30.94, 'key': 'magic_stick'},
   {'time': 129.695, 'key': 'boots'},
   {'time': 133.461, 'key': 'blades_of_attack'},
   {'time': 133.661, 'key': 'blades_of_attack'},
   {'time': 134.561, 'key': 'dust'},
   {'time': 220.373, 'key': 'phase_boots'},
   {'time': 220.373, 'key': 'boots'},
   {'time': 262.063, 'key': 'tango'},
   {'time': 262.496, 'key': 'flask'},
   {'time': 304.219, 'key': 'tpscroll'},
   {'time': 306.685, 'key': 'tpscroll'},
   {'time': 419.724, 'key': 'sobi_mask'},
   {'time': 419.924, 'key': 'circlet'},
   {'time': 420.091, 'key': 'gauntlets'},
   {'time': 420.258, 'key': 'bracer'},
   {'time': 469.479, 'key': 'ancient_janggo'},
   {'time': 622.575, 'key': 'blade_of_alacrity'},
   {'time': 624.908, 'key': 'dust'},
   {'time': 625.741, 'key': 'tpscroll'}],
  'kills_log': [{'time': 2.901, 'key': 'npc_dota_hero_pudge'},
   {'time': 15.837, 'key': 'npc_dota_hero_clinkz'},
   {'time': 26.106, 'key': 'npc_dota_hero_pudge'},
   {'time': 286.257, 'key': 'npc_dota_hero_clinkz'},
   {'time': 347.275, 'key': 'npc_dota_hero_pudge'},
   {'time': 397.83, 'key': 'npc_dota_hero_pudge'},
   {'time': 538.262, 'key': 'npc_dota_hero_pudge'}],
  'buyback_log': [],
  'runes_log': [],
  'obs': {},
  'sen': {},
  'actions': {'1': 2980,
   '2': 23,
   '3': 4,
   '4': 526,
   '5': 2,
   '6': 9,
   '7': 6,
   '8': 39,
   '10': 113,
   '11': 8,
   '12': 4,
   '14': 4,
   '16': 25,
   '17': 3,
   '19': 11,
   '27': 3,
   '33': 113},
  'pings': {'0': 16},
  'purchase': {'tpscroll': 4,
   'wind_lace': 1,
   'tango': 2,
   'branches': 3,
   'slippers': 1,
   'enchanted_mango': 1,
   'magic_wand': 1,
   'magic_stick': 1,
   'boots': 2,
   'blades_of_attack': 2,
   'dust': 2,
   'phase_boots': 1,
   'flask': 1,
   'sobi_mask': 1,
   'circlet': 1,
   'gauntlets': 1,
   'bracer': 1,
   'recipe_bracer': 1,
   'recipe_ancient_janggo': 1,
   'ancient_janggo': 1,
   'blade_of_alacrity': 1},
  'gold_reasons': {'0': 720,
   '1': -294,
   '6': 660,
   '11': 320,
   '12': 1413,
   '13': 2407},
  'xp_reasons': {'1': 781, '2': 3156},
  'killed': {'npc_dota_hero_pudge': 598,
   'npc_dota_hero_clinkz': 211,
   'npc_dota_creep_badguys_melee': 2751,
   'npc_dota_creep_goodguys_ranged': 100,
   'npc_dota_creep_badguys_ranged': 1394,
   'npc_dota_creep_goodguys_melee': 281,
   'npc_dota_badguys_siege': 74},
  'item_uses': {'tango': 6,
   'phase_boots': 20,
   'tpscroll': 2,
   'dust': 2,
   'magic_wand': 2,
   'flask': 1,
   'ancient_janggo': 1},
  'ability_uses': {'razor_static_link': 8, 'razor_eye_of_the_storm': 1},
  'hero_hits': {'null': 42,
   'razor_unstable_current': 6,
   'centaur_stampede': 1,
   'razor_eye_of_the_storm': 4},
  'damage': {'npc_dota_hero_pudge': 2298,
   'npc_dota_hero_clinkz': 2151,
   'npc_dota_creep_goodguys_melee': 719,
   'npc_dota_creep_badguys_melee': 10986,
   'npc_dota_creep_goodguys_ranged': 149,
   'npc_dota_creep_badguys_ranged': 3452,
   'npc_dota_neutral_centaur_outrunner': 81,
   'npc_dota_badguys_siege': 540,
   'npc_dota_badguys_tower1_bot': 184,
   'npc_dota_neutral_polar_furbolg_champion': 115,
   'npc_dota_hero_enchantress': 100,
   'npc_dota_hero_antimage': 107},
  'damage_taken': {'npc_dota_hero_pudge': 488,
   'npc_dota_hero_clinkz': 1320,
   'npc_dota_creep_badguys_ranged': 371,
   'npc_dota_creep_badguys_melee': 628,
   'npc_dota_badguys_tower1_mid': 609,
   'npc_dota_badguys_tower1_bot': 586,
   'npc_dota_badguys_tower2_bot': 100,
   'npc_dota_neutral_polar_furbolg_champion': 98,
   'npc_dota_hero_enchantress': 578,
   'npc_dota_hero_antimage': 79},
  'damage_inflictor': {'null': 3904,
   'razor_unstable_current': 573,
   'centaur_stampede': 42,
   'razor_eye_of_the_storm': 137},
  'runes': {},
  'killed_by': {'npc_dota_badguys_tower1_mid': 1,
   'npc_dota_hero_enchantress': 1},
  'kill_streaks': {'3': 2, '4': 1},
  'multi_kills': {'2': 1, '3': 1},
  'life_state': {'0': 1230, '1': 14, '2': 72},
  'healing': {'npc_dota_hero_razor': 530},
  'damage_inflictor_received': {'pudge_rot': 344,
   'clinkz_searing_arrows': 526,
   'null': 1419,
   'enchantress_impetus': 176},
  'randomed': False,
  'pred_vict': False,
  'gold': 5257,
  'lh': 52,
  'xp': 3937,
  'x': 76,
  'y': 78,
  'hero_inventory': [{'id': 'item_phase_boots', 'cooldown': 0},
   {'id': 'item_magic_wand', 'num_charges': 2, 'cooldown': 0},
   {'id': 'item_blade_of_alacrity', 'cooldown': 0},
   {'id': 'item_tpscroll', 'num_charges': 2, 'cooldown': 6.021},
   {'id': 'item_ancient_janggo', 'num_charges': 5, 'cooldown': 0},
   {'id': 'item_dust', 'num_charges': 2, 'cooldown': 0}],
  'hero_stash': [],
  'health': 1160,
  'max_health': 1160,
  'max_mana': 566.938,
  'level': 8,
  'kills': 7,
  'deaths': 2,
  'assists': 0,
  'denies': 7,
  'nearby_creep_death_count': 79},
 {'player_slot': 1,
  'hero_id': 96,
  'hero_name': 'npc_dota_hero_centaur',
  'account_id_hash': '1c2500195e6ab646fc9371344724aa77',
  'ability_upgrades': [{'ability': 5514, 'time': 232, 'level': 1},
   {'ability': 5515, 'time': 304, 'level': 2},
   {'ability': 5515, 'time': 322, 'level': 3},
   {'ability': 5514, 'time': 391, 'level': 4},
   {'ability': 5515, 'time': 499, 'level': 5},
   {'ability': 5517, 'time': 581, 'level': 6}],
  'obs_placed': 0,
  'sen_placed': 0,
  'creeps_stacked': 0,
  'camps_stacked': 0,
  'rune_pickups': 4,
  'firstblood_claimed': 0,
  'teamfight_participation': 0.312,
  'towers_killed': 0,
  'roshans_killed': 0,
  'observers_placed': 0,
  'stuns': 8.398,
  'max_hero_hit': {'type': 'max_hero_hit',
   'time': 460.981,
   'max': True,
   'inflictor': 'centaur_double_edge',
   'unit': 'npc_dota_hero_centaur',
   'key': 'npc_dota_hero_antimage',
   'value': 247,
   'slot': 1,
   'player_slot': 1},
  'times': [0, 60, 120, 180, 240, 300, 360, 420, 480, 540, 600],
  'gold_t': [41, 211, 340, 589, 762, 1209, 1579, 1803, 2404, 2796, 3106],
  'lh_t': [0, 0, 1, 5, 8, 9, 10, 13, 15, 17, 19],
  'dn_t': [0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3],
  'xp_t': [0, 57, 452, 1022, 1103, 1641, 1991, 2388, 3061, 3327, 3769],
  'obs_log': [],
  'sen_log': [],
  'obs_left_log': [],
  'sen_left_log': [],
  'purchase_log': [{'time': -89.781, 'key': 'stout_shield'},
   {'time': -89.781, 'key': 'enchanted_mango'},
   {'time': -89.781, 'key': 'tango'},
   {'time': -89.781, 'key': 'flask'},
   {'time': -89.781, 'key': 'tpscroll'},
   {'time': 176.784, 'key': 'ring_of_regen'},
   {'time': 176.95, 'key': 'gauntlets'},
   {'time': 177.05, 'key': 'gauntlets'},
   {'time': 199.245, 'key': 'tpscroll'},
   {'time': 257.797, 'key': 'tango'},
   {'time': 279.559, 'key': 'soul_ring'},
   {'time': 343.743, 'key': 'boots'},
   {'time': 370.803, 'key': 'wind_lace'},
   {'time': 398.996, 'key': 'tpscroll'},
   {'time': 466.58, 'key': 'ring_of_regen'},
   {'time': 478.01, 'key': 'tango'},
   {'time': 516.701, 'key': 'tranquil_boots'},
   {'time': 590.483, 'key': 'chainmail'},
   {'time': 629.673, 'key': 'tpscroll'}],
  'kills_log': [{'time': 242.168, 'key': 'npc_dota_hero_antimage'},
   {'time': 334.245, 'key': 'npc_dota_hero_enchantress'},
   {'time': 462.814, 'key': 'npc_dota_hero_antimage'}],
  'buyback_log': [],
  'runes_log': [{'time': 0.167, 'key': 5},
   {'time': 475.777, 'key': 5},
   {'time': 480.176, 'key': 5},
   {'time': 501.305, 'key': 5}],
  'obs': {},
  'sen': {},
  'actions': {'1': 3679,
   '2': 2,
   '4': 810,
   '5': 4,
   '6': 42,
   '7': 12,
   '8': 31,
   '10': 183,
   '11': 8,
   '15': 19,
   '16': 18,
   '19': 14,
   '33': 183},
  'pings': {'0': 6},
  'purchase': {'stout_shield': 1,
   'enchanted_mango': 1,
   'tango': 3,
   'flask': 1,
   'tpscroll': 4,
   'ring_of_regen': 2,
   'gauntlets': 2,
   'recipe_soul_ring': 1,
   'soul_ring': 1,
   'boots': 1,
   'wind_lace': 1,
   'tranquil_boots': 1,
   'chainmail': 1},
  'gold_reasons': {'0': 996, '1': -125, '11': 320, '12': 880, '13': 801},
  'xp_reasons': {'1': 600, '2': 3297},
  'killed': {'npc_dota_creep_goodguys_ranged': 137,
   'npc_dota_creep_badguys_melee': 1555,
   'npc_dota_creep_goodguys_melee': 59,
   'npc_dota_neutral_wildkin': 506,
   'npc_dota_neutral_enraged_wildkin': 253,
   'npc_dota_hero_antimage': 252,
   'npc_dota_hero_enchantress': 71,
   'npc_dota_creep_badguys_ranged': 1380},
  'item_uses': {'tango': 12,
   'tpscroll': 4,
   'flask': 1,
   'enchanted_mango': 1,
   'soul_ring': 4},
  'ability_uses': {'centaur_hoof_stomp': 8,
   'centaur_double_edge': 11,
   'centaur_stampede': 2},
  'hero_hits': {'null': 13,
   'centaur_double_edge': 17,
   'centaur_hoof_stomp': 5,
   'centaur_stampede': 2},
  'damage': {'npc_dota_creep_goodguys_ranged': 194,
   'npc_dota_hero_antimage': 1414,
   'npc_dota_creep_goodguys_melee': 110,
   'npc_dota_creep_badguys_melee': 5062,
   'npc_dota_creep_badguys_ranged': 2595,
   'npc_dota_hero_centaur': 2496,
   'npc_dota_neutral_wildkin': 506,
   'npc_dota_neutral_satyr_hellcaller': 253,
   'npc_dota_neutral_enraged_wildkin': 253,
   'npc_dota_neutral_centaur_outrunner': 195,
   'npc_dota_neutral_centaur_khan': 338,
   'npc_dota_hero_enchantress': 1031,
   'npc_dota_badguys_siege': 381,
   'npc_dota_hero_clinkz': 155},
  'damage_taken': {'npc_dota_hero_enchantress': 2252,
   'npc_dota_hero_antimage': 1617,
   'npc_dota_creep_badguys_melee': 152,
   'npc_dota_hero_pudge': 48,
   'npc_dota_creep_badguys_ranged': 103,
   'npc_dota_hero_centaur': 2496,
   'npc_dota_neutral_centaur_outrunner': 13,
   'npc_dota_hero_clinkz': 392,
   'npc_dota_badguys_siege': 41},
  'damage_inflictor': {'null': 633,
   'centaur_double_edge': 1332,
   'centaur_hoof_stomp': 558,
   'centaur_stampede': 77},
  'runes': {'5': 4},
  'killed_by': {'npc_dota_hero_antimage': 1},
  'kill_streaks': {'3': 1},
  'multi_kills': {},
  'life_state': {'0': 1256, '1': 7, '2': 53},
  'healing': {'npc_dota_hero_centaur': 265},
  'damage_inflictor_received': {'null': 3473,
   'pudge_rot': 48,
   'clinkz_searing_arrows': 199,
   'antimage_mana_void': 226},
  'randomed': False,
  'pred_vict': False,
  'gold': 3394,
  'lh': 19,
  'xp': 3897,
  'x': 78,
  'y': 166,
  'hero_inventory': [{'id': 'item_stout_shield', 'cooldown': 0},
   {'id': 'item_soul_ring', 'cooldown': 0},
   {'id': 'item_tranquil_boots', 'num_charges': 1, 'cooldown': 12.9},
   {'id': 'item_chainmail', 'cooldown': 0}],
  'hero_stash': [],
  'health': 1352,
  'max_health': 1380,
  'max_mana': 386.938,
  'level': 8,
  'kills': 3,
  'deaths': 1,
  'assists': 2,
  'denies': 3,
  'nearby_creep_death_count': 66},
 {'player_slot': 2,
  'hero_id': 27,
  'hero_name': 'npc_dota_hero_shadow_shaman',
  'account_id_hash': '11acfafa05e08877a5be929c46810aa2',
  'ability_upgrades': [{'ability': 5080, 'time': 185, 'level': 1},
   {'ability': 5078, 'time': 413, 'level': 2},
   {'ability': 5078, 'time': 519, 'level': 3},
   {'ability': 5079, 'time': 624, 'level': 4}],
  'obs_placed': 3,
  'sen_placed': 1,
  'creeps_stacked': 2,
  'camps_stacked': 1,
  'rune_pickups': 4,
  'firstblood_claimed': 0,
  'teamfight_participation': 0.312,
  'towers_killed': 0,
  'roshans_killed': 0,
  'observers_placed': 3,
  'stuns': 11.965,
  'max_hero_hit': {'type': 'max_hero_hit',
   'time': 538.962,
   'max': True,
   'inflictor': 'shadow_shaman_ether_shock',
   'unit': 'npc_dota_hero_shadow_shaman',
   'key': 'npc_dota_hero_antimage',
   'value': 153,
   'slot': 2,
   'player_slot': 2},
  'times': [0, 60, 120, 180, 240, 300, 360, 420, 480, 540, 600],
  'gold_t': [41, 211, 302, 393, 530, 621, 712, 877, 968, 1533, 1809],
  'lh_t': [0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2],
  'dn_t': [0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2],
  'xp_t': [0, 19, 122, 184, 311, 467, 827, 1065, 1121, 1339, 1672],
  'obs_log': [{'time': -30.707,
    'tick': 4568,
    'type': 'obs_log',
    'key': '[148, 106]',
    'slot': 2,
    'x': 148,
    'y': 106,
    'z': 130,
    'entityleft': False,
    'ehandle': 11305543,
    'player_slot': 2},
   {'time': 383.933,
    'tick': 17009,
    'type': 'obs_log',
    'key': '[142, 106]',
    'slot': 2,
    'x': 142,
    'y': 106,
    'z': 130,
    'entityleft': False,
    'ehandle': 13960258,
    'player_slot': 2},
   {'time': 405.528,
    'tick': 17657,
    'type': 'obs_log',
    'key': '[168, 122]',
    'slot': 2,
    'x': 168,
    'y': 122,
    'z': 132,
    'entityleft': False,
    'ehandle': 6767488,
    'player_slot': 2}],
  'sen_log': [{'time': 114.266,
    'tick': 8917,
    'type': 'sen_log',
    'key': '[174, 90]',
    'slot': 2,
    'x': 174,
    'y': 90,
    'z': 130,
    'entityleft': False,
    'ehandle': 8914131,
    'player_slot': 2},
   {'time': 657.8,
    'tick': 25227,
    'type': 'sen_log',
    'key': '[158, 150]',
    'slot': 2,
    'x': 158,
    'y': 150,
    'z': 130,
    'entityleft': False,
    'ehandle': 5702769,
    'player_slot': 2}],
  'obs_left_log': [{'time': 336.945,
    'tick': 15599,
    'type': 'obs_left_log',
    'key': '[148, 106]',
    'slot': 2,
    'x': 148,
    'y': 106,
    'z': 130,
    'entityleft': True,
    'ehandle': 11305543,
    'player_slot': 2}],
  'sen_left_log': [{'time': 361.872,
    'tick': 16347,
    'type': 'sen_left_log',
    'key': '[174, 90]',
    'slot': 2,
    'x': 174,
    'y': 90,
    'z': 130,
    'entityleft': True,
    'ehandle': 8914131,
    'player_slot': 2}],
  'purchase_log': [{'time': -89.948, 'key': 'ward_dispenser'},
   {'time': -89.781, 'key': 'tango'},
   {'time': -89.781, 'key': 'ward_observer'},
   {'time': -89.781, 'key': 'ward_observer'},
   {'time': -89.781, 'key': 'ward_sentry'},
   {'time': -89.781, 'key': 'ward_dispenser'},
   {'time': -89.781, 'key': 'faerie_fire'},
   {'time': -89.781, 'key': 'clarity'},
   {'time': -89.781, 'key': 'tpscroll'},
   {'time': -73.381, 'key': 'ward_dispenser'},
   {'time': 74.042, 'key': 'ward_sentry'},
   {'time': 76.108, 'key': 'branches'},
   {'time': 76.242, 'key': 'branches'},
   {'time': 161.054, 'key': 'tpscroll'},
   {'time': 226.605, 'key': 'dust'},
   {'time': 344.343, 'key': 'ward_observer'},
   {'time': 344.476, 'key': 'ward_observer'},
   {'time': 444.285, 'key': 'tpscroll'},
   {'time': 446.451, 'key': 'magic_stick'},
   {'time': 483.042, 'key': 'enchanted_mango'},
   {'time': 569.888, 'key': 'boots'},
   {'time': 605.246, 'key': 'tome_of_knowledge'},
   {'time': 607.745, 'key': 'ward_observer'},
   {'time': 607.879, 'key': 'ward_observer'},
   {'time': 619.676, 'key': 'ward_dispenser'},
   {'time': 619.676, 'key': 'ward_sentry'},
   {'time': 646.269, 'key': 'magic_wand'}],
  'kills_log': [{'time': 538.962, 'key': 'npc_dota_hero_antimage'}],
  'buyback_log': [],
  'runes_log': [{'time': 43.343, 'key': 5},
   {'time': 50.211, 'key': 5},
   {'time': 482.176, 'key': 5},
   {'time': 497.839, 'key': 5}],
  'obs': {'142': {'106': 1}, '148': {'106': 1}, '168': {'122': 1}},
  'sen': {'158': {'150': 1}, '174': {'90': 1}},
  'actions': {'1': 4787,
   '2': 8,
   '3': 13,
   '4': 318,
   '5': 7,
   '6': 24,
   '7': 2,
   '8': 10,
   '9': 2,
   '10': 38,
   '11': 6,
   '15': 55,
   '16': 24,
   '19': 19,
   '27': 2},
  'pings': {'0': 5},
  'purchase': {'ward_dispenser': 4,
   'tango': 1,
   'ward_observer': 6,
   'ward_sentry': 3,
   'faerie_fire': 1,
   'clarity': 1,
   'tpscroll': 3,
   'branches': 2,
   'dust': 1,
   'magic_stick': 1,
   'enchanted_mango': 1,
   'boots': 1,
   'tome_of_knowledge': 1,
   'magic_wand': 1},
  'gold_reasons': {'0': 905, '1': -61, '11': 320, '12': 429, '13': 161},
  'xp_reasons': {'0': 702, '1': 436, '2': 1425},
  'killed': {'npc_dota_neutral_gnoll_assassin': 147,
   'npc_dota_creep_goodguys_ranged': 155,
   'npc_dota_hero_antimage': 153,
   'npc_dota_creep_badguys_ranged': 470},
  'item_uses': {'tango': 3,
   'ward_dispenser': 5,
   'ward_observer': 3,
   'faerie_fire': 1,
   'tpscroll': 2,
   'ward_sentry': 1,
   'clarity': 2,
   'magic_stick': 1,
   'tome_of_knowledge': 1},
  'ability_uses': {'shadow_shaman_shackles': 4,
   'shadow_shaman_ether_shock': 6,
   'shadow_shaman_voodoo': 1},
  'hero_hits': {'shadow_shaman_shackles': 109,
   'null': 8,
   'shadow_shaman_ether_shock': 3},
  'damage': {'npc_dota_hero_clinkz': 122,
   'npc_dota_hero_pudge': 473,
   'npc_dota_creep_badguys_melee': 2267,
   'npc_dota_neutral_gnoll_assassin': 293,
   'npc_dota_neutral_enraged_wildkin': 119,
   'npc_dota_creep_goodguys_melee': 75,
   'npc_dota_creep_goodguys_ranged': 155,
   'npc_dota_hero_antimage': 397,
   'npc_dota_hero_enchantress': 99,
   'npc_dota_neutral_centaur_khan': 271,
   'npc_dota_creep_badguys_ranged': 1017,
   'npc_dota_badguys_tower1_mid': 152,
   'npc_dota_badguys_tower2_mid': 311,
   'npc_dota_badguys_siege': 190},
  'damage_taken': {'npc_dota_hero_pudge': 890,
   'npc_dota_hero_clinkz': 258,
   'npc_dota_creep_badguys_melee': 114,
   'npc_dota_neutral_gnoll_assassin': 52,
   'npc_dota_neutral_enraged_wildkin': 87,
   'npc_dota_neutral_wildkin': 13,
   'npc_dota_hero_antimage': 76,
   'npc_dota_badguys_tower1_mid': 140,
   'npc_dota_creep_badguys_ranged': 28,
   'npc_dota_badguys_tower2_mid': 100},
  'damage_inflictor': {'shadow_shaman_shackles': 109,
   'null': 571,
   'shadow_shaman_ether_shock': 411},
  'runes': {'5': 4},
  'killed_by': {'npc_dota_hero_pudge': 1},
  'kill_streaks': {},
  'multi_kills': {},
  'life_state': {'0': 1306, '1': 2, '2': 8},
  'healing': {'npc_dota_hero_shadow_shaman': 115},
  'damage_inflictor_received': {'pudge_rot': 448,
   'null': 490,
   'clinkz_searing_arrows': 104,
   'pudge_meat_hook': 182},
  'randomed': False,
  'pred_vict': False,
  'gold': 2212,
  'lh': 4,
  'xp': 2561,
  'x': 156,
  'y': 146,
  'hero_inventory': [{'id': 'item_magic_wand', 'cooldown': 0},
   {'id': 'item_dust', 'num_charges': 2, 'cooldown': 0},
   {'id': 'item_boots', 'cooldown': 0},
   {'id': 'item_ward_dispenser',
    'num_charges': 2,
    'num_secondary_charges': 1,
    'cooldown': 0},
   {'id': 'item_tpscroll', 'num_charges': 1, 'cooldown': 0}],
  'hero_stash': [],
  'health': 710,
  'max_health': 860,
  'max_mana': 530.938,
  'level': 6,
  'kills': 1,
  'deaths': 1,
  'assists': 4,
  'denies': 2,
  'nearby_creep_death_count': 61},
 {'player_slot': 3,
  'hero_id': 63,
  'hero_name': 'npc_dota_hero_weaver',
  'account_id_hash': '1c2500195e6ab646fc9371344724aa77',
  'ability_upgrades': [{'ability': 5290, 'time': 192, 'level': 1},
   {'ability': 5291, 'time': 262, 'level': 2},
   {'ability': 5290, 'time': 292, 'level': 3},
   {'ability': 5289, 'time': 327, 'level': 4},
   {'ability': 5290, 'time': 399, 'level': 5},
   {'ability': 5292, 'time': 450, 'level': 6},

In [12]:
def attach_player_feature(raw_features, df_matches, feature: str, overwrite=False):
    """
    Добавляет к raw_features фичу по игрокам из df_matches["players"].
    Колонки будут вида r1_<feature>, ..., r5_<feature>, d1_<feature>, ..., d5_<feature>.
    Джойн по match_id_hash.
    
    overwrite=False не трогает уже существующие колонки этого feature.
    """

    def extract_for_match(players):
        row = {}
        for p in players:
            slot = p.get("player_slot")
            if slot is None:
                continue

            if slot < 128:
                prefix = "r"
                idx = slot + 1
            else:
                prefix = "d"
                idx = slot - 128 + 1

            col_name = f"{prefix}{idx}_{feature}"
            row[col_name] = p.get(feature)

        return pd.Series(row)

    tmp = df_matches[["match_id_hash", "players"]].copy()
    features_df = tmp["players"].apply(extract_for_match)
    tmp = pd.concat([tmp[["match_id_hash"]], features_df], axis=1)

 
    left = raw_features.set_index("match_id_hash")
    right = tmp.set_index("match_id_hash")

    if not overwrite:
        new_cols = [c for c in right.columns if c not in left.columns]
        right = right[new_cols]

    result = left.join(right, how="left").reset_index()
    return result

In [13]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="pred_vict"
)

In [14]:
def fix_hero_names_inplace(df):
    """
    In-place убирает префикс 'npc_dota_hero_' из колонок с именами героев.
    Правит все колонки, которые заканчиваются на '_hero_name'.
    
    Возвращает df для удобства, но изменяет его на месте.
    """
    hero_cols = [c for c in df.columns if c.endswith("_hero_name")]

    for col in hero_cols:
        df[col] = (
            df[col]
            .astype("string")
            .str.replace(r"^npc_dota_hero_", "", regex=True)
        )

    return df

In [15]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="hero_name"
)

In [16]:
raw_features = fix_hero_names_inplace(raw_features)

In [17]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="damage"
)

In [18]:
raw_features.head()

,match_id_hash,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed,r1_pred_vict,r2_pred_vict,r3_pred_vict,r4_pred_vict,r5_pred_vict,d1_pred_vict,d2_pred_vict,d3_pred_vict,d4_pred_vict,d5_pred_vict,r1_hero_name,r2_hero_name,r3_hero_name,r4_hero_name,r5_hero_name,d1_hero_name,d2_hero_name,d3_hero_name,d4_hero_name,d5_hero_name,r1_damage,r2_damage,r3_damage,r4_damage,r5_damage,d1_damage,d2_damage,d3_damage,d4_damage,d5_damage
0,a400b8f29dece5f4d266f49f1ae2e98a,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.0,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,True,True,False,False,False,nevermore,brewmaster,pudge,huskar,lycan,phantom_lancer,windrunner,night_stalker,ogre_magi,tinker,"{'npc_dota_creep_goodguys_melee': 92, 'npc_dot...","{'npc_dota_creep_goodguys_ranged': 113, 'npc_d...","{'npc_dota_hero_ogre_magi': 16, 'npc_dota_hero...","{'npc_dota_creep_badguys_melee': 497, 'npc_dot...","{'npc_dota_neutral_satyr_soulstealer': 1286, '...","{'npc_dota_creep_badguys_melee': 695, 'npc_dot...","{'npc_dota_hero_huskar': 402, 'npc_dota_creep_...","{'npc_dota_hero_huskar': 635, 'npc_dota_creep_...",{'npc_dota_hero_pudge': 868},"{'npc_dota_hero_nevermore': 704, 'npc_dota_cre..."
1,b9c57c450ce74a2af79c9ce96fac144d,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.5,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,False,False,False,False,False,razor,centaur,shadow_shaman,weaver,naga_siren,enchantress,pudge,antimage,clinkz,visage,"{'npc_dota_hero_pudge': 2298, 'npc_dota_hero_c...","{'npc_dota_creep_goodguys_ranged': 194, 'npc_d...","{'npc_dota_hero_clinkz': 122, 'npc_dota_hero_p...","{'npc_dota_creep_goodguys_ranged': 622, 'npc_d...","{'npc_dota_hero_clinkz': 1021, 'npc_dota_hero_...","{'npc_dota_hero_centaur': 2252, 'npc_dota_neut...","{'npc_dota_hero_shadow_shaman': 890, 'npc_dota...","{'npc_dota_hero_centaur': 1617, 'npc_dota_cree...","{'npc_dota_hero_shadow_shaman': 258, 'npc_dota...","{'npc_dota_creep_goodguys_melee': 903, 'npc_do..."
2,6db558535151ea18ca70a6892197db41,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.0,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skywrath_mage,rattletrap,phantom_assassin,dragon_knight,furion,sven,spectre,viper,venomancer,storm_spirit,{},{},{'npc_dota_hero_spectre': 70},{},{},{},{'npc_dota_hero_phantom_assassin': 68},{},{},{}
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.0,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.00,0,0,2,0,False,False,False,False,False,False,False,False,True,False,pudge,bristleback,skywrath_mage,lion,faceless_void,sven,shredder,juggernaut,doom_bringer,rubick,"{'npc_dota_hero_pudge': 918, 'npc_dota_hero_do...","{'npc_dota_creep_badguys_melee': 6665, 'npc_do...","{'npc_dota_hero_shredder': 4304, 'npc_dota_cre...","{'npc_dota_hero_doom_bringer': 710, 'npc_dota_...","{'npc_dota_creep_badguys_melee': 4949, 'npc_do...","{'npc_dota_neutral_satyr_trickster': 2710, 'np...","{'npc_dota_creep_goodguys_melee': 5060, 'npc_d...","{'npc_dota_creep_goodguys_melee': 6142, 'npc_d...","{'npc_dota_creep_goodguys_melee': 960, 'npc_do...","{'npc_dota_hero_bristleback': 1577, 'npc_dota_..."
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.5,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.25,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skeleton_king,doom_bringer,shadow_shaman,legion_commander,batrider,kunkka,zuus,sniper,gyrocopter,antimage,"{'npc_dota_hero_antimage': 418, 'npc_dota_cree...","{'npc_dota_hero_antimage': 766, 'npc_dota_cree...","{'npc_dota_hero_gyrocopter': 168, 'npc_dota_cr...","{'npc_dota_hero_antimage': 248, 'npc_dota_cree...","{'npc_dota_creep_badguys_melee': 4301, 'npc_do...","{'npc_dota_hero_legion_commander': 134, 'npc_d...","{'npc_dota_creep_goodguys_melee': 4583, 'npc_d...","{'npc_dota_hero_shadow_shaman': 1521, 'npc_dot...","{'npc_dota_hero_shadow_shaman': 447, 'npc_dota...","{'npc_dota_hero_doom_bringer': 672, 'npc_dota_..."

In [19]:
def add_damage_features(df):
    """
    Ищет колонки, заканчивающиеся на _damage, где значения это dict.
    Добавляет
    1) <player>_total_damage  сумма всего урона
    2) <player>_hero_damage   сумма урона только по героям
    
    """

    damage_cols = [c for c in df.columns if c.endswith("_damage")]

    def total_damage(d):
        if not isinstance(d, dict):
            return 0
        return sum(d.values())

    def hero_damage(d):
        if not isinstance(d, dict):
            return 0
        return sum(v for k, v in d.items() if isinstance(k, str) and k.startswith("npc_dota_hero_"))

    for col in damage_cols:
        player = col.replace("_damage", "")  

        df[f"{player}_total_damage"] = df[col].apply(total_damage)
        df[f"{player}_hero_damage"] = df[col].apply(hero_damage)

    return df

In [20]:
raw_features = add_damage_features(raw_features)
raw_features.head()

,match_id_hash,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed,r1_pred_vict,r2_pred_vict,r3_pred_vict,r4_pred_vict,r5_pred_vict,d1_pred_vict,d2_pred_vict,d3_pred_vict,d4_pred_vict,d5_pred_vict,r1_hero_name,r2_hero_name,r3_hero_name,r4_hero_name,r5_hero_name,d1_hero_name,d2_hero_name,d3_hero_name,d4_hero_name,d5_hero_name,r1_damage,r2_damage,r3_damage,r4_damage,r5_damage,d1_damage,d2_damage,d3_damage,d4_damage,d5_damage,r1_total_damage,r1_hero_damage,r2_total_damage,r2_hero_damage,r3_total_damage,r3_hero_damage,r4_total_damage,r4_hero_damage,r5_total_damage,r5_hero_damage,d1_total_damage,d1_hero_damage,d2_total_damage,d2_hero_damage,d3_total_damage,d3_hero_damage,d4_total_damage,d4_hero_damage,d5_total_damage,d5_hero_damage
0,a400b8f29dece5f4d266f49f1ae2e98a,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.0,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,True,True,False,False,False,nevermore,brewmaster,pudge,huskar,lycan,phantom_lancer,windrunner,night_stalker,ogre_magi,tinker,"{'npc_dota_creep_goodguys_melee': 92, 'npc_dot...","{'npc_dota_creep_goodguys_ranged': 113, 'npc_d...","{'npc_dota_hero_ogre_magi': 16, 'npc_dota_hero...","{'npc_dota_creep_badguys_melee': 497, 'npc_dot...","{'npc_dota_neutral_satyr_soulstealer': 1286, '...","{'npc_dota_creep_badguys_melee': 695, 'npc_dot...","{'npc_dota_hero_huskar': 402, 'npc_dota_creep_...","{'npc_dota_hero_huskar': 635, 'npc_dota_creep_...",{'npc_dota_hero_pudge': 868},"{'npc_dota_hero_nevermore': 704, 'npc_dota_cre...",1287,459,1327,0,32,32,1000,457,5090,0,3521,224,1977,402,747,635,868,868,2332,820
1,b9c57c450ce74a2af79c9ce96fac144d,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.5,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,False,False,False,False,False,razor,centaur,shadow_shaman,weaver,naga_siren,enchantress,pudge,antimage,clinkz,visage,"{'npc_dota_hero_pudge': 2298, 'npc_dota_hero_c...","{'npc_dota_creep_goodguys_ranged': 194, 'npc_d...","{'npc_dota_hero_clinkz': 122, 'npc_dota_hero_p...","{'npc_dota_creep_goodguys_ranged': 622, 'npc_d...","{'npc_dota_hero_clinkz': 1021, 'npc_dota_hero_...","{'npc_dota_hero_centaur': 2252, 'npc_dota_neut...","{'npc_dota_hero_shadow_shaman': 890, 'npc_dota...","{'npc_dota_hero_centaur': 1617, 'npc_dota_cree...","{'npc_dota_hero_shadow_shaman': 258, 'npc_dota...","{'npc_dota_creep_goodguys_melee': 903, 'npc_do...",20882,4656,14983,5096,5941,1091,21394,4708,6565,1912,13575,2871,9643,4141,13855,2054,7437,3071,2308,926
2,6db558535151ea18ca70a6892197db41,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.0,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skywrath_mage,rattletrap,phantom_assassin,dragon_knight,furion,sven,spectre,viper,venomancer,storm_spirit,{},{},{'npc_dota_hero_spectre': 70},{},{},{},{'npc_dota_hero_phantom_assassin': 68},{},{},{},0,0,0,0,70,70,0,0,0,0,0,0,68,68,0,0,0,0,0,0
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.0,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.00,0,0,2,0,False,False,False,False,False,False,False,False,True,False,pudge,bristleback,skywrath_mage,lion,faceless_void,sven,shredder,juggernaut,doom_bringer,rubick,"{'npc_dota_hero_pudge': 918, 'npc_dota_hero_do...","{'npc_dota_creep_badguys_melee': 6665, 'npc_do...","{'npc_dota_hero_shredder': 4304, 'npc_dota_cre...","{'npc_dota_hero_doom_bringer': 710, 'npc_dota_...","{'npc_dota_creep_badguys_melee': 4949, 'npc_do...","{'npc_dota_neutral_satyr_trickster': 2710, 'np...","{'npc_dota_creep_goodguys_melee': 5060, 'npc_d...","{'npc_dota_creep_goodguys_melee': 6142, 'npc_d...","{'npc_dota_creep_goodguys_melee': 960, 'npc_do...","{'npc_dota_hero_bristleback': 1577, 'npc_dota_...",3350,3130,19497,6101,14140,4468,1819,710,11575,1133,36761,0,8913,2087,13392,2633,6010,1952,3955,1665
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.5,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.25,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skeleton_king,doom_bringer,shadow_shaman,legion_commander,batrider,kunkka,zuus,sniper,gyrocopter,antimage,"{'npc_dota_hero_antimage': 418, 'npc_dota_cree...","{'npc_dota_hero_antimage': 766, 'npc_dota_cree...","{'npc_dota_hero_gyrocopter': 168, 'npc_dota_cr...","{'npc_dota_hero_antimage': 248, 'npc_dota_cree...","{'npc_dota_creep_badguys_melee': 4301, 'npc_do...","{'npc_dota_hero_legion_commander': 134, 'npc_d...","{'npc_dota_creep_goodguys_melee': 4583, 'npc_d...","{'npc_dota_hero_shadow_shaman': 1521, 'npc_dot...","{'npc_dota_hero_shadow_shaman': 447, 'npc_dota...","{'npc_dota_hero_doom_bringer': 672, 'npc_dota_...",4547,655,8519,1534,9178,1299,8946,1523,6723,929,11833,3471,9431,3098,13832,1521,8388,2858,10739,1003

In [21]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="gold_t"
)

In [22]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="xp_t"
)

In [23]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="lh_t"
)

In [24]:
raw_features = attach_player_feature(raw_features, df_json_matches,
    feature="dn_t"
)

In [25]:
raw_features.head()

,match_id_hash,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed,r1_pred_vict,r2_pred_vict,r3_pred_vict,r4_pred_vict,r5_pred_vict,d1_pred_vict,d2_pred_vict,d3_pred_vict,d4_pred_vict,d5_pred_vict,r1_hero_name,r2_hero_name,r3_hero_name,r4_hero_name,r5_hero_name,d1_hero_name,d2_hero_name,d3_hero_name,d4_hero_name,d5_hero_name,r1_damage,r2_damage,r3_damage,r4_damage,r5_damage,d1_damage,d2_damage,d3_damage,d4_damage,d5_damage,r1_total_damage,r1_hero_damage,r2_total_damage,r2_hero_damage,r3_total_damage,r3_hero_damage,r4_total_damage,r4_hero_damage,r5_total_damage,r5_hero_damage,d1_total_damage,d1_hero_damage,d2_total_damage,d2_hero_damage,d3_total_damage,d3_hero_damage,d4_total_damage,d4_hero_damage,d5_total_damage,d5_hero_damage,r1_gold_t,r2_gold_t,r3_gold_t,r4_gold_t,r5_gold_t,d1_gold_t,d2_gold_t,d3_gold_t,d4_gold_t,d5_gold_t,r1_xp_t,r2_xp_t,r3_xp_t,r4_xp_t,r5_xp_t,d1_xp_t,d2_xp_t,d3_xp_t,d4_xp_t,d5_xp_t,r1_lh_t,r2_lh_t,r3_lh_t,r4_lh_t,r5_lh_t,d1_lh_t,d2_lh_t,d3_lh_t,d4_lh_t,d5_lh_t,r1_dn_t,r2_dn_t,r3_dn_t,r4_dn_t,r5_dn_t,d1_dn_t,d2_dn_t,d3_dn_t,d4_dn_t,d5_dn_t
0,a400b8f29dece5f4d266f49f1ae2e98a,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.0,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,True,True,False,False,False,nevermore,brewmaster,pudge,huskar,lycan,phantom_lancer,windrunner,night_stalker,ogre_magi,tinker,"{'npc_dota_creep_goodguys_melee': 92, 'npc_dot...","{'npc_dota_creep_goodguys_ranged': 113, 'npc_d...","{'npc_dota_hero_ogre_magi': 16, 'npc_dota_hero...","{'npc_dota_creep_badguys_melee': 497, 'npc_dot...","{'npc_dota_neutral_satyr_soulstealer': 1286, '...","{'npc_dota_creep_badguys_melee': 695, 'npc_dot...","{'npc_dota_hero_huskar': 402, 'npc_dota_creep_...","{'npc_dota_hero_huskar': 635, 'npc_dota_creep_...",{'npc_dota_hero_pudge': 868},"{'npc_dota_hero_nevermore': 704, 'npc_dota_cre...",1287,459,1327,0,32,32,1000,457,5090,0,3521,224,1977,402,747,635,868,868,2332,820,"[1, 91, 356]","[1, 91, 262]","[1, 91, 182]","[1, 169, 260]","[1, 91, 281]","[1, 331, 738]","[1, 251, 561]","[1, 251, 342]","[1, 251, 342]","[1, 425, 680]","[0, 107, 387]","[0, 38, 318]","[0, 0, 73]","[0, 202, 301]","[0, 38, 238]","[0, 85, 431]","[0, 58, 445]","[0, 41, 229]","[0, 85, 329]","[0, 240, 616]","[0, 0, 4]","[0, 0, 2]","[0, 0, 0]","[0, 2, 2]","[0, 0, 5]","[0, 2, 9]","[0, 0, 5]","[0, 0, 0]","[0, 0, 0]","[0, 4, 8]","[0, 0, 0]","[0, 0, 2]","[0, 0, 0]","[0, 1, 1]","[0, 0, 0]","[0, 4, 12]","[0, 1, 4]","[0, 0, 1]","[0, 0, 0]","[0, 0, 0]"
1,b9c57c450ce74a2af79c9ce96fac144d,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.5,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,False,False,False,False,False,razor,centaur,shadow_shaman,weaver,naga_siren,enchantress,pudge,antimage,clinkz,visage,"{'npc_dota_hero_pudge': 2298, 'npc_dota_hero_c...","{'npc_dota_creep_goodguys_ranged': 194, 'npc_d...","{'npc_dota_hero_clinkz': 122, 'npc_dota_hero_p...","{'npc_dota_creep_goodguys_ranged': 622, 'npc_d...","{'npc_dota_hero_clinkz': 1021, 'npc_dota_hero_...","{'npc_dota_hero_centaur': 2252, 'npc_dota_neut...","{'npc_dota_hero_shadow_shaman': 890, 'npc_dota...","{'npc_dota_hero_centaur': 1617, 'npc_dota_cree...","{'npc_dota_hero_shadow_shaman': 258, 'npc_dota...","{'npc_dota_creep_goodguys_melee': 903, 'npc_do...",20882,4656,14983,5096,5941,1091,21394,4708,6565,1912,13575,2871,9643,4141,13855,2054,7437,3071,2308,926,"[41, 819, 1196, 1467, 1839, 2356, 2812, 3444, ...","[41, 211, 340, 589, 762, 1209, 1579, 1803, 240...","[41, 211, 302, 393, 530, 621, 712, 877, 968, 1...","[41, 292, 750, 922, 1644, 1875, 2042, 2623, 28...","[41, 541, 632, 723, 814, 1100, 1406, 1769, 186...","[1, 131, 295, 458, 592, 814, 1002, 1194, 1460,...","[1, 426, 617, 735, 908, 1095, 1383, 1473, 1564...","[1, 225, 396, 742, 1223, 1707, 1798, 2077, 231...","[1, 182, 315, 543, 766, 1135, 1226, 1500, 1632...","[1, 131, 379, 647, 738, 881, 972, 1062, 1153, ...","[0, 166, 395, 702, 1038, 1497, 1759, 2387, 282...","[0, 57, 452, 1022, 1103, 1641, 1991, 2388, 306...","[0, 19, 122, 184, 311, 467, 827, 1065, 1121, 1...","[0, 188, 968, 1291, 2209, 2480, 2695, 3298, 34...","[0, 166, 395, 631, 687, 1023, 1582, 1855, 2009...","[0, 0, 183, 384, 528, 1025, 1025, 1391, 1973, ...","[0, 30, 254, 444, 615, 843, 1209, 1329, 1500, ...","[0, 197, 532, 698, 1368, 1719, 1902, 2000, 224...","[0, 87, 458, 631, 997, 1189, 1317, 1656, 1884,...","[0, 188, 510, 945, 1136, 1136, 1136, 1136, 113...","[0, 2, 8, 12, 18, 22, 25, 33, 39, 45, 52]","[0, 0, 1, 5, 8, 9, 10, 13, 15, 17, 19]","[0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]","[0, 2, 4, 6, 9, 12, 14, 21, 25, 28, 33]","[0, 0, 0, 0, 0, 5, 8, 8, 8, 8, 13]","[0, 0, 4, 8, 11, 11, 12, 14, 18, 22, 22]","[0, 0, 2, 4, 6, 8, 12, 12, 12, 12, 12]","[0, 2, 4, 7, 15, 15, 15, 18, 25, 27, 27]","[0, 0, 1, 1, 4, 6, 6, 9, 10, 11, 16]","[0, 0, 4, 8, 8, 8, 8, 8, 8, 8, 8]","[0, 0, 1, 5, 5, 7, 7, 7, 7, 7, 7]","[0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3]","[0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2]","[0, 1, 2, 2, 4, 6, 7, 8, 9, 11, 12]","[0, 0, 0, 1, 1, 2, 3, 3, 3, 3, 4]","[0, 0, 0, 0, 0, 1, 1, 1, 2, 3, 3]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 1, 3, 7, 7, 7, 7, 7, 7, 7]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3]","[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]"
2,6db558535151ea18ca70a6892197db41,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.0,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skywrath_mage,rattletrap,phantom_assassin,dragon_knight,furion,sven,spectre,viper,venomancer,storm_spirit,{},{},{'npc_dota_hero_spectre': 70},{},{},{},{'npc_dota_hero_phantom_assassin': 68},{},{},{},0,0,0,0,70,70,0,0,0,0,0,0,68,68,0,0,0,0,0,0,[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0]
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.0,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.00,0,0,2,0,False,False,False,False,False,False,False,False,True,False,pudge,bristleback,skywrath_mage,lion,faceless_void,sven,shredder,juggernaut,doom_bringer,rubick,"{'npc_dota_hero_pudge': 918, 'npc_dota_hero_do...","{'npc_dota_creep_badguys_melee': 6665, 'npc_do...","{'npc_dota_hero_shredder': 4304, 'npc_dota_cre...","{'npc_dota_hero_doom_bringer': 710, 'npc_dota_...","{'npc_dota_creep_badguys_melee': 4949, 'npc_do...","{'npc_dota_neutral_satyr_trickster': 2710, 'np...","{'npc_dota_creep_goodguys_melee': 5060, 'npc_d...","{'npc_dota_creep_goodguys_melee': 6142, 'npc_d...","{'npc_dota_creep_goodguys_melee': 960, 'npc_do...","{'npc_dota_hero_bristleback': 1577, 'npc_dota_...",3350,3130,19497,6101,14140,4468,1819,710,11575,1133,36761,0,8913,2087,13392,2633,6010,1952,3955,1665,"[81, 171, 262, 524, 615, 820, 911, 1105, 1196,...","[81, 171, 499, 658, 924, 1285, 1416, 1968, 213...","[81, 274, 540, 1239, 1455, 2132, 2398, 2706, 3...","[81, 171, 262, 464, 555, 885, 976, 1092, 1272,...","[81, 288, 681, 992, 1374, 1620, 2029, 2418, 26...","[104, 194, 424, 658, 828, 1258, 1491, 1917, 22...","[104, 315, 579, 710, 1014, 1148, 1379, 1865, 2...","[104, 272, 547, 892, 1321, 1602, 1989, 2331, 2...","[104, 262, 427, 625, 821, 1031, 1180, 1539, 17...","[104, 194, 285, 376, 561, 728, 819, 910, 1001,...","[0, 77, 206, 352, 422, 611, 701, 970, 1177, 1311]","[0, 114, 720, 1153, 1539, 2050, 2121, 2548, 28...","[0, 240, 776, 1231, 1616, 2282, 2750, 3318, 36...","[0, 42, 233, 372, 504, 698, 768, 984, 1095, 1194]","[0, 77, 410, 849, 1209, 1460, 1805, 2204, 2817...","[0, 0, 336, 506, 634, 1056, 1283, 1533, 1960, ...","[0, 240, 719, 1028, 1596, 1933, 2275, 2772, 32...","[0, 118, 354, 708, 1096, 1377, 1699, 2010, 219...","[0, 57, 172, 266, 499, 822, 908, 1250, 1504, 1...","[0, 118, 354, 463, 761, 990, 1312, 1494, 1676,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 5, 7, 10, 16, 17, 24, 26, 30]","[0, 2, 6, 11, 14, 20, 24, 27, 33, 37]","[0, 0, 0, 2, 2, 2, 2, 2, 2, 2]","[0, 3, 10, 15, 22, 25, 32, 39, 42, 51]","[0, 0, 7, 10, 12, 24, 29, 36, 47, 56]","[0, 3, 7, 8, 13, 14, 17, 20, 23, 23]","[0, 2, 6, 12, 19, 23, 30, 34, 39, 40]","[0, 1, 3, 4, 6, 8, 9, 12, 15, 15]","[0, 0, 0, 0, 2, 2, 2, 2, 2, 2]","[0, 0, 1, 1, 1, 1, 1, 1, 1, 1]","[0, 0, 0, 0, 1, 2, 2, 2, 2, 2]","[0, 0, 2, 2, 2, 4, 7, 7, 8, 8]","[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]","[0, 2, 9, 12, 14, 15, 17, 21, 23, 28]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 2, 2, 4, 4, 4, 4, 5, 5]","[0, 0, 0, 0, 0, 1, 2, 3, 4, 4]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 1, 1, 1, 1]"
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.5,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.25,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skeleton_king,doom_bringer,shadow_shaman,legion_commander,batrider,kunkka,zuus,sniper,gyrocopter,antimage,"{'npc_dota_hero_antimage': 418, 'npc_dota_cree...","{'npc_dota_hero_antimage': 766, 'npc_dota_cree...","{'npc_dota_hero_gyrocopter': 168, 'npc_dota_cr...","{'npc_dota_hero_antimage': 248, 'npc_dota_cree...","{'npc_dota_creep_badguys_melee': 4301, 'npc_do...","{'npc_dota_hero_legion_commander': 134, 'npc_d...","{'npc_dota_creep_goodguys_melee': 4583, 'npc_d...","{'npc_dota_hero_shadow_shaman': 1521, 'npc_dot...","{'npc_dota_hero_shadow_shaman': 447, 'npc_dota...","{'npc_dota_hero_doom_bringer': 672, 'npc_dota_...",4547,655,8519,1534,9178,1299,8946,1523,6723,929,11833,3471,9431,3098,13832,1521,8388,2858,10739,1003,"[21, 191, 282, 481, 610, 820, 988, 1355]","[283, 555, 782, 1030, 1186, 1372, 1488, 1645]","[1, 211, 345, 573, 664, 854, 1024, 1115]","[27, 238, 504, 595, 781, 1149, 1374, 1675]","[1, 171, 356, 515, 700, 944, 1174, 1438]","[1, 210, 339, 468, 823, 1030, 1202, 1293]","[1, 214, 456, 667, 758, 890, 1180, 1326]","[86, 431, 686, 957, 1183, 1457, 1670, 2173]","[165, 389, 556, 981, 1115, 1248, 1431, 1648]","[1, 312, 542, 905, 1217, 1442, 1756, 2077]","[20, 66, 247, 365, 519, 789, 887, 1295]","[20, 80, 278, 524, 678, 1062, 1229, 1511]","[0, 297, 777, 1214, 1694, 2048, 2856, 2856]","[20, 148, 384, 384, 684, 1042, 1343, 1823]","[0, 147, 383, 623, 797, 915, 1090, 1090]","[0, 133, 384, 749, 1053, 1205, 1499, 1624]","[0, 118, 305, 636, 844, 1195, 1439, 1617]","[30, 327, 807, 1301, 1838, 2387, 2684, 3304]","[30, 148, 266, 569, 777, 957, 1236, 1623]","[0, 133, 384, 608, 912, 1235, 1529, 1753]","[0, 0, 0, 1, 2, 3, 5, 9]","[0, 2, 5, 8, 9, 11, 11, 12]","[0, 1, 2, 5, 5, 7, 9, 9]","[0, 1, 5, 5, 7, 13, 16, 21]","[0, 0, 2, 2, 4, 4, 7, 7]","[0, 1, 2, 3, 5, 6, 8, 8]","[0, 1, 4, 7, 7, 8, 9, 10]","[0, 4, 8, 12, 15, 19, 22, 31]","[0, 1, 3, 4, 5, 6, 9, 12]","[0, 3, 6, 12, 16, 19, 23, 28]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 1, 1, 1, 1]","[0, 0, 0, 1, 1, 1, 1, 2]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 2, 4, 5, 6, 6, 8, 8]"

In [26]:
def create_features(df):
    # какие характеристики суммируем для каждой команды
    metrics = ["gold", "kills", "deaths", "level", "hero_damage", "total_damage"]

    for m in metrics:
        # radiant
        r_cols = [f"r{i}_{m}" for i in range(1, 6)]
        df[f"radiant_total_{m}"] = df[r_cols].sum(axis=1)

        # dire
        d_cols = [f"d{i}_{m}" for i in range(1, 6)]
        df[f"dire_total_{m}"] = df[d_cols].sum(axis=1)

        # разница
        df[f"radiant_{m}_advantage"] = df[f"radiant_total_{m}"] - df[f"dire_total_{m}"]

    # итоговая метрика убийств и смертей
    df["total_kills_deaths"] = (
        df["radiant_total_kills"] +
        df["dire_total_kills"] +
        df["radiant_total_deaths"] +
        df["dire_total_deaths"]
    )
    
    return df

In [ ]:
raw_features = create_features(raw_features)

In [30]:
raw_features.shape

(39675, 355)

In [29]:
raw_features.head()

,match_id_hash,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed,r1_pred_vict,r2_pred_vict,r3_pred_vict,r4_pred_vict,r5_pred_vict,d1_pred_vict,d2_pred_vict,d3_pred_vict,d4_pred_vict,d5_pred_vict,r1_hero_name,r2_hero_name,r3_hero_name,r4_hero_name,r5_hero_name,d1_hero_name,d2_hero_name,d3_hero_name,d4_hero_name,d5_hero_name,r1_damage,r2_damage,r3_damage,r4_damage,r5_damage,d1_damage,d2_damage,d3_damage,d4_damage,d5_damage,r1_total_damage,r1_hero_damage,r2_total_damage,r2_hero_damage,r3_total_damage,r3_hero_damage,r4_total_damage,r4_hero_damage,r5_total_damage,r5_hero_damage,d1_total_damage,d1_hero_damage,d2_total_damage,d2_hero_damage,d3_total_damage,d3_hero_damage,d4_total_damage,d4_hero_damage,d5_total_damage,d5_hero_damage,r1_gold_t,r2_gold_t,r3_gold_t,r4_gold_t,r5_gold_t,d1_gold_t,d2_gold_t,d3_gold_t,d4_gold_t,d5_gold_t,r1_xp_t,r2_xp_t,r3_xp_t,r4_xp_t,r5_xp_t,d1_xp_t,d2_xp_t,d3_xp_t,d4_xp_t,d5_xp_t,r1_lh_t,r2_lh_t,r3_lh_t,r4_lh_t,r5_lh_t,d1_lh_t,d2_lh_t,d3_lh_t,d4_lh_t,d5_lh_t,r1_dn_t,r2_dn_t,r3_dn_t,r4_dn_t,r5_dn_t,d1_dn_t,d2_dn_t,d3_dn_t,d4_dn_t,d5_dn_t,radiant_total_gold,dire_total_gold,radiant_gold_advantage,radiant_total_kills,dire_total_kills,radiant_kills_advantage,radiant_total_deaths,dire_total_deaths,radiant_deaths_advantage,radiant_total_level,dire_total_level,radiant_level_advantage,radiant_total_hero_damage,dire_total_hero_damage,radiant_hero_damage_advantage,radiant_total_total_damage,dire_total_total_damage,radiant_total_damage_advantage,total_kills_deaths
0,a400b8f29dece5f4d266f49f1ae2e98a,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.0,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,True,True,False,False,False,nevermore,brewmaster,pudge,huskar,lycan,phantom_lancer,windrunner,night_stalker,ogre_magi,tinker,"{'npc_dota_creep_goodguys_melee': 92, 'npc_dot...","{'npc_dota_creep_goodguys_ranged': 113, 'npc_d...","{'npc_dota_hero_ogre_magi': 16, 'npc_dota_hero...","{'npc_dota_creep_badguys_melee': 497, 'npc_dot...","{'npc_dota_neutral_satyr_soulstealer': 1286, '...","{'npc_dota_creep_badguys_melee': 695, 'npc_dot...","{'npc_dota_hero_huskar': 402, 'npc_dota_creep_...","{'npc_dota_hero_huskar': 635, 'npc_dota_creep_...",{'npc_dota_hero_pudge': 868},"{'npc_dota_hero_nevermore': 704, 'npc_dota_cre...",1287,459,1327,0,32,32,1000,457,5090,0,3521,224,1977,402,747,635,868,868,2332,820,"[1, 91, 356]","[1, 91, 262]","[1, 91, 182]","[1, 169, 260]","[1, 91, 281]","[1, 331, 738]","[1, 251, 561]","[1, 251, 342]","[1, 251, 342]","[1, 425, 680]","[0, 107, 387]","[0, 38, 318]","[0, 0, 73]","[0, 202, 301]","[0, 38, 238]","[0, 85, 431]","[0, 58, 445]","[0, 41, 229]","[0, 85, 329]","[0, 240, 616]","[0, 0, 4]","[0, 0, 2]","[0, 0, 0]","[0, 2, 2]","[0, 0, 5]","[0, 2, 9]","[0, 0, 5]","[0, 0, 0]","[0, 0, 0]","[0, 4, 8]","[0, 0, 0]","[0, 0, 2]","[0, 0, 0]","[0, 1, 1]","[0, 0, 0]","[0, 4, 12]","[0, 1, 4]","[0, 0, 1]","[0, 0, 0]","[0, 0, 0]",2037,3948,-1911,0,1,-1,1,0,1,9,13,-4,948,2949,-2001,8736,9445,-709,2
1,b9c57c450ce74a2af79c9ce96fac144d,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.5,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,False,False,False,False,False,razor,centaur,shadow_shaman,weaver,naga_siren,enchantress,pudge,antimage,clinkz,visage,"{'npc_dota_hero_pudge': 2298, 'npc_dota_hero_c...","{'npc_dota_creep_goodguys_ranged': 194, 'npc_d...","{'npc_dota_hero_clinkz': 122, 'npc_dota_hero_p...","{'npc_dota_creep_goodguys_ranged': 622, 'npc_d...","{'npc_dota_hero_clinkz': 1021, 'npc_dota_hero_...","{'npc_dota_hero_centaur': 2252, 'npc_dota_neut...","{'npc_dota_hero_shadow_shaman': 890, 'npc_dota...","{'npc_dota_hero_centaur': 1617, 'npc_dota_cree...","{'npc_dota_hero_shadow_shaman': 258, 'npc_dota...","{'npc_dota_creep_goodguys_melee': 903, 'npc_do...",20882,4656,14983,5096,5941,1091,21394,4708,6565,1912,13575,2871,9643,4141,13855,2054,7437,3071,2308,926,"[41, 819, 1196, 1467, 1839, 2356, 2812, 3444, ...","[41, 211, 340, 589, 762, 1209, 1579, 1803, 240...","[41, 211, 302, 393, 530, 621, 712, 877, 968, 1...","[41, 292, 750, 922, 1644, 1875, 2042, 2623, 28...","[41, 541, 632, 723, 814, 1100, 1406, 1769, 186...","[1, 131, 295, 458, 592, 814, 1002, 1194, 1460,...","[1, 426, 617, 735, 908, 1095, 1383, 1473, 1564...","[1, 225, 396, 742, 1223, 1707, 1798, 2077, 231...","[1, 182, 315, 543, 766, 1135, 1226, 1500, 1632...","[1, 131, 379, 647, 738, 881, 972, 1062, 1153, ...","[0, 166, 395, 702, 1038, 1497, 1759, 2387, 282...","[0, 57, 452, 1022, 1103, 1641, 1991, 2388, 306...","[0, 19, 122, 184, 311, 467, 827, 1065, 1121, 1...","[0, 188, 968, 1291, 2209, 2480, 2695, 3298, 34...","[0, 166, 395, 631, 687, 1023, 1582, 1855, 2009...","[0, 0, 183, 384, 528, 1025, 1025, 1391, 1973, ...","[0, 30, 254, 444, 615, 843, 1209, 1329, 1500, ...","[0, 197, 532, 698, 1368, 1719, 1902, 2000, 224...","[0, 87, 458, 631, 997, 1189, 1317, 1656, 1884,...","[0, 188, 510, 945, 1136, 1136, 1136, 1136, 113...","[0, 2, 8, 12, 18, 22, 25, 33, 39, 45, 52]","[0, 0, 1, 5, 8, 9, 10, 13, 15, 17, 19]","[0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]","[0, 2, 4, 6, 9, 12, 14, 21, 25, 28, 33]","[0, 0, 0, 0, 0, 5, 8, 8, 8, 8, 13]","[0, 0, 4, 8, 11, 11, 12, 14, 18, 22, 22]","[0, 0, 2, 4, 6, 8, 12, 12, 12, 12, 12]","[0, 2, 4, 7, 15, 15, 15, 18, 25, 27, 27]","[0, 0, 1, 1, 4, 6, 6, 9, 10, 11, 16]","[0, 0, 4, 8, 8, 8, 8, 8, 8, 8, 8]","[0, 0, 1, 5, 5, 7, 7, 7, 7, 7, 7]","[0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3]","[0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2]","[0, 1, 2, 2, 4, 6, 7, 8, 9, 11, 12]","[0, 0, 0, 1, 1, 2, 3, 3, 3, 3, 4]","[0, 0, 0, 0, 0, 1, 1, 1, 2, 3, 3]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 1, 3, 7, 7, 7, 7, 7, 7, 7]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3]","[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]",18172,13144,5028,16,3,13,4,16,-12,37,30,7,17463,13063,4400,69765,46818,22947,39
2,6db558535151ea18ca70a6892197db41,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.0,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skywrath_mage,rattletrap,phantom_assassin,dragon_knight,furion,sven,spectre,viper,venomancer,storm_spirit,{},{},{'npc_dota_hero_spectre': 70},{},{},{},{'npc_dota_hero_phantom_assassin': 68},{},{},{},0,0,0,0,70,70,0,0,0,0,0,0,68,68,0,0,0,0,0,0,[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],880,480,400,0,0,0,0,0,0,5,5,0,70,68,2,70,68,2,0
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.0,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.00,0,0,2,0,False,False,False,False,False,False,False,False,True,False,pudge,bristleback,skywrath_mage,lion,faceless_void,sven,shredder,juggernaut,doom_bringer,rubick,"{'npc_dota_hero_pudge': 918, 'npc_dota_hero_do...","{'npc_dota_creep_badguys_melee': 6665, 'npc_do...","{'npc_dota_hero_shredder': 4304, 'npc_dota_cre...","{'npc_dota_hero_doom_bringer': 710, 'npc_dota_...","{'npc_dota_creep_badguys_melee': 4949, 'npc_do...","{'npc_dota_neutral_satyr_trickster': 2710, 'np...","{'npc_dota_creep_goodguys_melee': 5060, 'npc_d...","{'npc_dota_creep_goodguys_melee': 6142, 'npc_d...","{'npc_dota_creep_goodguys_melee': 960, 'npc_do...","{'npc_dota_hero_bristleback': 1577, 'npc_dota_...",3350,3130,19497,6101,14140,4468,1819,710,11575,1133,36761,0,8913,2087,13392,2633,6010,1952,3955,1665,"[81, 171, 262, 524, 615, 820, 911, 1105, 1196,...","[81, 171, 499, 658, 924, 1285, 1416, 1968, 213...","[81, 274, 540, 1239, 1455, 2132, 2398, 2706, 3...","[81, 171, 262, 464, 555, 885, 976, 1092, 1272,...","[81, 288, 681, 992, 1374, 1620, 2029, 2418, 26...","[104, 194, 424, 658, 828, 1258, 1491, 1917, 22...","[104, 315, 579, 710, 1014, 1148, 1379, 1865, 2...","[104, 272, 547, 892, 1321, 1602, 1989, 2331, 2...","[104, 262, 427, 625, 821, 1031, 1180, 1539, 17...","[104, 194, 285, 376, 561, 728, 819, 910, 1001,...","[0, 77, 206, 352, 422, 611, 701, 970, 1177, 1311]","[0, 114, 720, 1153, 1539, 2050, 2121, 2548, 28...","[0, 240, 776, 1231, 1616, 2282, 2750, 3318, 36...","[0, 42, 233, 372, 504, 698, 768, 984, 1095, 1194]","[0, 77, 410, 849, 1209, 1460, 1805, 2204, 2817...","[0, 0, 336, 506, 634, 1056, 1283, 1533, 1960, ...","[0, 240, 719, 1028, 1596, 1933, 2275, 2772, 32...","[0, 118, 354, 708, 1096, 1377, 1699, 2010, 219...","[0, 57, 172, 266, 499, 822, 908, 1250, 1504, 1...","[0, 118, 354, 463, 761, 990, 1312, 1494, 1676,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 5, 7, 10, 16, 17, 24, 26, 30]","[0, 2, 6, 11, 14, 20, 24, 27, 33, 37]","[0, 0, 0, 2, 2, 2, 2, 2, 2, 2]","[0, 3, 10, 15, 22, 25, 32, 39, 42, 51]","[0, 0, 7, 10, 12, 24, 29, 36, 47, 56]","[0, 3, 7, 8, 13, 14, 17, 20, 23, 23]","[0, 2, 6, 12, 19, 23, 30, 34, 39, 40]","[0, 1, 3, 4, 6, 8, 9, 12, 15, 15]","[0, 0, 0, 0, 2, 2, 2, 2, 2, 2]","[0, 0, 1, 1, 1, 1, 1, 1, 1, 1]","[0, 0, 0, 0, 1, 2, 2, 2, 2, 2]","[0, 0, 2, 2, 2, 4, 7, 7, 8, 8]","[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]","[0, 2, 9, 12, 14, 15, 17, 21, 23, 28]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 2, 2, 4, 4, 4, 4, 5, 5]","[0, 0, 0, 0, 0, 1, 2, 3, 4, 4]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 1, 1, 1, 1]",13348,11301,2047,6,1,5,2,7,-5,32,28,4,15542,8337,7205,50381,69031,-18650,16
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.5,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.25,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skeleton_king,doom_bringer,shadow_shaman,legion_commander,batrider,kunkka,zuus,sniper,gyrocopter,antimage,"{'npc_dota_hero_antimage': 418, 'npc_dota_cree...","{'npc_dota_hero_antimage': 766, 'npc_dota_cree...","{'npc_dota_hero_gyrocopter': 168, 'npc_dota_cr...","{'npc_dota_hero_antimage': 248, 'npc_dota_cree...","{'npc_dota_creep_badguys_melee': 4301, 'npc_do...","{'npc_dota_hero_legion_commander': 134, 'npc_d...","{'npc_dota_creep_goodguys_melee': 4583, 'npc_d...","{'npc_dota_hero_shadow_shaman': 1521, 'npc_dot...","{'npc_dota_hero_shadow_shaman': 447, 'npc_dota...","{'npc_dota_hero_doom_bringer': 672, 'npc_dota_...",4547,655,8519,1534,9178,1299,8946,1523,6723,929,11833,3471,9431,3098,13832,1521,8388,2858,10739,1003,"[21, 191, 282, 481, 610, 820, 988, 1355]","[283, 555, 782, 1030, 1186, 1372, 1488, 1645]","[1, 211, 345, 573, 664, 854, 1024, 1115]","[27, 238, 504, 595, 781, 1149, 1374, 1675]","[1, 171, 356, 515, 700, 944, 1174, 1438]","[1, 210, 339, 468, 823, 1030, 1202, 1293]","[1, 214, 456, 667, 758, 890, 1180, 1326]","[86, 431, 686, 957, 1183, 1457, 1670, 2173]","[165, 389, 556, 981, 1115, 1248, 1431, 1648]","[1, 312, 542, 905, 1217, 1442, 1756, 2077]","[20, 66, 247, 365, 519, 789, 887, 1295]","[20, 80, 278, 524, 678, 1062, 1229, 1511]","[0, 297, 777, 1214, 1694, 2048, 2856, 2856]","[20, 148, 384, 384, 684, 1042, 1343, 1823]","[0, 147, 383, 623, 797, 915, 1090, 1090]","[0, 133, 384, 749, 1053, 1205, 1499, 1624]","[0, 118, 305, 636, 844, 1195, 1439, 1617]","[30, 327, 807, 1301, 1838, 2387, 2684, 3304]","[30, 148, 266, 569, 777, 957, 1236, 1623]","[0, 133, 384, 608, 912, 1235, 1529, 1753]","[0, 0, 0, 1, 2, 3, 5, 9]","[0, 2, 5, 8, 9, 11, 11, 12]","[0, 1, 2, 5, 5, 7, 9, 9]","[0, 1, 5, 5, 7, 13, 16, 21]","[0, 0, 2, 2, 4, 4, 7, 7]","[0, 1, 2, 3, 5, 6, 8, 8]","[0, 1, 4, 7, 7, 8, 9, 10]","[0, 4, 8, 12, 15, 19, 22, 31]","[0, 1, 3, 4, 5, 6, 9, 12]","[0, 3, 6, 12, 16, 19, 23, 28]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 1, 1, 1, 1]","[0, 0, 0, 1, 1, 1, 1, 2]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 2, 4, 5, 6, 6, 8, 8]",8079,9177,-1098,2,4,-2,4,2,2,25,26,-1,5940,11951,-6011,37913,54223,-16310,12

In [31]:
def match_timeseries_widget_random(df, idx=0, time_step=60):
    metrics = {
        "gold_t": "Gold networth",
        "xp_t": "XP",
        "lh_t": "Last hits",
        "dn_t": "Denies",
    }

    players = [f"r{i}" for i in range(1, 6)] + [f"d{i}" for i in range(1, 6)]

    out = widgets.Output()

    dropdown = widgets.Dropdown(
        options=[(label, key) for key, label in metrics.items()],
        value="gold_t",
        description="Metric",
        layout=widgets.Layout(width="260px")
    )

    btn_random = widgets.Button(
        description="Random match",
        button_style="",
        icon="random",
        layout=widgets.Layout(width="150px")
    )

    idx_label = widgets.HTML()

    state = {"idx": idx}

    def coerce_list(val):
        if val is None:
            return []
        if isinstance(val, (list, tuple)):
            return list(val)
        if isinstance(val, str):
            s = val.strip()
            if s.startswith("[") and s.endswith("]"):
                try:
                    parsed = ast.literal_eval(s)
                    if isinstance(parsed, list):
                        return parsed
                except Exception:
                    return []
        return []

    def get_series(row, p, metric):
        col = f"{p}_{metric}"
        if col not in row.index:
            return []
        return coerce_list(row[col])

    def update_label(row_idx):
        text = f"<b>idx:</b> {row_idx}"
        idx_label.value = text

    def plot():
        row_idx = state["idx"]
        metric = dropdown.value
        row = df.iloc[row_idx]

        with out:
            clear_output(wait=True)

            plt.figure(figsize=(10, 6))

            plotted_any = False
            max_len = 0

            for p in players:
                values = get_series(row, p, metric)
                if not values:
                    continue

                max_len = max(max_len, len(values))
                times = [i * time_step for i in range(len(values))]
                color = "green" if p.startswith("r") else "red"

                plt.plot(times, values, color=color, alpha=0.9)
                plotted_any = True

            if not plotted_any:
                print(
                    f"Для строки idx={row_idx} нет данных {metric}. "
                    f"Проверь, что колонки r1_{metric} ... d5_{metric} прикреплены "
                    f"и что в этой строке они не пустые"
                )
                return

            plt.xlabel("Time, sec")
            plt.ylabel(metrics[metric])
            plt.title(f"{metrics[metric]} for all players, idx = {row_idx}")

            if max_len > 1:
                plt.xlim(0, (max_len - 1) * time_step)

            legend_handles = [
                Line2D([0], [0], color="green", lw=2, label="Radiant"),
                Line2D([0], [0], color="red", lw=2, label="Dire"),
            ]
            plt.legend(handles=legend_handles, loc="upper left")

            plt.tight_layout()
            plt.show()

    def on_metric_change(change):
        if change.get("name") == "value":
            update_label(state["idx"])
            plot()

    def on_random_click(_):
        state["idx"] = random.randrange(0, len(df))
        update_label(state["idx"])
        plot()

    dropdown.observe(on_metric_change)
    btn_random.on_click(on_random_click)

    controls = widgets.HBox([dropdown, btn_random, idx_label])

    display(controls)
    display(out)

    update_label(state["idx"])
    plot()

In [32]:
match_timeseries_widget_random(raw_features, idx=longest_match_id)

HBox(children=(Dropdown(description='Metric', layout=Layout(width='260px'), options=(('Gold networth', 'gold_t…

Output()

In [33]:
raw_features.iloc[0]

match_id_hash                     a400b8f29dece5f4d266f49f1ae2e98a
game_time                                                      155
game_mode                                                       22
lobby_type                                                       7
objectives_len                                                   1
                                                ...
radiant_hero_damage_advantage                                -2001
radiant_total_total_damage                                    8736
dire_total_total_damage                                       9445
radiant_total_damage_advantage                                -709
total_kills_deaths                                               2
Name: 0, Length: 355, dtype: object

In [44]:

drop_suffixes = ("_damage", "_damage_taken", "_gold_t", "_lh_t", "_dn_t", "_xp_t")
drop_cols = [c for c in raw_features.columns if c.endswith(drop_suffixes)]

X = raw_features.drop(columns=drop_cols + ['match_id_hash'], errors="ignore")
y = raw_targets["radiant_win"]

In [ ]:
# X = df_feats.drop(['match_id_hash',], axis=1)
# y = raw_targets["radiant_win"]

In [36]:
X

,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed,r1_pred_vict,r2_pred_vict,r3_pred_vict,r4_pred_vict,r5_pred_vict,d1_pred_vict,d2_pred_vict,d3_pred_vict,d4_pred_vict,d5_pred_vict,r1_hero_name,r2_hero_name,r3_hero_name,r4_hero_name,r5_hero_name,d1_hero_name,d2_hero_name,d3_hero_name,d4_hero_name,d5_hero_name,r1_damage,r2_damage,r3_damage,r4_damage,r5_damage,d1_damage,d2_damage,d3_damage,d4_damage,d5_damage,r1_total_damage,r1_hero_damage,r2_total_damage,r2_hero_damage,r3_total_damage,r3_hero_damage,r4_total_damage,r4_hero_damage,r5_total_damage,r5_hero_damage,d1_total_damage,d1_hero_damage,d2_total_damage,d2_hero_damage,d3_total_damage,d3_hero_damage,d4_total_damage,d4_hero_damage,d5_total_damage,d5_hero_damage,r1_gold_t,r2_gold_t,r3_gold_t,r4_gold_t,r5_gold_t,d1_gold_t,d2_gold_t,d3_gold_t,d4_gold_t,d5_gold_t,r1_xp_t,r2_xp_t,r3_xp_t,r4_xp_t,r5_xp_t,d1_xp_t,d2_xp_t,d3_xp_t,d4_xp_t,d5_xp_t,r1_lh_t,r2_lh_t,r3_lh_t,r4_lh_t,r5_lh_t,d1_lh_t,d2_lh_t,d3_lh_t,d4_lh_t,d5_lh_t,r1_dn_t,r2_dn_t,r3_dn_t,r4_dn_t,r5_dn_t,d1_dn_t,d2_dn_t,d3_dn_t,d4_dn_t,d5_dn_t,radiant_total_gold,dire_total_gold,radiant_gold_advantage,radiant_total_kills,dire_total_kills,radiant_kills_advantage,radiant_total_deaths,dire_total_deaths,radiant_deaths_advantage,radiant_total_level,dire_total_level,radiant_level_advantage,radiant_total_hero_damage,dire_total_hero_damage,radiant_hero_damage_advantage,radiant_total_total_damage,dire_total_total_damage,radiant_total_damage_advantage,total_kills_deaths
0,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00000,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00000,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00000,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.000,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.0000,0,0,0,0,False,False,False,False,False,True,True,False,False,False,nevermore,brewmaster,pudge,huskar,lycan,phantom_lancer,windrunner,night_stalker,ogre_magi,tinker,"{'npc_dota_creep_goodguys_melee': 92, 'npc_dot...","{'npc_dota_creep_goodguys_ranged': 113, 'npc_d...","{'npc_dota_hero_ogre_magi': 16, 'npc_dota_hero...","{'npc_dota_creep_badguys_melee': 497, 'npc_dot...","{'npc_dota_neutral_satyr_soulstealer': 1286, '...","{'npc_dota_creep_badguys_melee': 695, 'npc_dot...","{'npc_dota_hero_huskar': 402, 'npc_dota_creep_...","{'npc_dota_hero_huskar': 635, 'npc_dota_creep_...",{'npc_dota_hero_pudge': 868},"{'npc_dota_hero_nevermore': 704, 'npc_dota_cre...",1287,459,1327,0,32,32,1000,457,5090,0,3521,224,1977,402,747,635,868,868,2332,820,"[1, 91, 356]","[1, 91, 262]","[1, 91, 182]","[1, 169, 260]","[1, 91, 281]","[1, 331, 738]","[1, 251, 561]","[1, 251, 342]","[1, 251, 342]","[1, 425, 680]","[0, 107, 387]","[0, 38, 318]","[0, 0, 73]","[0, 202, 301]","[0, 38, 238]","[0, 85, 431]","[0, 58, 445]","[0, 41, 229]","[0, 85, 329]","[0, 240, 616]","[0, 0, 4]","[0, 0, 2]","[0, 0, 0]","[0, 2, 2]","[0, 0, 5]","[0, 2, 9]","[0, 0, 5]","[0, 0, 0]","[0, 0, 0]","[0, 4, 8]","[0, 0, 0]","[0, 0, 2]","[0, 0, 0]","[0, 1, 1]","[0, 0, 0]","[0, 4, 12]","[0, 1, 4]","[0, 0, 1]","[0, 0, 0]","[0, 0, 0]",2037,3948,-1911,0,1,-1,1,0,1,9,13,-4,948,2949,-2001,8736,9445,-709,2
1,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25000,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25000,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50000,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.500,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.0000,0,0,0,0,False,False,False,False,False,False,False,False,False,False,razor,centaur,shadow_shaman,weaver,naga_siren,enchantress,pudge,antimage,clinkz,visage,"{'npc_dota_hero_pudge': 2298, 'npc_dota_hero_c...","{'npc_dota_creep_goodguys_ranged': 194, 'npc_d...","{'npc_dota_hero_clinkz': 122, 'npc_dota_hero_p...","{'npc_dota_creep_goodguys_ranged': 622, 'npc_d...","{'npc_dota_hero_clinkz': 1021, 'npc_dota_hero_...","{'npc_dota_hero_centaur': 2252, 'npc_dota_neut...","{'npc_dota_hero_shadow_shaman': 890, 'npc_dota...","{'npc_dota_hero_centaur': 1617, 'npc_dota_cree...","{'npc_dota_hero_shadow_shaman': 258, 'npc_dota...","{'npc_dota_creep_goodguys_melee': 903, 'npc_do...",20882,4656,14983,5096,5941,1091,21394,4708,6565,1912,13575,2871,9643,4141,13855,2054,7437,3071,2308,926,"[41, 819, 1196, 1467, 1839, 2356, 2812, 3444, ...","[41, 211, 340, 589, 762, 1209, 1579, 1803, 240...","[41, 211, 302, 393, 530, 621, 712, 877, 968, 1...","[41, 292, 750, 922, 1644, 1875, 2042, 2623, 28...","[41, 541, 632, 723, 814, 1100, 1406, 1769, 186...","[1, 131, 295, 458, 592, 814, 1002, 1194, 1460,...","[1, 426, 617, 735, 908, 1095, 1383, 1473, 1564...","[1, 225, 396, 742, 1223, 1707, 1798, 2077, 231...","[1, 182, 315, 543, 766, 1135, 1226, 1500, 1632...","[1, 131, 379, 647, 738, 881, 972, 1062, 1153, ...","[0, 166, 395, 702, 1038, 1497, 1759, 2387, 282...","[0, 57, 452, 1022, 1103, 1641, 1991, 2388, 306...","[0, 19, 122, 184, 311, 467, 827, 1065, 1121, 1...","[0, 188, 968, 1291, 2209, 2480, 2695, 3298, 34...","[0, 166, 395, 631, 687, 1023, 1582, 1855, 2009...","[0, 0, 183, 384, 528, 1025, 1025, 1391, 1973, ...","[0, 30, 254, 444, 615, 843, 1209, 1329, 1500, ...","[0, 197, 532, 698, 1368, 1719, 1902, 2000, 224...","[0, 87, 458, 631, 997, 1189, 1317, 1656, 1884,...","[0, 188, 510, 945, 1136, 1136, 1136, 1136, 113...","[0, 2, 8, 12, 18, 22, 25, 33, 39, 45, 52]","[0, 0, 1, 5, 8, 9, 10, 13, 15, 17, 19]","[0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]","[0, 2, 4, 6, 9, 12, 14, 21, 25, 28, 33]","[0, 0, 0, 0, 0, 5, 8, 8, 8, 8, 13]","[0, 0, 4, 8, 11, 11, 12, 14, 18, 22, 22]","[0, 0, 2, 4, 6, 8, 12, 12, 12, 12, 12]","[0, 2, 4, 7, 15, 15, 15, 18, 25, 27, 27]","[0, 0, 1, 1, 4, 6, 6, 9, 10, 11, 16]","[0, 0, 4, 8, 8, 8, 8, 8, 8, 8, 8]","[0, 0, 1, 5, 5, 7, 7, 7, 7, 7, 7]","[0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3]","[0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2]","[0, 1, 2, 2, 4, 6, 7, 8, 9, 11, 12]","[0, 0, 0, 1, 1, 2, 3, 3, 3, 3, 4]","[0, 0, 0, 0, 0, 1, 1, 1, 2, 3, 3]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 1, 3, 7, 7, 7, 7, 7, 7, 7]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3]","[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]",18172,13144,5028,16,3,13,4,16,-12,37,30,7,17463,13063,4400,69765,46818,22947,39
2,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00000,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00000,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00000,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.000,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.0000,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skywrath_mage,rattletrap,phantom_assassin,dragon_knight,furion,sven,spectre,viper,venomancer,storm_spirit,{},{},{'npc_dota_hero_spectre': 70},{},{},{},{'npc_dota_hero_phantom_assassin': 68},{},{},{},0,0,0,0,70,70,0,0,0,0,0,0,68,68,0,0,0,0,0,0,[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],880,480,400,0,0,0,0,0,0,5,5,0,70,68,2,70,68,2,0
3,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00000,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50000,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50000,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.000,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.0000,0,0,2,0,False,False,False,False,False,False,False,False,True,False,pudge,bristleback,skywrath_mage,lion,faceless_void,sven,shredder,juggernaut,doom_bringer,rubick,"{'npc_dota_hero_pudge': 918, 'npc_dota_hero_do...","{'npc_dota_creep_badguys_melee': 6665, 'npc_do...","{'npc_dota_hero_shredder': 4304, 'npc_dota_cre...","{'npc_dota_hero_doom_bringer': 710, 'npc_dota_...","{'npc_dota_creep_badguys_melee': 4949, 'npc_do...","{'npc_dota_neutral_satyr_trickster': 2710, 'np...","{'npc_dota_creep_goodguys_melee': 5060, 'npc_d...","{'npc_dota_creep_goodguys_melee': 6142, 'npc_d...","{'npc_dota_creep_goodguys_melee': 960, 'npc_do...","{'npc_dota_hero_bristleback': 1577, 'npc_dota_...",3350,3130,19497,6101,14140,4468,1819,710,11575,1133,36761,0,8913,2087,13392,2633,6010,1952,3955,1665,"[81, 171, 262, 524, 615, 820, 911, 1105, 1196,...","[81, 171, 499, 658, 924, 1285, 1416, 1968, 213...","[81, 274, 540, 1239, 1455, 2132, 2398, 2706, 3...","[81, 171, 262, 464, 555, 885, 976, 1092, 1272,...","[81, 288, 681, 992, 1374, 1620, 2029, 2418, 26...","[104, 194, 424, 658, 828, 1258, 1491, 1917, 22...","[104, 315, 579, 710, 1014, 1148, 1379, 1865, 2...","[104, 272, 547, 892, 1321, 1602, 1989, 2331, 2...","[104, 262, 427, 625, 821, 1031, 1180, 1539, 17...","[104, 194, 285, 376, 561, 728, 819, 910, 1001,...","[0, 77, 206, 352, 422, 611, 701, 970, 1177, 1311]","[0, 114, 720, 1153, 1539, 2050, 2121, 2548, 28...","[0, 240, 776, 1231, 1616, 2282, 2750, 3318, 36...","[0, 42, 233, 372, 504, 698, 768, 984, 1095, 1194]","[0, 77, 410, 849, 1209, 1460, 1805, 2204, 2817...","[0, 0, 336, 506, 634, 1056, 1283, 1533, 1960, ...","[0, 240, 719, 1028, 1596, 1933, 2275, 2772, 32...","[0, 118, 354, 708, 1096, 1377, 1699, 2010, 219...","[0, 57, 172, 266, 499, 822, 908, 1250, 1504, 1...","[0, 118, 354, 463, 761, 990, 1312, 1494, 1676,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 5, 7, 10, 16, 17, 24, 26, 30]","[0, 2, 6, 11, 14, 20, 24, 27, 33, 37]","[0, 0, 0, 2, 2, 2, 2, 2, 2, 2]","[0, 3, 10, 15, 22, 25, 32, 39, 42, 51]","[0, 0, 7, 10, 12, 24, 29, 36, 47, 56]","[0, 3, 7, 8, 13, 14, 17, 20, 23, 23]","[0, 2, 6, 12, 19, 23, 30, 34, 39, 40]","[0, 1, 3, 4, 6, 8, 9, 12, 15, 15]","[0, 0, 0, 0, 2, 2, 2, 2, 2, 2]","[0, 0, 1, 1, 1, 1, 1, 1, 1, 1]","[0, 0, 0, 0, 1, 2, 2, 2, 2, 2]","[0, 0, 2, 2, 2, 4, 7, 7, 8, 8]","[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]","[0, 2, 9, 12, 14, 15, 17, 21, 23, 28]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 2, 2, 4, 4, 4, 4, 5, 5]","[0, 0, 0, 0, 0, 1, 2, 3, 4, 4]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 1, 1, 1, 1]",13348,11301,2047,6,1,5,2,7,-5,32,28,4,15542,8337,7205,50381,69031,-18650,16
4,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25000,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25000,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25000,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.500,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.2500,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skeleton_king,doom_bringer,shadow_shaman,legion_commander,batrider,kunkka,zuus,sniper,gyrocopter,antimage,"{'npc_dota_hero_antimage': 418, 'npc_dota_cree...","{'npc_dota_hero_antimage': 766, 'npc_dota_cree...","{'npc_dota_hero_gyrocopter': 168, 'npc_dota_cr...","{'npc_dota_hero_antimage': 248, 'npc_dota_cree...","{'npc_dota_creep_badguys_melee': 4301, 'npc_do...","{'npc_dota_hero_legion_commander': 134, 'npc_d...","{'npc_dota_creep_goodguys_melee': 4583, 'npc_d...","{'npc_dota_hero_shadow_shaman': 1521, 'npc_dot...","{'npc_dota_hero_shadow_shaman': 447, 'npc_dota...","{'npc_dota_hero_doom_bringer': 672, 'npc_dota_...",4547,655,8519,1534,9178,1299,8946,1523,6723,929,11833,3471,9431,3098,13832,1521,8388,2858,10739,1003,"[21, 191, 282, 481, 610, 820, 988, 1355]","[283, 555, 782, 1030, 1186, 1372, 1488, 1645]","[1, 211, 345, 573, 664, 854, 1024, 1115]","[27, 238, 504, 595, 781, 1149, 1374, 1675]","[1, 171, 356, 515, 700, 944, 1174, 1438]","[1, 210, 339, 468, 823, 1030, 1202, 1293]","[1, 214, 456, 667, 758, 890, 1180, 1326]","[86, 431, 686, 957, 1183, 1457, 1670, 2173]","[165, 389, 556, 981, 1115, 1248, 1431, 1648]","[1, 312, 542, 905, 1217, 1442, 1756, 2077]","[20, 66, 247, 365, 519, 789, 887, 1295]","[20, 80, 278, 524, 678, 1062, 1229, 1511]","[0, 297, 777, 1214, 1694, 2048, 2856, 2856]","[20, 148, 384, 384, 684, 1042, 1343, 1823]","[0, 147, 383, 623, 797, 915, 1090, 1090]","[0, 133, 384, 749, 1053, 1205, 1499, 1624]","[0, 118, 305, 636, 844, 1195, 1439, 1617]","[30, 327, 807, 1301, 1838, 2387, 2684, 3304]","[30, 148, 266, 569, 777, 957, 1236, 1623]","[0, 133, 384, 608, 912, 1235, 1529, 1753]","[0, 0, 0, 1, 2, 3, 5, 9]","[0, 2, 5, 8, 9, 11, 11, 12]","[0, 1, 2, 5, 5, 7, 9, 9]","[0, 1, 5, 5, 7, 13, 16, 21]","[0, 0, 2, 2, 4, 4, 7, 7]","[0, 1, 2, 3, 5, 6, 8, 8]","[0, 1, 4, 7, 7, 8, 9, 10]","[0, 4, 8, 12, 15, 19, 22, 31]","[0, 1, 3, 4, 5, 6, 9, 12]","[0, 3, 6, 12, 16, 19, 23, 28]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 1, 1, 1, 1]","[0, 0, 0, 1, 1, 1, 1, 2]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 2, 4, 5, 6, 6, 8, 8]",8079,9177,-1098,2,4,-2,4,2,2,25,26,-1,5940,11951,-6011,37913,54223,-16310,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [37]:
y.head()

0    False
1     True
2     True
3     True
4    False
Name: radiant_win, dtype: bool

In [ ]:
# path = "DOTA 2//train_matches.jsonl"

# with open(path, "r", encoding="utf-8") as f:
#     for line in itertools.islice(f, 5):  # первые 5 строк
#         print(line.strip())

{"game_time": 155, "match_id_hash": "a400b8f29dece5f4d266f49f1ae2e98a", "teamfights": [], "objectives": [{"time": 124.203, "type": "CHAT_MESSAGE_FIRSTBLOOD", "slot": 8, "key": 2, "player_slot": 131}], "chat": [{"player_slot": 0, "time": -13.63, "text": "???"}, {"player_slot": 0, "time": -10.964, "text": "? ???? ??????"}, {"player_slot": 0, "time": -7.965, "text": "???????? ????("}, {"player_slot": 4, "time": 43.756, "text": "???"}, {"player_slot": 2, "time": 44.422, "text": "??? ??????"}, {"player_slot": 4, "time": 45.289, "text": "*[*[*["}, {"player_slot": 2, "time": 46.622, "text": "????"}, {"player_slot": 4, "time": 47.355, "text": "??? ??????"}, {"player_slot": 4, "time": 48.688, "text": "????"}, {"player_slot": 2, "time": 52.021, "text": "???????? ??? ??????"}, {"player_slot": 4, "time": 73.349, "text": "????? ??? ?????"}], "game_mode": 22, "lobby_type": 7, "players": [{"player_slot": 0, "hero_id": 11, "hero_name": "npc_dota_hero_nevermore", "account_id_hash": "86bf86c5488742478688149155258ea8", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 1, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 94.977, "max": true, "inflictor": "nevermore_shadowraze2", "unit": "npc_dota_hero_nevermore", "key": "npc_dota_hero_tinker", "value": 136, "slot": 0, "player_slot": 0}, "times": [0, 60, 120], "gold_t": [1, 91, 356], "lh_t": [0, 0, 4], "dn_t": [0, 0, 0], "xp_t": [0, 107, 387], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "wraith_band"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": -84.215, "key": "tango"}, {"time": 99.409, "key": "flask"}, {"time": 100.909, "key": "clarity"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 134.067, "key": 0}], "obs": {}, "sen": {}, "actions": {"1": 551, "2": 8, "4": 43, "6": 1, "7": 2, "8": 6, "10": 1, "11": 2, "15": 2, "16": 8, "17": 2, "19": 6, "21": 30, "33": 30}, "pings": {"0": 6}, "purchase": {"wraith_band": 1, "enchanted_mango": 1, "tpscroll": 1, "tango": 1, "flask": 1, "clarity": 1}, "gold_reasons": {"0": 600, "13": 308}, "xp_reasons": {"2": 533}, "killed": {"npc_dota_creep_badguys_melee": 250, "npc_dota_creep_badguys_ranged": 203}, "item_uses": {"tango": 1, "flask": 1}, "ability_uses": {"nevermore_shadowraze3": 1, "nevermore_shadowraze1": 1, "nevermore_shadowraze2": 1}, "hero_hits": {"null": 3, "nevermore_shadowraze3": 1, "nevermore_shadowraze1": 1, "nevermore_shadowraze2": 1}, "damage": {"npc_dota_creep_goodguys_melee": 92, "npc_dota_creep_badguys_melee": 478, "npc_dota_hero_tinker": 459, "npc_dota_creep_badguys_ranged": 203, "npc_dota_creep_goodguys_ranged": 55}, "damage_taken": {"npc_dota_hero_tinker": 704, "npc_dota_creep_badguys_melee": 231, "npc_dota_creep_badguys_ranged": 38}, "damage_inflictor": {"null": 159, "nevermore_shadowraze3": 64, "nevermore_shadowraze1": 100, "nevermore_shadowraze2": 136}, "runes": {"0": 1}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {"tinker_laser": 410, "null": 294}, "randomed": false, "pred_vict": false, "gold": 543, "lh": 7, "xp": 533, "x": 116, "y": 122, "hero_inventory": [{"id": "item_tango", "num_charges": 2, "cooldown": 0}, {"id": "item_wraith_band", "cooldown": 0}, {"id": "item_enchanted_mango", "cooldown": 0}, {"id": "item_clarity", "num_charges": 1, "cooldown": 0}, {"id": "item_tpscroll", "num_charges": 1, "cooldown": 0}], "hero_stash": [], "health": 358, "max_health": 600, "max_mana": 350.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 0, "nearby_creep_death_count": 19}, {"player_slot": 1, "hero_id": 78, "hero_name": "npc_dota_hero_brewmaster", "account_id_hash": "67d6d5d0a77e585a11319af7bdd5caed", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 0, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"value": 0}, "times": [0, 60, 120], "gold_t": [1, 91, 262], "lh_t": [0, 0, 2], "dn_t": [0, 0, 2], "xp_t": [0, 38, 318], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tpscroll"}, {"time": -66.817, "key": "stout_shield"}, {"time": -66.417, "key": "enchanted_mango"}, {"time": -65.851, "key": "tango"}, {"time": -65.184, "key": "tango"}, {"time": -64.951, "key": "flask"}], "kills_log": [], "buyback_log": [], "runes_log": [], "obs": {}, "sen": {}, "actions": {"1": 713, "4": 196, "5": 1, "6": 3, "7": 18, "8": 2, "10": 52, "11": 2, "12": 1, "16": 5, "19": 1, "33": 52}, "pings": {}, "purchase": {"tpscroll": 1, "stout_shield": 1, "enchanted_mango": 1, "tango": 2, "flask": 1}, "gold_reasons": {"0": 600, "13": 164}, "xp_reasons": {"2": 478}, "killed": {"npc_dota_creep_goodguys_ranged": 113, "npc_dota_creep_badguys_melee": 281, "npc_dota_creep_goodguys_melee": 53}, "item_uses": {"tpscroll": 1, "enchanted_mango": 1, "flask": 1, "tango": 6}, "ability_uses": {"brewmaster_drunken_haze": 2}, "hero_hits": {}, "damage": {"npc_dota_creep_goodguys_ranged": 113, "npc_dota_creep_badguys_melee": 1002, "npc_dota_creep_goodguys_melee": 212}, "damage_taken": {"npc_dota_creep_badguys_melee": 148, "npc_dota_hero_tinker": 116}, "damage_inflictor": {}, "runes": {}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {"npc_dota_hero_brewmaster": 1}, "damage_inflictor_received": {"null": 116}, "randomed": false, "pred_vict": false, "gold": 399, "lh": 4, "xp": 478, "x": 124, "y": 126, "hero_inventory": [], "hero_stash": [], "health": 636, "max_health": 720, "max_mana": 254.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 3, "nearby_creep_death_count": 19}, {"player_slot": 2, "hero_id": 14, "hero_name": "npc_dota_hero_pudge", "account_id_hash": "d0cb6c812472517b999025ea19d17b5c", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 1, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 123.437, "max": true, "inflictor": "pudge_rot", "unit": "npc_dota_hero_pudge", "key": "npc_dota_hero_ogre_magi", "value": 4, "slot": 2, "player_slot": 2}, "times": [0, 60, 120], "gold_t": [1, 91, 182], "lh_t": [0, 0, 0], "dn_t": [0, 0, 0], "xp_t": [0, 0, 73], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tpscroll"}, {"time": -70.849, "key": "courier"}, {"time": -69.116, "key": "tango"}, {"time": -65.117, "key": "magic_stick"}, {"time": -19.662, "key": "wind_lace"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 139.333, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 145, "5": 1, "7": 3, "8": 1, "9": 1, "10": 10, "11": 1, "15": 1, "16": 4, "19": 3, "33": 10}, "pings": {"0": 1}, "purchase": {"tpscroll": 1, "courier": 1, "tango": 1, "magic_stick": 1, "wind_lace": 1}, "gold_reasons": {"0": 669, "1": -67}, "xp_reasons": {"2": 130}, "killed": {}, "item_uses": {"courier": 1, "tango": 3, "tpscroll": 1}, "ability_uses": {"pudge_rot": 1}, "hero_hits": {"pudge_rot": 8}, "damage": {"npc_dota_hero_ogre_magi": 16, "npc_dota_hero_pudge": 16}, "damage_taken": {"npc_dota_hero_ogre_magi": 868, "npc_dota_hero_phantom_lancer": 224, "npc_dota_hero_pudge": 16}, "damage_inflictor": {"pudge_rot": 16}, "runes": {"5": 1}, "killed_by": {"npc_dota_hero_ogre_magi": 1}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 300, "1": 3, "2": 7}, "healing": {}, "damage_inflictor_received": {"null": 731, "orb_of_venom": 54, "ogre_magi_ignite": 190, "phantom_lancer_spirit_lance": 76, "ogre_magi_fireblast": 41}, "randomed": false, "pred_vict": false, "gold": 304, "lh": 0, "xp": 130, "x": 70, "y": 156, "hero_inventory": [{"id": "item_magic_stick", "num_charges": 4, "cooldown": 0}, {"id": "item_wind_lace", "cooldown": 0}], "hero_stash": [], "health": 700, "max_health": 700, "max_mana": 242.938, "level": 1, "kills": 0, "deaths": 1, "assists": 0, "denies": 0, "nearby_creep_death_count": 6}, {"player_slot": 3, "hero_id": 59, "hero_name": "npc_dota_hero_huskar", "account_id_hash": "83975f1afb5f5e97dc7266402f997dc3", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 0, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 83.48, "max": true, "inflictor": null, "unit": "npc_dota_hero_huskar", "key": "npc_dota_hero_night_stalker", "value": 42, "slot": 3, "player_slot": 3}, "times": [0, 60, 120], "gold_t": [1, 169, 260], "lh_t": [0, 2, 2], "dn_t": [0, 1, 1], "xp_t": [0, 202, 301], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tango"}, {"time": -89.783, "key": "wind_lace"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "tpscroll"}, {"time": 52.221, "key": "magic_wand"}, {"time": 52.221, "key": "magic_stick"}, {"time": 117.438, "key": "flask"}], "kills_log": [], "buyback_log": [], "runes_log": [], "obs": {}, "sen": {}, "actions": {"1": 1053, "2": 8, "3": 3, "4": 84, "6": 3, "7": 3, "8": 1, "10": 41, "11": 2, "16": 7, "19": 1, "20": 2, "33": 41}, "pings": {}, "purchase": {"tango": 1, "wind_lace": 1, "enchanted_mango": 1, "branches": 2, "tpscroll": 1, "magic_wand": 1, "magic_stick": 1, "flask": 1}, "gold_reasons": {"0": 600, "13": 154}, "xp_reasons": {"2": 506}, "killed": {"npc_dota_creep_badguys_melee": 185, "npc_dota_creep_goodguys_melee": 46}, "item_uses": {"tango": 3}, "ability_uses": {}, "hero_hits": {"huskar_burning_spear": 25, "null": 6}, "damage": {"npc_dota_creep_badguys_melee": 497, "npc_dota_hero_huskar": 90, "npc_dota_hero_windrunner": 64, "npc_dota_creep_goodguys_melee": 46, "npc_dota_hero_night_stalker": 303}, "damage_taken": {"npc_dota_hero_windrunner": 402, "npc_dota_hero_night_stalker": 635, "npc_dota_hero_huskar": 90, "npc_dota_creep_badguys_melee": 65}, "damage_inflictor": {"null": 194, "huskar_burning_spear": 173}, "runes": {}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {"null": 760, "orb_of_venom": 87, "night_stalker_void": 190}, "randomed": false, "pred_vict": false, "gold": 389, "lh": 4, "xp": 506, "x": 170, "y": 86, "hero_inventory": [{"id": "item_wind_lace", "cooldown": 0}, {"id": "item_magic_wand", "num_charges": 2, "cooldown": 0}, {"id": "item_tpscroll", "num_charges": 1, "cooldown": 0}], "hero_stash": [], "health": 399, "max_health": 700, "max_mana": 326.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 1, "nearby_creep_death_count": 14}, {"player_slot": 4, "hero_id": 77, "hero_name": "npc_dota_hero_lycan", "account_id_hash": "7713505172bca930266a2da3524ae04e", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 0, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"value": 0}, "times": [0, 60, 120], "gold_t": [1, 91, 281], "lh_t": [0, 0, 5], "dn_t": [0, 0, 0], "xp_t": [0, 38, 238], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "stout_shield"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "faerie_fire"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": -9.198, "key": "quelling_blade"}], "kills_log": [], "buyback_log": [], "runes_log": [], "obs": {}, "sen": {}, "actions": {"1": 671, "2": 5, "3": 1, "4": 130, "7": 1, "8": 1, "10": 1, "11": 2, "16": 4, "19": 2}, "pings": {}, "purchase": {"stout_shield": 1, "branches": 2, "faerie_fire": 1, "enchanted_mango": 1, "tpscroll": 1, "quelling_blade": 1}, "gold_reasons": {"0": 600, "13": 167}, "xp_reasons": {"2": 344}, "killed": {"npc_dota_neutral_satyr_soulstealer": 174, "npc_dota_neutral_satyr_trickster": 194, "npc_dota_neutral_mud_golem": 209, "npc_dota_neutral_mud_golem_split": 399}, "item_uses": {"quelling_blade": 1}, "ability_uses": {"lycan_howl": 1}, "hero_hits": {}, "damage": {"npc_dota_neutral_satyr_soulstealer": 1286, "npc_dota_neutral_satyr_trickster": 780, "npc_dota_neutral_mud_golem": 1721, "npc_dota_neutral_mud_golem_split": 1206, "npc_dota_neutral_giant_wolf": 97}, "damage_taken": {"npc_dota_neutral_satyr_soulstealer": 227, "npc_dota_neutral_satyr_trickster": 56, "npc_dota_neutral_mud_golem": 343, "npc_dota_neutral_mud_golem_split": 44, "npc_dota_neutral_giant_wolf": 35}, "damage_inflictor": {}, "runes": {}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {}, "randomed": true, "pred_vict": false, "gold": 402, "lh": 10, "xp": 344, "x": 120, "y": 100, "hero_inventory": [{"id": "item_stout_shield", "cooldown": 0}, {"id": "item_quelling_blade", "cooldown": 0}, {"id": "item_branches", "cooldown": 0}, {"id": "item_faerie_fire", "num_charges": 1, "cooldown": 0}, {"id": "item_enchanted_mango", "cooldown": 0}, {"id": "item_branches", "cooldown": 0}], "hero_stash": [], "health": 422, "max_health": 800, "max_mana": 314.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 0, "nearby_creep_death_count": 12}, {"player_slot": 128, "hero_id": 12, "hero_name": "npc_dota_hero_phantom_lancer", "account_id_hash": "c5e8f264da8fbb8b352f5298039c9be8", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 1, "firstblood_claimed": 0, "teamfight_participation": 1, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 118.771, "max": true, "inflictor": "phantom_lancer_spirit_lance", "unit": "npc_dota_hero_phantom_lancer", "key": "npc_dota_hero_pudge", "value": 76, "slot": 5, "player_slot": 128}, "times": [0, 60, 120], "gold_t": [1, 331, 738], "lh_t": [0, 2, 9], "dn_t": [0, 4, 12], "xp_t": [0, 85, 431], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tango"}, {"time": -89.783, "key": "flask"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "stout_shield"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": 23.428, "key": "quelling_blade"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 4.232, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 443, "2": 12, "3": 1, "4": 80, "6": 1, "7": 4, "10": 19, "11": 2, "15": 2, "16": 7, "17": 1, "19": 5, "33": 19}, "pings": {}, "purchase": {"tango": 1, "flask": 1, "branches": 1, "stout_shield": 1, "enchanted_mango": 1, "tpscroll": 1, "quelling_blade": 1}, "gold_reasons": {"0": 760, "12": 34, "13": 553}, "xp_reasons": {"1": 30, "2": 750}, "killed": {"npc_dota_creep_badguys_melee": 507, "npc_dota_creep_goodguys_melee": 648, "npc_dota_creep_badguys_ranged": 239, "npc_dota_creep_goodguys_ranged": 364}, "item_uses": {"tango": 1, "quelling_blade": 3}, "ability_uses": {"phantom_lancer_spirit_lance": 1}, "hero_hits": {"phantom_lancer_spirit_lance": 1, "null": 4}, "damage": {"npc_dota_creep_badguys_melee": 695, "npc_dota_creep_goodguys_melee": 1436, "npc_dota_creep_badguys_ranged": 239, "npc_dota_creep_goodguys_ranged": 927, "npc_dota_hero_pudge": 224}, "damage_taken": {"npc_dota_creep_goodguys_ranged": 220, "npc_dota_creep_goodguys_melee": 127}, "damage_inflictor": {"phantom_lancer_spirit_lance": 76, "null": 148}, "runes": {"5": 1}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {}, "randomed": false, "pred_vict": true, "gold": 982, "lh": 12, "xp": 780, "x": 82, "y": 170, "hero_inventory": [{"id": "item_tango", "num_charges": 2, "cooldown": 0}, {"id": "item_flask", "num_charges": 1, "cooldown": 0}, {"id": "item_enchanted_mango", "cooldown": 0}, {"id": "item_stout_shield", "cooldown": 0}, {"id": "item_quelling_blade", "cooldown": 0}, {"id": "item_branches", "cooldown": 0}], "hero_stash": [], "health": 650, "max_health": 720, "max_mana": 386.938, "level": 3, "kills": 0, "deaths": 0, "assists": 1, "denies": 13, "nearby_creep_death_count": 30}, {"player_slot": 129, "hero_id": 21, "hero_name": "npc_dota_hero_windrunner", "account_id_hash": "0472e177a478eb381f3534446f80cd2a", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 2, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": -5.465, "max": true, "inflictor": null, "unit": "npc_dota_hero_windrunner", "key": "npc_dota_hero_huskar", "value": 50, "slot": 6, "player_slot": 129}, "times": [0, 60, 120], "gold_t": [1, 251, 561], "lh_t": [0, 0, 5], "dn_t": [0, 1, 4], "xp_t": [0, 58, 445], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "orb_of_venom"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "tango"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": 23.428, "key": "magic_wand"}, {"time": 23.428, "key": "magic_stick"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 1.7, "key": 5}, {"time": 8.565, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 575, "2": 4, "4": 77, "11": 3, "15": 10, "16": 6, "19": 3}, "pings": {}, "purchase": {"orb_of_venom": 1, "branches": 2, "tango": 1, "enchanted_mango": 1, "tpscroll": 1, "magic_wand": 1, "magic_stick": 1}, "gold_reasons": {"0": 760, "13": 393}, "xp_reasons": {"2": 706}, "killed": {"npc_dota_creep_badguys_ranged": 159, "npc_dota_creep_goodguys_melee": 350, "npc_dota_creep_badguys_melee": 148, "npc_dota_creep_goodguys_ranged": 110}, "item_uses": {}, "ability_uses": {}, "hero_hits": {"null": 8, "orb_of_venom": 14}, "damage": {"npc_dota_hero_huskar": 402, "npc_dota_creep_goodguys_melee": 460, "npc_dota_creep_badguys_ranged": 265, "npc_dota_creep_badguys_melee": 740, "npc_dota_creep_goodguys_ranged": 110}, "damage_taken": {"npc_dota_hero_huskar": 64, "npc_dota_creep_goodguys_melee": 95, "npc_dota_creep_goodguys_ranged": 31}, "damage_inflictor": {"null": 360, "orb_of_venom": 42}, "runes": {"5": 2}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {"null": 40, "huskar_burning_spear": 24}, "randomed": false, "pred_vict": true, "gold": 788, "lh": 9, "xp": 706, "x": 174, "y": 90, "hero_inventory": [{"id": "item_orb_of_venom", "cooldown": 0}, {"id": "item_tango", "num_charges": 3, "cooldown": 0}, {"id": "item_flask", "num_charges": 1, "cooldown": 0}, {"id": "item_magic_wand", "cooldown": 0}, {"id": "item_tpscroll", "num_charges": 1, "cooldown": 0}], "hero_stash": [], "health": 640, "max_health": 640, "max_mana": 422.938, "level": 3, "kills": 0, "deaths": 0, "assists": 0, "denies": 6, "nearby_creep_death_count": 23}, {"player_slot": 130, "hero_id": 60, "hero_name": "npc_dota_hero_night_stalker", "account_id_hash": "fc1271b29e684b9e7f39817b94db73dd", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 2, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0

In [ ]:
# path = "DOTA 2//train_matches.jsonl"
# count = 0

# with open(path, "rb") as f:
#     for block in iter(lambda: f.read(1024 * 1024), b""):  # читаем по 1 МБ
#         count += block.count(b"\n")

# print("Строк в файле:", count)

Строк в файле: 33723

In [ ]:
# path = "DOTA 2//test_matches.jsonl"
# with open(path, "r", encoding="utf-8") as f:
#     for line in itertools.islice(f, 5):  # первые 5 строк
#         print(line.strip())

{"game_time": 1249, "match_id_hash": "4b6e4e511d399180776d0f23984466b2", "teamfights": [{"start": 335.581, "end": 369.61, "last_death": 354.114, "deaths": 3, "players": [{"deaths_pos": {}, "ability_uses": {"sandking_sand_storm": 1}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 157, "xp_delta": 166}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 84, "xp_delta": 111}, {"deaths_pos": {}, "ability_uses": {"furion_teleportation": 1}, "item_uses": {"magic_wand": 1, "phase_boots": 1}, "killed": {"npc_dota_hero_earthshaker": 71}, "deaths": 0, "buybacks": 0, "damage": 522, "healing": 0, "gold_delta": 170, "xp_delta": 23}, {"deaths_pos": {}, "ability_uses": {"chaos_knight_reality_rift": 1, "chaos_knight_chaos_bolt": 1}, "item_uses": {"power_treads": 3, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 307, "healing": 120, "gold_delta": -117, "xp_delta": 80}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 108, "healing": 0, "gold_delta": 93, "xp_delta": 228}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 178, "xp_delta": 285}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {"quelling_blade": 2}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 291, "xp_delta": 335}, {"deaths_pos": {}, "ability_uses": {"earthshaker_enchant_totem": 2, "earthshaker_fissure": 1}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 463, "healing": 0, "gold_delta": 130, "xp_delta": 298}, {"deaths_pos": {}, "ability_uses": {"venomancer_plague_ward": 4, "venomancer_venomous_gale": 1}, "item_uses": {}, "killed": {"npc_dota_hero_furion": 8}, "deaths": 0, "buybacks": 0, "damage": 94, "healing": 0, "gold_delta": 474, "xp_delta": 493}, {"deaths_pos": {}, "ability_uses": {"oracle_purifying_flames": 2, "oracle_fortunes_end": 1}, "item_uses": {"tpscroll": 1}, "killed": {"npc_dota_hero_chaos_knight": 41}, "deaths": 0, "buybacks": 0, "damage": 459, "healing": 0, "gold_delta": 426, "xp_delta": 460}]}, {"start": 742.049, "end": 793.573, "last_death": 778.443, "deaths": 4, "players": [{"deaths_pos": {}, "ability_uses": {"sandking_sand_storm": 1}, "item_uses": {"blink": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 499, "xp_delta": 178}, {"deaths_pos": {}, "ability_uses": {"riki_smoke_screen": 1, "riki_blink_strike": 1}, "item_uses": {"phase_boots": 4, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 68, "healing": 15, "gold_delta": 311, "xp_delta": 384}, {"deaths_pos": {}, "ability_uses": {"furion_sprout": 1, "furion_wrath_of_nature": 1}, "item_uses": {"ancient_janggo": 1, "phase_boots": 2, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 145, "healing": 135, "gold_delta": 919, "xp_delta": 0}, {"deaths_pos": {}, "ability_uses": {"chaos_knight_phantasm": 1, "chaos_knight_reality_rift": 2, "chaos_knight_chaos_bolt": 1}, "item_uses": {"armlet": 3, "magic_wand": 1}, "killed": {"npc_dota_hero_oracle": 118}, "deaths": 0, "buybacks": 0, "damage": 2372, "healing": 321, "gold_delta": 290, "xp_delta": 57}, {"deaths_pos": {}, "ability_uses": {"tinker_march_of_the_machines": 5, "tinker_rearm": 6, "tinker_heat_seeking_missile": 2, "tinker_laser": 1}, "item_uses": {"bottle": 15, "soul_ring": 4, "travel_boots": 4, "magic_stick": 1}, "killed": {"npc_dota_hero_venomancer": 271}, "deaths": 0, "buybacks": 0, "damage": 1846, "healing": 581, "gold_delta": 646, "xp_delta": 663}, {"deaths_pos": {}, "ability_uses": {"nyx_assassin_vendetta": 1, "nyx_assassin_impale": 1, "nyx_assassin_mana_burn": 2, "nyx_assassin_spiked_carapace": 1}, "item_uses": {"clarity": 1, "power_treads": 6, "quelling_blade": 1, "magic_wand": 1}, "killed": {"npc_dota_hero_furion": 74}, "deaths": 0, "buybacks": 0, "damage": 1422, "healing": 75, "gold_delta": 377, "xp_delta": 702}, {"deaths_pos": {}, "ability_uses": {"terrorblade_conjure_image": 2}, "item_uses": {"power_treads": 3, "quelling_blade": 2}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 205, "healing": 0, "gold_delta": 378, "xp_delta": 605}, {"deaths_pos": {}, "ability_uses": {"earthshaker_echo_slam": 1, "earthshaker_enchant_totem": 4}, "item_uses": {"arcane_boots": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 454, "healing": 0, "gold_delta": 540, "xp_delta": 932}, {"deaths_pos": {}, "ability_uses": {"venomancer_plague_ward": 4, "venomancer_venomous_gale": 1}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 425, "healing": 0, "gold_delta": 284, "xp_delta": 567}, {"deaths_pos": {}, "ability_uses": {"oracle_false_promise": 1, "oracle_fortunes_end": 1, "oracle_purifying_flames": 1}, "item_uses": {"magic_wand": 1, "flask": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 382, "healing": 713, "gold_delta": 142, "xp_delta": 421}]}, {"start": 956.929, "end": 1009.12, "last_death": 993.957, "deaths": 4, "players": [{"deaths_pos": {}, "ability_uses": {}, "item_uses": {"blink": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 0, "xp_delta": 0}, {"deaths_pos": {}, "ability_uses": {"riki_smoke_screen": 1, "riki_blink_strike": 2, "riki_tricks_of_the_trade": 1}, "item_uses": {"tpscroll": 1, "phase_boots": 5, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 812, "healing": 210, "gold_delta": 394, "xp_delta": 1326}, {"deaths_pos": {}, "ability_uses": {"furion_sprout": 2, "furion_force_of_nature": 1, "furion_teleportation": 1, "furion_wrath_of_nature": 1}, "item_uses": {"magic_wand": 2, "phase_boots": 3, "ancient_janggo": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 684, "healing": 135, "gold_delta": 254, "xp_delta": 700}, {"deaths_pos": {}, "ability_uses": {"chaos_knight_phantasm": 1, "chaos_knight_reality_rift": 4, "chaos_knight_chaos_bolt": 1}, "item_uses": {"magic_wand": 3, "armlet": 3, "power_treads": 1, "tpscroll": 1}, "killed": {"npc_dota_hero_terrorblade": 117, "npc_dota_hero_venomancer": 71, "npc_dota_hero_oracle": 115, "npc_dota_hero_nyx_assassin": 107}, "deaths": 0, "buybacks": 0, "damage": 4169, "healing": 238, "gold_delta": 1263, "xp_delta": 1385}, {"deaths_pos": {}, "ability_uses": {"tinker_rearm": 5, "tinker_heat_seeking_missile": 4, "tinker_march_of_the_machines": 2, "tinker_laser": 1}, "item_uses": {"soul_ring": 5, "bottle": 13, "blink": 4, "magic_stick": 1, "travel_boots": 4}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 2369, "healing": 771, "gold_delta": 347, "xp_delta": 928}, {"deaths_pos": {}, "ability_uses": {"nyx_assassin_mana_burn": 1, "nyx_assassin_impale": 2, "nyx_assassin_spiked_carapace": 1}, "item_uses": {"magic_wand": 2, "meteor_hammer": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 2300, "healing": 90, "gold_delta": -107, "xp_delta": 188}, {"deaths_pos": {}, "ability_uses": {"terrorblade_reflection": 1, "terrorblade_metamorphosis": 1}, "item_uses": {"quelling_blade": 1, "tpscroll": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 205, "healing": 0, "gold_delta": -180, "xp_delta": 136}, {"deaths_pos": {}, "ability_uses": {"earthshaker_echo_slam": 1, "earthshaker_enchant_totem": 3, "earthshaker_fissure": 2}, "item_uses": {"blink": 2, "magic_stick": 1, "tpscroll": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 1359, "healing": 30, "gold_delta": 380, "xp_delta": 478}, {"deaths_pos": {}, "ability_uses": {"venomancer_plague_ward": 2}, "item_uses": {"tpscroll": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 538, "healing": 0, "gold_delta": -70, "xp_delta": 84}, {"deaths_pos": {}, "ability_uses": {"oracle_fates_edict": 2, "oracle_purifying_flames": 3, "oracle_false_promise": 1, "oracle_fortunes_end": 1}, "item_uses": {"arcane_boots": 1, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 93, "healing": 1078, "gold_delta": -114, "xp_delta": 78}]}, {"start": 1088.797, "end": 1136.089, "last_death": 1120.993, "deaths": 4, "players": [{"deaths_pos": {}, "ability_uses": {"sandking_epicenter": 1, "sandking_burrowstrike": 1, "sandking_sand_storm": 1}, "item_uses": {"tpscroll": 1, "blink": 1, "soul_ring": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 1596, "healing": 0, "gold_delta": -156, "xp_delta": 156}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {"phase_boots": 4}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 171, "xp_delta": 802}, {"deaths_pos": {}, "ability_uses": {"furion_teleportation": 1, "furion_force_of_nature": 1, "furion_sprout": 1}, "item_uses": {"phase_boots": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": -131, "xp_delta": 176}, {"deaths_pos": {}, "ability_uses": {"chaos_knight_reality_rift": 1, "chaos_knight_chaos_bolt": 1, "chaos_knight_phantasm": 1}, "item_uses": {"armlet": 5, "power_treads": 2, "tpscroll": 1, "magic_wand": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 1678, "healing": 573, "gold_delta": -94, "xp_delta": 297}, {"deaths_pos": {}, "ability_uses": {"tinker_rearm": 6, "tinker_laser": 1, "tinker_heat_seeking_missile": 5, "tinker_march_of_the_machines": 1}, "item_uses": {"bottle": 14, "soul_ring": 5, "travel_boots": 3, "blink": 2, "magic_stick": 1}, "killed": {"npc_dota_hero_venomancer": 272}, "deaths": 0, "buybacks": 0, "damage": 1897, "healing": 552, "gold_delta": 350, "xp_delta": 502}, {"deaths_pos": {}, "ability_uses": {"nyx_assassin_mana_burn": 2, "nyx_assassin_spiked_carapace": 1, "nyx_assassin_impale": 1, "nyx_assassin_vendetta": 1}, "item_uses": {"meteor_hammer": 1, "magic_wand": 1}, "killed": {"npc_dota_hero_furion": 108}, "deaths": 0, "buybacks": 0, "damage": 1218, "healing": 165, "gold_delta": 672, "xp_delta": 934}, {"deaths_pos": {}, "ability_uses": {"terrorblade_conjure_image": 3, "terrorblade_reflection": 1}, "item_uses": {"force_staff": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 463, "healing": 0, "gold_delta": 459, "xp_delta": 619}, {"deaths_pos": {}, "ability_uses": {"earthshaker_fissure": 2, "earthshaker_enchant_totem": 2, "earthshaker_echo_slam": 1}, "item_uses": {"blink": 3, "force_staff": 1, "magic_stick": 1, "arcane_boots": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 1533, "healing": 120, "gold_delta": 443, "xp_delta": 948}, {"deaths_pos": {}, "ability_uses": {"venomancer_plague_ward": 5, "venomancer_venomous_gale": 1, "venomancer_poison_nova": 1}, "item_uses": {"magic_wand": 1, "power_treads": 1}, "killed": {"npc_dota_hero_sand_king": 82}, "deaths": 0, "buybacks": 0, "damage": 1666, "healing": 8, "gold_delta": 736, "xp_delta": 896}, {"deaths_pos": {}, "ability_uses": {"oracle_purifying_flames": 3, "oracle_fortunes_end": 1, "oracle_false_promise": 1}, "item_uses": {"arcane_boots": 1}, "killed": {"npc_dota_hero_chaos_knight": 280}, "deaths": 0, "buybacks": 0, "damage": 512, "healing": 0, "gold_delta": 951, "xp_delta": 856}]}, {"start": 1143.45, "end": 1178.612, "last_death": 1163.483, "deaths": 3, "players": [{"deaths_pos": {}, "ability_uses": {}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 0, "xp_delta": 0}, {"deaths_pos": {}, "ability_uses": {"riki_blink_strike": 2, "riki_smoke_screen": 2, "riki_tricks_of_the_trade": 1}, "item_uses": {"ward_dispenser": 1, "phase_boots": 4, "ring_of_aquila": 1, "magic_wand": 1}, "killed": {"npc_dota_hero_oracle": 110}, "deaths": 0, "buybacks": 0, "damage": 911, "healing": 135, "gold_delta": 324, "xp_delta": 1329}, {"deaths_pos": {}, "ability_uses": {"furion_wrath_of_nature": 1, "furion_teleportation": 1, "furion_force_of_nature": 1, "furion_sprout": 1}, "item_uses": {"phase_boots": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 509, "healing": 0, "gold_delta": 23, "xp_delta": 19}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 0, "xp_delta": 0}, {"deaths_pos": {}, "ability_uses": {"tinker_rearm": 3, "tinker_march_of_the_machines": 1, "tinker_heat_seeking_missile": 2, "tinker_laser": 1}, "item_uses": {"bottle": 4, "blink": 2, "soul_ring": 2, "magic_stick": 1}, "killed": {"npc_dota_hero_nyx_assassin": 332}, "deaths": 0, "buybacks": 0, "damage": 2539, "healing": 175, "gold_delta": 463, "xp_delta": 1331}, {"deaths_pos": {}, "ability_uses": {"nyx_assassin_impale": 1, "nyx_assassin_spiked_carapace": 1}, "item_uses": {"magic_wand": 1, "quelling_blade": 2}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 27, "healing": 75, "gold_delta": -223, "xp_delta": 38}, {"deaths_pos": {}, "ability_uses": {"terrorblade_conjure_image": 2, "terrorblade_reflection": 1, "terrorblade_sunder": 1, "terrorblade_metamorphosis": 1}, "item_uses": {"force_staff": 1, "power_treads": 3, "quelling_blade": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 1386, "healing": 830, "gold_delta": 232, "xp_delta": 682}, {"deaths_pos": {}, "ability_uses": {"earthshaker_fissure": 1}, "item_uses": {"blink": 2, "force_staff": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 201, "healing": 0, "gold_delta": 0, "xp_delta": 45}, {"deaths_pos": {}, "ability_uses": {}, "item_uses": {"tpscroll": 1, "hand_of_midas": 1}, "killed": {}, "deaths": 0, "buybacks": 0, "damage": 0, "healing": 0, "gold_delta": 200, "xp_delta": 184}, {"deaths_pos": {}, "ability_uses": {"oracle_fates_edict": 1, "oracle_purifying_flames": 2, "oracle_fortunes_end": 1}, "item_uses": {"magic_wand": 1, "dust": 1}, "killed": {"npc_dota_hero_furion": 102}, "deaths": 0, "buybacks": 0, "damage": 348, "healing": 1014, "gold_delta": 392, "xp_delta": 752}]}], "objectives": [{"time": 614.883, "type": "CHAT_MESSAGE_TOWER_DENY", "team": 60, "slot": 8, "player_slot": 131}, {"time": 719.124, "type": "CHAT_MESSAGE_TOWER_KILL", "team": 2, "slot": -1}, {"time": 764.113, "type": "CHAT_MESSAGE_TOWER_KILL", "team": 2, "slot": 2, "player_slot": 2}, {"time": 1059.041, "type": "CHAT_MESSAGE_TOWER_KILL", "team": 2, "slot": 3, "player_slot": 3}, {"time": 1120.56, "type": "CHAT_MESSAGE_TOWER_KILL", "team": 3, "slot": 8, "player_slot": 131}], "chat": [{"player_slot": 4, "time": 512.375, "text": "*****"}, {"player_slot": 4, "time": 514.441, "text": "******"}, {"player_slot": 4, "time": 516.974, "text": "** **** ***"}, {"player_slot": 1, "time": 655.54, "text": "))"}], "game_mode": 22, "lobby_type": 7, "players": [{"player_slot": 0, "hero_id": 16, "hero_name": "npc_dota_hero_sand_king", "account_id_hash": "5f8e7c02c758eb0a517002e7484a7918", "ability_upgrades": [{"ability": 5102, "time": 308, "level": 1}, {"ability": 5103, "time": 502, "level": 2}, {"ability": 5103, "time": 639, "level": 3}, {"ability": 5102, "time": 792, "level": 4}, {"ability": 5102, "time": 911, "level": 5}, {"ability": 5103, "time": 995, "level": 6}, {"ability": 5103, "time": 1037, "level": 7}], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 6, "camps_stacked": 3, "rune_pickups": 11, "firstblood_claimed": 0, "teamfight_participation": 0.238, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 50.655, "max_hero_hit": {"type": "max_hero_hit", "time": 948.502, "max": true, "inflictor": "sandking_burrowstrike", "unit": "npc_dota_hero_sand_king", "key": "npc_dota_hero_terrorblade", "value": 214, "slot": 0, "player_slot": 0}, "times": [0, 60, 120, 180, 240, 300, 360, 420, 480, 540, 600, 660, 720, 780, 840, 900, 960, 1020, 1080, 1140, 1200], "gold_t": [1, 211, 328, 419, 718, 909, 1073, 1248, 1469, 1707, 1829, 2182, 2777, 3480, 3690, 3781, 4420, 4511, 5095, 5472, 5700], "lh_t": [0, 0, 0, 0, 2, 2, 6, 6, 10, 12, 13, 17, 25, 30, 32, 32, 38, 38, 43, 43, 46], "dn_t": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 4], "xp_t": [0, 49, 125, 202, 427, 579, 786, 849, 1166, 1620, 1710, 2123, 2827, 3141, 3271, 3278, 3764, 3821, 4478, 4634, 4799], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.861, "key": "tango"}, {"time": -89.861, "key": "orb_of_venom"}, {"time": -89.861, "key": "tpscroll"}, {"time": -83.326, "key": "clarity"}, {"time": -82.393, "key": "tango"}, {"time": 223.046, "key": "boots"}, {"time": 264.935, "key": "wind_lace"}, {"time": 265.335, "key": "tpscroll"}, {"time": 427.229, "key": "tranquil_boots"}, {"time": 427.229, "key": "ring_of_regen"}, {"time": 435.594, "key": "tpscroll"}, {"time": 789.574, "key": "blink"}, {"time": 989.792, "key": "tpscroll"}, {"time": 1058.875, "key": "ring_of_regen"}, {"time": 1059.008, "key": "gauntlets"}, {"time": 1059.141, "key": "gauntlets"}, {"time": 1059.308, "key": "soul_ring"}, {"time": 1151.819, "key": "tpscroll"}, {"time": 1152.152, "key": "tpscroll"}, {"time": 1218.536, "key": "tome_of_knowledge"}, {"time": 1246.729, "key": "tpscroll"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 1.766, "key": 5}, {"time": 185.255, "key": 5}, {"time": 360.279, "key": 5}, {"time": 748.517, "key": 5}, {"time": 755.182, "key": 5}, {"time": 916.276, "key": 5}, {"time": 920.409, "key": 5}, {"time": 1016.252, "key": 3}, {"time": 1046.978, "key": 5}, {"time": 1081.836, "key": 5}, {"time": 1088.301, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 3929, "2": 2, "4": 395, "5": 18, "6": 20, "7": 4, "8": 24, "10": 35, "11": 10, "14": 2, "15": 35, "16": 21, "19": 3, "27": 1, "33": 35}, "pings": {"0": 1}, "purchase": {"tango": 2, "orb_of_venom": 1, "tpscroll": 7, "clarity": 1, "boots": 1, "wind_lace": 1, "tranquil_boots": 1, "ring_of_regen": 2, "blink": 1, "gauntlets": 2, "soul_ring": 1, "recipe_soul_ring": 1, "tome_of_knowledge": 1}, "gold_reasons": {"0": 1763, "1": -645, "11": 500, "12": 264, "13": 2061}, "xp_reasons": {"0": 1, "1": 437, "2": 4734}, "killed": {"npc_dota_creep_badguys_melee": 1803, "npc_dota_neutral_satyr_trickster": 119, "npc_dota_neutral_satyr_soulstealer": 105, "npc_dota_neutral_dark_troll": 114, "npc_dota_neutral_dark_troll_warlord": 30, "npc_dota_neutral_satyr_hellcaller": 24, "npc_dota_neutral_polar_furbolg_ursa_warrior": 30, "npc_dota_neutral_polar_furbolg_champion": 24, "npc_dota_creep_goodguys_melee": 200, "npc_dota_creep_badguys_ranged": 698, "npc_dota_creep_goodguys_ranged": 77, "npc_dota_neutral_centaur_outrunner": 40, "npc_dota_neutral_centaur_khan": 50}, "item_uses": {"tango": 6, "tpscroll": 5, "clarity": 1, "blink": 10, "soul_ring": 2}, "ability_uses": {"sandking_burrowstrike": 18, "sandking_sand_storm": 19, "sandking_epicenter": 1}, "hero_hits": {"null": 34, "orb_of_venom": 51, "sandking_burrowstrike": 18, "sandking_sand_storm": 35, "sandking_epicenter": 10}, "damage": {"npc_dota_hero_venomancer": 1807, "npc_dota_hero_earthshaker": 957, "npc_dota_hero_terrorblade": 1337, "illusion_npc_dota_hero_terrorblade": 6083, "npc_dota_creep_badguys_melee": 12000, "npc_dota_hero_oracle": 879, "npc_dota_creep_badguys_ranged": 2743, "npc_dota_neutral_centaur_outrunner": 758, "npc_dota_neutral_satyr_soulstealer": 1745, "npc_dota_neutral_satyr_trickster": 719, "npc_dota_neutral_enraged_wildkin": 117, "npc_dota_neutral_wildkin": 120, "npc_dota_neutral_dark_troll": 2040, "npc_dota_neutral_dark_troll_warlord": 1620, "npc_dota_neutral_polar_furbolg_ursa_warrior": 1878, "npc_dota_neutral_polar_furbolg_champion": 1248, "npc_dota_hero_nyx_assassin": 996, "npc_dota_neutral_satyr_hellcaller": 1003, "npc_dota_creep_goodguys_melee": 381, "npc_dota_badguys_siege": 216, "npc_dota_creep_goodguys_ranged": 141, "npc_dota_neutral_centaur_khan": 920}, "damage_taken": {"npc_dota_hero_venomancer": 2019, "npc_dota_hero_earthshaker": 1277, "npc_dota_creep_badguys_ranged": 330, "npc_dota_creep_badguys_melee": 584, "npc_dota_hero_oracle": 2148, "npc_dota_hero_terrorblade": 644, "npc_dota_neutral_centaur_outrunner": 12, "npc_dota_neutral_wildkin": 26, "npc_dota_neutral_enraged_wildkin": 43, "npc_dota_neutral_satyr_trickster": 4, "npc_dota_neutral_satyr_soulstealer": 16, "npc_dota_neu

In [ ]:
# path = "DOTA 2//test_matches.jsonl"
# count = 0

# with open(path, "rb") as f:
#     for block in iter(lambda: f.read(1024 * 1024), b""):  # читаем по 1 МБ
#         count += block.count(b"\n")

# print("Строк в файле:", count)

Строк в файле: 5952

In [ ]:
# src = "DOTA 2//train_matches.jsonl"
# dst = "train_matches_sample.jsonl"

# step = 1  # каждую сотую строку берём в семпл

# with open(src, "r", encoding="utf-8") as fin, open(dst, "w", encoding="utf-8") as fout:
#     for i, line in enumerate(fin, start=1):
#         if not line.strip():
#             continue
#         if i % step == 0:
#             fout.write(line)

# print("Готово, семпл сохранён в", dst)

Готово, семпл сохранён в train_matches_sample.jsonl

# Предобработка

In [39]:
# import json

# jsonl_path = "DOTA 2/train_matches.jsonl"

# # set со всеми match_id_hash из файла
# jsonl_ids = set()

# with open(jsonl_path, "r", encoding="utf8") as f:
#     for line in f:
#         obj = json.loads(line)
#         jsonl_ids.add(obj["match_id_hash"])

# print("ID в JSONL:", len(jsonl_ids))

In [40]:
# feature_ids = set(raw_features["match_id_hash"])

# print("ID в таблице:", len(feature_ids))

# missing = jsonl_ids - feature_ids
# print("Отсутствуют:", len(missing))

# if missing:
#     print("Примеры отсутствующих:", list(missing)[:10])
# else:
#     print("Все match_id_hash присутствуют")

In [41]:
# import json

# train_path = "DOTA 2/train_matches.jsonl"
# test_path = "DOTA 2/test_matches.jsonl"

# def load_ids(path):
#     ids = set()
#     with open(path, "r", encoding="utf8") as f:
#         for line in f:
#             obj = json.loads(line)
#             ids.add(obj["match_id_hash"])
#     return ids

# # Загружаем id из обоих файлов
# train_ids = load_ids(train_path)
# test_ids = load_ids(test_path)

# # Объединяем множества
# jsonl_ids = train_ids.union(test_ids)

# print("ID в train:", len(train_ids))
# print("ID в test:", len(test_ids))
# print("Всего уникальных ID:", len(jsonl_ids))

# # ID из твоей таблицы признаков
# feature_ids = set(raw_features["match_id_hash"])

# print("ID в таблице:", len(feature_ids))

# # Проверка отсутствующих
# missing = jsonl_ids - feature_ids
# print("Отсутствуют:", len(missing))

# if missing:
#     print("Примеры отсутствующих:", list(missing)[:10])
# else:
#     print("Все match_id_hash присутствуют в таблице признаков")

In [42]:
# import json

# train_path = "DOTA 2/train_matches.jsonl"
# test_path = "DOTA 2/test_matches.jsonl"

# def load_ids(path):
#     ids = set()
#     with open(path, "r", encoding="utf8") as f:
#         for line in f:
#             obj = json.loads(line)
#             ids.add(obj["match_id_hash"])
#     return ids

# # Загружаем id из обоих файлов
# train_ids = load_ids(train_path)
# test_ids = load_ids(test_path)

# # Объединяем множества
# jsonl_ids = train_ids.union(test_ids)

# print("ID в train:", len(train_ids))
# print("ID в test:", len(test_ids))
# print("Всего уникальных ID:", len(jsonl_ids))

# # ID из твоей таблицы признаков
# feature_ids = set(test_features["match_id_hash"])

# print("ID в таблице:", len(feature_ids))

# # Проверка отсутствующих
# missing = jsonl_ids - feature_ids
# print("Отсутствуют:", len(missing))

# if missing:
#     print("Примеры отсутствующих:", list(missing)[:10])
# else:
#     print("Все match_id_hash присутствуют в таблице признаков")

In [43]:
# df = pd.read_json("train_matches_sample.jsonl", lines=True)
# df.head()

In [44]:
# df['players'][1]

In [41]:
X.head()

,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed,r1_pred_vict,r2_pred_vict,r3_pred_vict,r4_pred_vict,r5_pred_vict,d1_pred_vict,d2_pred_vict,d3_pred_vict,d4_pred_vict,d5_pred_vict,r1_hero_name,r2_hero_name,r3_hero_name,r4_hero_name,r5_hero_name,d1_hero_name,d2_hero_name,d3_hero_name,d4_hero_name,d5_hero_name,r1_damage,r2_damage,r3_damage,r4_damage,r5_damage,d1_damage,d2_damage,d3_damage,d4_damage,d5_damage,r1_total_damage,r1_hero_damage,r2_total_damage,r2_hero_damage,r3_total_damage,r3_hero_damage,r4_total_damage,r4_hero_damage,r5_total_damage,r5_hero_damage,d1_total_damage,d1_hero_damage,d2_total_damage,d2_hero_damage,d3_total_damage,d3_hero_damage,d4_total_damage,d4_hero_damage,d5_total_damage,d5_hero_damage,r1_gold_t,r2_gold_t,r3_gold_t,r4_gold_t,r5_gold_t,d1_gold_t,d2_gold_t,d3_gold_t,d4_gold_t,d5_gold_t,r1_xp_t,r2_xp_t,r3_xp_t,r4_xp_t,r5_xp_t,d1_xp_t,d2_xp_t,d3_xp_t,d4_xp_t,d5_xp_t,r1_lh_t,r2_lh_t,r3_lh_t,r4_lh_t,r5_lh_t,d1_lh_t,d2_lh_t,d3_lh_t,d4_lh_t,d5_lh_t,r1_dn_t,r2_dn_t,r3_dn_t,r4_dn_t,r5_dn_t,d1_dn_t,d2_dn_t,d3_dn_t,d4_dn_t,d5_dn_t,radiant_total_gold,dire_total_gold,radiant_gold_advantage,radiant_total_kills,dire_total_kills,radiant_kills_advantage,radiant_total_deaths,dire_total_deaths,radiant_deaths_advantage,radiant_total_level,dire_total_level,radiant_level_advantage,radiant_total_hero_damage,dire_total_hero_damage,radiant_hero_damage_advantage,radiant_total_total_damage,dire_total_total_damage,radiant_total_damage_advantage,total_kills_deaths
0,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.0,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,True,True,False,False,False,nevermore,brewmaster,pudge,huskar,lycan,phantom_lancer,windrunner,night_stalker,ogre_magi,tinker,"{'npc_dota_creep_goodguys_melee': 92, 'npc_dot...","{'npc_dota_creep_goodguys_ranged': 113, 'npc_d...","{'npc_dota_hero_ogre_magi': 16, 'npc_dota_hero...","{'npc_dota_creep_badguys_melee': 497, 'npc_dot...","{'npc_dota_neutral_satyr_soulstealer': 1286, '...","{'npc_dota_creep_badguys_melee': 695, 'npc_dot...","{'npc_dota_hero_huskar': 402, 'npc_dota_creep_...","{'npc_dota_hero_huskar': 635, 'npc_dota_creep_...",{'npc_dota_hero_pudge': 868},"{'npc_dota_hero_nevermore': 704, 'npc_dota_cre...",1287,459,1327,0,32,32,1000,457,5090,0,3521,224,1977,402,747,635,868,868,2332,820,"[1, 91, 356]","[1, 91, 262]","[1, 91, 182]","[1, 169, 260]","[1, 91, 281]","[1, 331, 738]","[1, 251, 561]","[1, 251, 342]","[1, 251, 342]","[1, 425, 680]","[0, 107, 387]","[0, 38, 318]","[0, 0, 73]","[0, 202, 301]","[0, 38, 238]","[0, 85, 431]","[0, 58, 445]","[0, 41, 229]","[0, 85, 329]","[0, 240, 616]","[0, 0, 4]","[0, 0, 2]","[0, 0, 0]","[0, 2, 2]","[0, 0, 5]","[0, 2, 9]","[0, 0, 5]","[0, 0, 0]","[0, 0, 0]","[0, 4, 8]","[0, 0, 0]","[0, 0, 2]","[0, 0, 0]","[0, 1, 1]","[0, 0, 0]","[0, 4, 12]","[0, 1, 4]","[0, 0, 1]","[0, 0, 0]","[0, 0, 0]",2037,3948,-1911,0,1,-1,1,0,1,9,13,-4,948,2949,-2001,8736,9445,-709,2
1,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.5,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,False,False,False,False,False,razor,centaur,shadow_shaman,weaver,naga_siren,enchantress,pudge,antimage,clinkz,visage,"{'npc_dota_hero_pudge': 2298, 'npc_dota_hero_c...","{'npc_dota_creep_goodguys_ranged': 194, 'npc_d...","{'npc_dota_hero_clinkz': 122, 'npc_dota_hero_p...","{'npc_dota_creep_goodguys_ranged': 622, 'npc_d...","{'npc_dota_hero_clinkz': 1021, 'npc_dota_hero_...","{'npc_dota_hero_centaur': 2252, 'npc_dota_neut...","{'npc_dota_hero_shadow_shaman': 890, 'npc_dota...","{'npc_dota_hero_centaur': 1617, 'npc_dota_cree...","{'npc_dota_hero_shadow_shaman': 258, 'npc_dota...","{'npc_dota_creep_goodguys_melee': 903, 'npc_do...",20882,4656,14983,5096,5941,1091,21394,4708,6565,1912,13575,2871,9643,4141,13855,2054,7437,3071,2308,926,"[41, 819, 1196, 1467, 1839, 2356, 2812, 3444, ...","[41, 211, 340, 589, 762, 1209, 1579, 1803, 240...","[41, 211, 302, 393, 530, 621, 712, 877, 968, 1...","[41, 292, 750, 922, 1644, 1875, 2042, 2623, 28...","[41, 541, 632, 723, 814, 1100, 1406, 1769, 186...","[1, 131, 295, 458, 592, 814, 1002, 1194, 1460,...","[1, 426, 617, 735, 908, 1095, 1383, 1473, 1564...","[1, 225, 396, 742, 1223, 1707, 1798, 2077, 231...","[1, 182, 315, 543, 766, 1135, 1226, 1500, 1632...","[1, 131, 379, 647, 738, 881, 972, 1062, 1153, ...","[0, 166, 395, 702, 1038, 1497, 1759, 2387, 282...","[0, 57, 452, 1022, 1103, 1641, 1991, 2388, 306...","[0, 19, 122, 184, 311, 467, 827, 1065, 1121, 1...","[0, 188, 968, 1291, 2209, 2480, 2695, 3298, 34...","[0, 166, 395, 631, 687, 1023, 1582, 1855, 2009...","[0, 0, 183, 384, 528, 1025, 1025, 1391, 1973, ...","[0, 30, 254, 444, 615, 843, 1209, 1329, 1500, ...","[0, 197, 532, 698, 1368, 1719, 1902, 2000, 224...","[0, 87, 458, 631, 997, 1189, 1317, 1656, 1884,...","[0, 188, 510, 945, 1136, 1136, 1136, 1136, 113...","[0, 2, 8, 12, 18, 22, 25, 33, 39, 45, 52]","[0, 0, 1, 5, 8, 9, 10, 13, 15, 17, 19]","[0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]","[0, 2, 4, 6, 9, 12, 14, 21, 25, 28, 33]","[0, 0, 0, 0, 0, 5, 8, 8, 8, 8, 13]","[0, 0, 4, 8, 11, 11, 12, 14, 18, 22, 22]","[0, 0, 2, 4, 6, 8, 12, 12, 12, 12, 12]","[0, 2, 4, 7, 15, 15, 15, 18, 25, 27, 27]","[0, 0, 1, 1, 4, 6, 6, 9, 10, 11, 16]","[0, 0, 4, 8, 8, 8, 8, 8, 8, 8, 8]","[0, 0, 1, 5, 5, 7, 7, 7, 7, 7, 7]","[0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3]","[0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2]","[0, 1, 2, 2, 4, 6, 7, 8, 9, 11, 12]","[0, 0, 0, 1, 1, 2, 3, 3, 3, 3, 4]","[0, 0, 0, 0, 0, 1, 1, 1, 2, 3, 3]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 1, 3, 7, 7, 7, 7, 7, 7, 7]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3]","[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]",18172,13144,5028,16,3,13,4,16,-12,37,30,7,17463,13063,4400,69765,46818,22947,39
2,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.0,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.00,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skywrath_mage,rattletrap,phantom_assassin,dragon_knight,furion,sven,spectre,viper,venomancer,storm_spirit,{},{},{'npc_dota_hero_spectre': 70},{},{},{},{'npc_dota_hero_phantom_assassin': 68},{},{},{},0,0,0,0,70,70,0,0,0,0,0,0,68,68,0,0,0,0,0,0,[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],880,480,400,0,0,0,0,0,0,5,5,0,70,68,2,70,68,2,0
3,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.0,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.00,0,0,2,0,False,False,False,False,False,False,False,False,True,False,pudge,bristleback,skywrath_mage,lion,faceless_void,sven,shredder,juggernaut,doom_bringer,rubick,"{'npc_dota_hero_pudge': 918, 'npc_dota_hero_do...","{'npc_dota_creep_badguys_melee': 6665, 'npc_do...","{'npc_dota_hero_shredder': 4304, 'npc_dota_cre...","{'npc_dota_hero_doom_bringer': 710, 'npc_dota_...","{'npc_dota_creep_badguys_melee': 4949, 'npc_do...","{'npc_dota_neutral_satyr_trickster': 2710, 'np...","{'npc_dota_creep_goodguys_melee': 5060, 'npc_d...","{'npc_dota_creep_goodguys_melee': 6142, 'npc_d...","{'npc_dota_creep_goodguys_melee': 960, 'npc_do...","{'npc_dota_hero_bristleback': 1577, 'npc_dota_...",3350,3130,19497,6101,14140,4468,1819,710,11575,1133,36761,0,8913,2087,13392,2633,6010,1952,3955,1665,"[81, 171, 262, 524, 615, 820, 911, 1105, 1196,...","[81, 171, 499, 658, 924, 1285, 1416, 1968, 213...","[81, 274, 540, 1239, 1455, 2132, 2398, 2706, 3...","[81, 171, 262, 464, 555, 885, 976, 1092, 1272,...","[81, 288, 681, 992, 1374, 1620, 2029, 2418, 26...","[104, 194, 424, 658, 828, 1258, 1491, 1917, 22...","[104, 315, 579, 710, 1014, 1148, 1379, 1865, 2...","[104, 272, 547, 892, 1321, 1602, 1989, 2331, 2...","[104, 262, 427, 625, 821, 1031, 1180, 1539, 17...","[104, 194, 285, 376, 561, 728, 819, 910, 1001,...","[0, 77, 206, 352, 422, 611, 701, 970, 1177, 1311]","[0, 114, 720, 1153, 1539, 2050, 2121, 2548, 28...","[0, 240, 776, 1231, 1616, 2282, 2750, 3318, 36...","[0, 42, 233, 372, 504, 698, 768, 984, 1095, 1194]","[0, 77, 410, 849, 1209, 1460, 1805, 2204, 2817...","[0, 0, 336, 506, 634, 1056, 1283, 1533, 1960, ...","[0, 240, 719, 1028, 1596, 1933, 2275, 2772, 32...","[0, 118, 354, 708, 1096, 1377, 1699, 2010, 219...","[0, 57, 172, 266, 499, 822, 908, 1250, 1504, 1...","[0, 118, 354, 463, 761, 990, 1312, 1494, 1676,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 5, 7, 10, 16, 17, 24, 26, 30]","[0, 2, 6, 11, 14, 20, 24, 27, 33, 37]","[0, 0, 0, 2, 2, 2, 2, 2, 2, 2]","[0, 3, 10, 15, 22, 25, 32, 39, 42, 51]","[0, 0, 7, 10, 12, 24, 29, 36, 47, 56]","[0, 3, 7, 8, 13, 14, 17, 20, 23, 23]","[0, 2, 6, 12, 19, 23, 30, 34, 39, 40]","[0, 1, 3, 4, 6, 8, 9, 12, 15, 15]","[0, 0, 0, 0, 2, 2, 2, 2, 2, 2]","[0, 0, 1, 1, 1, 1, 1, 1, 1, 1]","[0, 0, 0, 0, 1, 2, 2, 2, 2, 2]","[0, 0, 2, 2, 2, 4, 7, 7, 8, 8]","[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]","[0, 2, 9, 12, 14, 15, 17, 21, 23, 28]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 2, 2, 4, 4, 4, 4, 5, 5]","[0, 0, 0, 0, 0, 1, 2, 3, 4, 4]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 1, 1, 1, 1]",13348,11301,2047,6,1,5,2,7,-5,32,28,4,15542,8337,7205,50381,69031,-18650,16
4,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.5,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.25,0,0,0,0,False,False,False,False,False,False,False,False,False,False,skeleton_king,doom_bringer,shadow_shaman,legion_commander,batrider,kunkka,zuus,sniper,gyrocopter,antimage,"{'npc_dota_hero_antimage': 418, 'npc_dota_cree...","{'npc_dota_hero_antimage': 766, 'npc_dota_cree...","{'npc_dota_hero_gyrocopter': 168, 'npc_dota_cr...","{'npc_dota_hero_antimage': 248, 'npc_dota_cree...","{'npc_dota_creep_badguys_melee': 4301, 'npc_do...","{'npc_dota_hero_legion_commander': 134, 'npc_d...","{'npc_dota_creep_goodguys_melee': 4583, 'npc_d...","{'npc_dota_hero_shadow_shaman': 1521, 'npc_dot...","{'npc_dota_hero_shadow_shaman': 447, 'npc_dota...","{'npc_dota_hero_doom_bringer': 672, 'npc_dota_...",4547,655,8519,1534,9178,1299,8946,1523,6723,929,11833,3471,9431,3098,13832,1521,8388,2858,10739,1003,"[21, 191, 282, 481, 610, 820, 988, 1355]","[283, 555, 782, 1030, 1186, 1372, 1488, 1645]","[1, 211, 345, 573, 664, 854, 1024, 1115]","[27, 238, 504, 595, 781, 1149, 1374, 1675]","[1, 171, 356, 515, 700, 944, 1174, 1438]","[1, 210, 339, 468, 823, 1030, 1202, 1293]","[1, 214, 456, 667, 758, 890, 1180, 1326]","[86, 431, 686, 957, 1183, 1457, 1670, 2173]","[165, 389, 556, 981, 1115, 1248, 1431, 1648]","[1, 312, 542, 905, 1217, 1442, 1756, 2077]","[20, 66, 247, 365, 519, 789, 887, 1295]","[20, 80, 278, 524, 678, 1062, 1229, 1511]","[0, 297, 777, 1214, 1694, 2048, 2856, 2856]","[20, 148, 384, 384, 684, 1042, 1343, 1823]","[0, 147, 383, 623, 797, 915, 1090, 1090]","[0, 133, 384, 749, 1053, 1205, 1499, 1624]","[0, 118, 305, 636, 844, 1195, 1439, 1617]","[30, 327, 807, 1301, 1838, 2387, 2684, 3304]","[30, 148, 266, 569, 777, 957, 1236, 1623]","[0, 133, 384, 608, 912, 1235, 1529, 1753]","[0, 0, 0, 1, 2, 3, 5, 9]","[0, 2, 5, 8, 9, 11, 11, 12]","[0, 1, 2, 5, 5, 7, 9, 9]","[0, 1, 5, 5, 7, 13, 16, 21]","[0, 0, 2, 2, 4, 4, 7, 7]","[0, 1, 2, 3, 5, 6, 8, 8]","[0, 1, 4, 7, 7, 8, 9, 10]","[0, 4, 8, 12, 15, 19, 22, 31]","[0, 1, 3, 4, 5, 6, 9, 12]","[0, 3, 6, 12, 16, 19, 23, 28]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 1, 1, 1, 1]","[0, 0, 0, 1, 1, 1, 1, 2]","[0, 0, 0, 0, 0, 0, 0, 0]","[0, 2, 4, 5, 6, 6, 8, 8]",8079,9177,-1098,2,4,-2,4,2,2,25,26,-1,5940,11951,-6011,37913,54223,-16310,12

# Моделирование

## Catboost

In [45]:
hero_cols = [f"r{i}_hero_name" for i in range(1, 6)] + [f"d{i}_hero_name" for i in range(1, 6)]

model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.1,
    depth=7,
    loss_function='Logloss',
    eval_metric='AUC',
    random_state=RANDOM_STATE,
    verbose=100)


X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,      
    random_state=RANDOM_STATE,    
    stratify=y,
    shuffle=True         
)

model.fit(X_train, y_train, cat_features=hero_cols)#, eval_set=(X_test, y_test), verbose=100)

0:	total: 222ms	remaining: 3m 42s
100:	total: 5.04s	remaining: 44.8s
200:	total: 9.8s	remaining: 39s
300:	total: 14.7s	remaining: 34.1s
400:	total: 19.7s	remaining: 29.5s
500:	total: 24.6s	remaining: 24.6s
600:	total: 29.3s	remaining: 19.4s
700:	total: 33.9s	remaining: 14.5s
800:	total: 38.5s	remaining: 9.55s
900:	total: 43.5s	remaining: 4.78s
999:	total: 48.6s	remaining: 0us

# Оценка

In [47]:
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)[:, 1]

accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_proba)

print(f"Accuracy: {accuracy:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

Accuracy: 0.7330
ROC AUC: 0.8205

In [47]:
y_pred

array([ True,  True, False, ..., False,  True,  True])

In [48]:
# model = CatBoostClassifier(
#     iterations=1000,
#     learning_rate=0.1,
#     depth=7,
#     loss_function='Logloss',
#     eval_metric='AUC',
#     random_state=RANDOM_STATE,
#     verbose=100)


# X_train, X_test, y_train, y_test = train_test_split(
#     X, y,
#     test_size=0.25,      
#     random_state=RANDOM_STATE,    
#     stratify=y,
#     shuffle=True         
# )

# model.fit(X_train, y_train)#, eval_set=(X_test, y_test), verbose=100)

# y_pred = model.predict(X_test)
# accuracy = accuracy_score(y_test, y_pred)
# roc_auc = roc_auc_score(y_test, y_pred)

# print(f"Accuracy: {accuracy:.4f}")
# print(f"ROC AUC: {roc_auc:.4f}")

# Выводы